import { Slate } from 'slates';
import { spec } from './spec';
import {
  addOrgUser,
  addTeamMember,
  createAlertRule,
  createAnnotation,
  createContactPoint,
  createDataSource,
  createFolder,
  createSnapshot,
  createTeam,
  deleteAlertRule,
  deleteAnnotation,
  deleteContactPoint,
  deleteDashboard,
  deleteDataSource,
  deleteFolder,
  deleteSnapshot,
  deleteTeam,
  findAnnotations,
  getAlertRule,
  getDashboard,
  getDataSource,
  getNotificationPolicies,
  getTeamMembers,
  listAlertRules,
  listContactPoints,
  listDataSources,
  listFolders,
  listOrgUsers,
  listSnapshots,
  removeOrgUser,
  removeTeamMember,
  saveDashboard,
  searchDashboards,
  searchTeams,
  updateAlertRule,
  updateAnnotation,
  updateDataSource,
  updateFolder,
  updateNotificationPolicies,
  updateOrgUserRole
} from './tools';
import { alertNotification, annotationEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchDashboards,
    getDashboard,
    saveDashboard,
    deleteDashboard,
    listFolders,
    createFolder,
    updateFolder,
    deleteFolder,
    listDataSources,
    getDataSource,
    createDataSource,
    updateDataSource,
    deleteDataSource,
    listAlertRules,
    getAlertRule,
    createAlertRule,
    updateAlertRule,
    deleteAlertRule,
    listContactPoints,
    createContactPoint,
    deleteContactPoint,
    getNotificationPolicies,
    updateNotificationPolicies,
    findAnnotations,
    createAnnotation,
    updateAnnotation,
    deleteAnnotation,
    listSnapshots,
    createSnapshot,
    deleteSnapshot,
    searchTeams,
    createTeam,
    getTeamMembers,
    addTeamMember,
    removeTeamMember,
    deleteTeam,
    listOrgUsers,
    addOrgUser,
    updateOrgUserRole,
    removeOrgUser
  ],
  triggers: [alertNotification, annotationEvents]
});
