import { Slate } from 'slates';
import { spec } from './spec';
import {
  createActionItem,
  createAlert,
  createHeartbeat,
  createIncident,
  deleteActionItem,
  deleteIncident,
  getActionItem,
  getAlert,
  getCurrentUser,
  getIncident,
  listActionItems,
  listAlerts,
  listEnvironments,
  listEscalationPolicies,
  listHeartbeats,
  listIncidents,
  listOnCall,
  listSchedules,
  listServices,
  listSeverities,
  listTeams,
  listUsers,
  listWorkflows,
  manageAlert,
  manageHeartbeat,
  updateActionItem,
  updateIncident
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getCurrentUser,
    getAlert,
    deleteIncident,
    getActionItem,
    deleteActionItem,
    manageHeartbeat,
    listIncidents,
    getIncident,
    createIncident,
    updateIncident,
    listAlerts,
    createAlert,
    manageAlert,
    listOnCall,
    listSchedules,
    listEscalationPolicies,
    listServices,
    listTeams,
    listUsers,
    listActionItems,
    createActionItem,
    updateActionItem,
    listHeartbeats,
    createHeartbeat,
    listWorkflows,
    listSeverities,
    listEnvironments
  ],
  triggers: []
});
