import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAvatarVideo,
  createStreamingToken,
  createVideoFromPrompt,
  deleteAsset,
  deleteTranslation,
  deleteVideo,
  generateFromTemplate,
  generateSpeech,
  getCurrentUser,
  getFileUrl,
  getRemainingQuota,
  getTemplate,
  getTranslationStatus,
  getVideoAgentStatus,
  getVideoStatus,
  listAssets,
  listAvatars,
  listTalkingPhotos,
  listTemplates,
  listTranslationLanguages,
  listTranslations,
  listVideos,
  listVoices,
  translateVideo,
  uploadAsset
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    createAvatarVideo,
    getVideoStatus,
    listAvatars,
    listVoices,
    listVideos,
    deleteVideo,
    createVideoFromPrompt,
    generateFromTemplate,
    listTemplates,
    getTemplate,
    translateVideo,
    listTranslations,
    deleteTranslation,
    getTranslationStatus,
    generateSpeech,
    createStreamingToken,
    listAssets,
    uploadAsset,
    deleteAsset,
    getRemainingQuota,
    getCurrentUser,
    getVideoAgentStatus,
    listTranslationLanguages,
    getFileUrl,
    listTalkingPhotos
  ],
  triggers: []
});
