import { Slate } from 'slates';
import { spec } from './spec';
import {
  addNote,
  createAccount,
  createActivity,
  createContact,
  createLead,
  createTask,
  deleteRecord,
  findAccounts,
  findActivities,
  findContacts,
  findLeads,
  getAccount,
  getContact,
  getCurrentUser,
  getLead,
  getRecord,
  getTimeline,
  listActivityTypes,
  listCustomFields,
  listPipelinesStages,
  listProducts,
  listSources,
  listUsersTeams,
  searchCrm,
  updateAccount,
  updateContact,
  updateLead
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    createContact,
    getContact,
    updateContact,
    findContacts,
    createAccount,
    getAccount,
    updateAccount,
    findAccounts,
    createLead,
    getLead,
    updateLead,
    findLeads,
    createActivity,
    findActivities,
    createTask,
    addNote,
    searchCrm,
    listProducts,
    listPipelinesStages,
    listUsersTeams,
    listActivityTypes,
    listSources,
    getTimeline,
    getCurrentUser,
    getRecord,
    deleteRecord,
    listCustomFields
  ],
  triggers: []
});
