import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCategory,
  createLead,
  createMember,
  createPhotoAlbum,
  createPost,
  createReview,
  createWidget,
  deleteCategory,
  deleteLead,
  deleteMember,
  deletePhotoAlbum,
  deletePost,
  deleteReview,
  deleteWidget,
  getCategory,
  getLead,
  getMember,
  getMemberTransactions,
  getPhotoAlbum,
  getPost,
  getReview,
  getWidget,
  matchLead,
  searchCategories,
  searchMembers,
  searchPhotoAlbums,
  searchPosts,
  searchReviews,
  unsubscribeMember,
  updateCategory,
  updateLead,
  updateMember,
  updatePhotoAlbum,
  updatePost,
  updateReview,
  updateWidget,
  verifyMemberLogin
} from './tools';
import { formSubmission, memberChanges } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    getMember,
    createMember,
    updateMember,
    deleteMember,
    searchMembers,
    getMemberTransactions,
    verifyMemberLogin,
    getLead,
    createLead,
    updateLead,
    deleteLead,
    matchLead,
    getReview,
    createReview,
    updateReview,
    deleteReview,
    searchReviews,
    getPost,
    createPost,
    updatePost,
    deletePost,
    searchPosts,
    getPhotoAlbum,
    createPhotoAlbum,
    updatePhotoAlbum,
    deletePhotoAlbum,
    searchPhotoAlbums,
    getWidget,
    createWidget,
    updateWidget,
    deleteWidget,
    getCategory,
    createCategory,
    updateCategory,
    deleteCategory,
    searchCategories,
    unsubscribeMember
  ],
  triggers: [formSubmission, memberChanges]
});
