import { Slate } from 'slates';
import { spec } from './spec';
import {
  addNote,
  createAvoidanceZone,
  createContact,
  createOptimization,
  createOrder,
  createTeamMember,
  createTerritory,
  createVehicle,
  deleteAvoidanceZone,
  deleteContacts,
  deleteOrders,
  deleteRoute,
  deleteTeamMember,
  deleteTerritory,
  deleteVehicle,
  duplicateRoute,
  geocode,
  getActivities,
  getAvoidanceZones,
  getContacts,
  getNotes,
  getOptimization,
  getOrders,
  getRoutes,
  getTeamMembers,
  getTerritories,
  getTrackingHistory,
  getVehicles,
  setGpsPosition,
  updateContact,
  updateOrder,
  updateRoute,
  updateTeamMember,
  updateVehicle
} from './tools';
import { activityPolling, activityWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createOptimization,
    getOptimization,
    getRoutes,
    updateRoute,
    deleteRoute,
    duplicateRoute,
    createOrder,
    getOrders,
    updateOrder,
    deleteOrders,
    createContact,
    getContacts,
    updateContact,
    deleteContacts,
    geocode,
    getVehicles,
    createVehicle,
    updateVehicle,
    deleteVehicle,
    getTeamMembers,
    createTeamMember,
    updateTeamMember,
    deleteTeamMember,
    addNote,
    getNotes,
    getActivities,
    getAvoidanceZones,
    createAvoidanceZone,
    deleteAvoidanceZone,
    getTerritories,
    createTerritory,
    deleteTerritory,
    getTrackingHistory,
    setGpsPosition
  ],
  triggers: [activityWebhook, activityPolling]
});
