import { Slate } from 'slates';
import { spec } from './spec';
import {
  completeTask,
  createComment,
  createFilter,
  createLabel,
  createProject,
  createSection,
  createTask,
  deleteComment,
  deleteFilter,
  deleteLabel,
  deleteProject,
  deleteSection,
  deleteTask,
  getCollaborators,
  getComments,
  getFilters,
  getLabels,
  getProductivityStats,
  getProjects,
  getSections,
  getTasks,
  moveTask,
  quickAddTask,
  updateComment,
  updateFilter,
  updateLabel,
  updateProject,
  updateSection,
  updateTask
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    createTask,
    getTasks,
    updateTask,
    completeTask,
    deleteTask,
    moveTask,
    quickAddTask,
    createProject,
    updateProject,
    deleteProject,
    getProjects,
    getSections,
    createSection,
    updateSection,
    deleteSection,
    getLabels,
    createLabel,
    updateLabel,
    deleteLabel,
    getComments,
    createComment,
    updateComment,
    deleteComment,
    getFilters,
    createFilter,
    updateFilter,
    deleteFilter,
    getCollaborators,
    getProductivityStats
  ] as any[],
  triggers: []
});
