import { Slate } from 'slates';
import { spec } from './spec';
import {
  createNotificationTool,
  createPolicySetTool,
  createProjectTool,
  createRunTool,
  createRunTriggerTool,
  createTeamTool,
  createVariableSetTool,
  createVariableTool,
  createWorkspaceTool,
  deleteNotificationTool,
  deletePolicySetTool,
  deleteProjectTool,
  deleteRunTriggerTool,
  deleteTeamTool,
  deleteVariableSetTool,
  deleteVariableTool,
  deleteWorkspaceTool,
  getCurrentStateTool,
  getOrganizationTool,
  getRunTool,
  getWorkspaceTool,
  listNotificationsTool,
  listPolicySetsTool,
  listProjectsTool,
  listRunsTool,
  listRunTriggersTool,
  listStateVersionsTool,
  listTeamsTool,
  listVariableSetsTool,
  listVariablesTool,
  listWorkspacesTool,
  lockWorkspaceTool,
  manageRunTool,
  manageTeamMembersTool,
  setTeamWorkspaceAccessTool,
  updateProjectTool,
  updateVariableTool,
  updateWorkspaceTool
} from './tools';
import { runEventsTrigger, workspaceRunsTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listWorkspacesTool,
    getWorkspaceTool,
    createWorkspaceTool,
    updateWorkspaceTool,
    deleteWorkspaceTool,
    lockWorkspaceTool,
    listRunsTool,
    getRunTool,
    createRunTool,
    manageRunTool,
    listVariablesTool,
    createVariableTool,
    updateVariableTool,
    deleteVariableTool,
    listProjectsTool,
    createProjectTool,
    updateProjectTool,
    deleteProjectTool,
    listTeamsTool,
    createTeamTool,
    deleteTeamTool,
    manageTeamMembersTool,
    setTeamWorkspaceAccessTool,
    listStateVersionsTool,
    getCurrentStateTool,
    listPolicySetsTool,
    createPolicySetTool,
    deletePolicySetTool,
    listNotificationsTool,
    createNotificationTool,
    deleteNotificationTool,
    getOrganizationTool,
    listVariableSetsTool,
    createVariableSetTool,
    deleteVariableSetTool,
    listRunTriggersTool,
    createRunTriggerTool,
    deleteRunTriggerTool
  ],
  triggers: [runEventsTrigger, workspaceRunsTrigger]
});
