import { SlateTool } from 'slates';
import { z } from 'zod';
import { YouTubeAnalyticsClient } from '../lib/client';
import { youtubeAnalyticsActionScopes } from '../scopes';
import { spec } from '../spec';

export let downloadBulkReport = SlateTool.create(spec, {
  name: 'Download Bulk Report',
  key: 'download_bulk_report',
  description: `Get the download URL for a YouTube bulk report.
Retrieves the metadata and download URL for a specific report generated by a reporting job.
Use "List Bulk Reports" to find available reports and their download URLs.`,
  constraints: [
    'Reports are only available for 60 days after generation.',
    'Report content is returned as tab-separated CSV text.'
  ],
  tags: {
    readOnly: true
  }
})
  .scopes(youtubeAnalyticsActionScopes.downloadBulkReport)
  .input(
    z.object({
      jobId: z.string().describe('ID of the reporting job that generated the report.'),
      reportId: z.string().describe('ID of the report to download.'),
      onBehalfOfContentOwner: z
        .string()
        .optional()
        .describe('Content owner ID for content owner operations.')
    })
  )
  .output(
    z.object({
      reportId: z.string().describe('ID of the downloaded report.'),
      startTime: z.string().describe('Start of the reporting period.'),
      endTime: z.string().describe('End of the reporting period.'),
      downloadUrl: z.string().describe('URL to download the report content.')
    })
  )
  .handleInvocation(async ctx => {
    let client = new YouTubeAnalyticsClient({ token: ctx.auth.token });

    let report = await client.getBulkReport(
      ctx.input.jobId,
      ctx.input.reportId,
      ctx.input.onBehalfOfContentOwner
    );

    return {
      output: {
        reportId: report.reportId,
        startTime: report.startTime,
        endTime: report.endTime,
        downloadUrl: report.downloadUrl
      },
      message: `Downloaded bulk report **${report.reportId}** covering ${report.startTime} to ${report.endTime}.`
    };
  })
  .build();
