import { SlateTool } from 'slates';
import { z } from 'zod';
import { YouTubeAnalyticsClient } from '../lib/client';
import { youtubeAnalyticsActionScopes } from '../scopes';
import { spec } from '../spec';

export let manageReportingJobs = SlateTool.create(spec, {
  name: 'Manage Reporting Jobs',
  key: 'manage_reporting_jobs',
  description: `Create, list, get, or delete YouTube Reporting API bulk report jobs.
Each job tells YouTube to generate daily bulk reports for a specific report type.
Use **list** to view existing jobs, **get** to fetch a specific job, **create** to schedule a new bulk report, or **delete** to stop generating reports.`,
  instructions: [
    'For "create", reportTypeId and name are required. Use the "List Report Types" tool to find available report type IDs.',
    'For "get" and "delete", jobId is required.',
    'Reports generated by a job become available within 48 hours of job creation.'
  ],
  constraints: [
    'System-managed jobs cannot be modified or deleted.',
    'Reports are only available for 60 days after generation.'
  ],
  tags: {
    destructive: false
  }
})
  .scopes(youtubeAnalyticsActionScopes.manageReportingJobs)
  .input(
    z.object({
      action: z
        .enum(['list', 'get', 'create', 'delete'])
        .describe('Action to perform on reporting jobs.'),
      jobId: z.string().optional().describe('Job ID (required for get and delete).'),
      reportTypeId: z
        .string()
        .optional()
        .describe('Report type ID for the job to generate (required for create).'),
      name: z.string().optional().describe('Name for the new job (required for create).'),
      includeSystemManaged: z
        .boolean()
        .optional()
        .describe('Include system-managed jobs in the list results.'),
      onBehalfOfContentOwner: z
        .string()
        .optional()
        .describe('Content owner ID for content owner operations.'),
      pageToken: z.string().optional().describe('Pagination token for list operations.')
    })
  )
  .output(
    z.object({
      jobs: z
        .array(
          z.object({
            jobId: z.string().describe('Job ID.'),
            reportTypeId: z.string().describe('Report type ID.'),
            name: z.string().describe('Job name.'),
            createTime: z.string().describe('When the job was created.'),
            expireTime: z.string().optional().describe('When the job expires.'),
            systemManaged: z
              .boolean()
              .optional()
              .describe('Whether the job is system-managed.')
          })
        )
        .optional()
        .describe('List of reporting jobs (for list action).'),
      job: z
        .object({
          jobId: z.string().describe('Job ID.'),
          reportTypeId: z.string().describe('Report type ID.'),
          name: z.string().describe('Job name.'),
          createTime: z.string().describe('When the job was created.'),
          expireTime: z.string().optional().describe('When the job expires.'),
          systemManaged: z.boolean().optional().describe('Whether the job is system-managed.')
        })
        .optional()
        .describe('Single reporting job (for get/create actions).'),
      deleted: z
        .boolean()
        .optional()
        .describe('Whether the job was deleted (for delete action).'),
      nextPageToken: z
        .string()
        .optional()
        .describe('Token for fetching the next page of results.')
    })
  )
  .handleInvocation(async ctx => {
    let client = new YouTubeAnalyticsClient({ token: ctx.auth.token });
    let {
      action,
      jobId,
      reportTypeId,
      name,
      includeSystemManaged,
      onBehalfOfContentOwner,
      pageToken
    } = ctx.input;

    if (action === 'list') {
      let result = await client.listReportingJobs({
        includeSystemManaged,
        onBehalfOfContentOwner,
        pageToken
      });

      return {
        output: { jobs: result.jobs, nextPageToken: result.nextPageToken },
        message: `Found **${result.jobs.length}** reporting job(s).`
      };
    }

    if (action === 'get') {
      if (!jobId) throw new Error('Job ID is required for getting a job.');

      let job = await client.getReportingJob(jobId, onBehalfOfContentOwner);

      return {
        output: { job },
        message: `Retrieved reporting job **"${job.name}"** (${job.jobId}).`
      };
    }

    if (action === 'create') {
      if (!reportTypeId) throw new Error('Report type ID is required for creating a job.');
      if (!name) throw new Error('Name is required for creating a job.');

      let job = await client.createReportingJob(reportTypeId, name, onBehalfOfContentOwner);

      return {
        output: { job },
        message: `Created reporting job **"${job.name}"** (${job.jobId}) for report type **${job.reportTypeId}**. Reports will be available within 48 hours.`
      };
    }

    if (action === 'delete') {
      if (!jobId) throw new Error('Job ID is required for deleting a job.');

      await client.deleteReportingJob(jobId, onBehalfOfContentOwner);

      return {
        output: { deleted: true },
        message: `Deleted reporting job **${jobId}**.`
      };
    }

    throw new Error(`Unknown action: ${action}`);
  })
  .build();
