import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCandidateNoteTool,
  advanceApplicationTool,
  createCandidateTool,
  createJobTool,
  downloadApplicationAttachmentTool,
  getApplicationTool,
  getCandidateTool,
  getCurrentContextTool,
  getFileUrl,
  getJobTool,
  getUserTool,
  listApplicationAttachmentsTool,
  listApplicationsTool,
  listCandidatesTool,
  listDepartmentsTool,
  listJobsTool,
  listOffersTool,
  listOfficesTool,
  listRejectionReasonsTool,
  listScheduledInterviewsTool,
  listUsersTool,
  manageCandidateTagsTool,
  rejectApplicationTool,
  updateCandidateTool
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getCurrentContextTool,
    listRejectionReasonsTool,
    listApplicationAttachmentsTool,
    downloadApplicationAttachmentTool,
    getFileUrl,
    listCandidatesTool,
    getCandidateTool,
    createCandidateTool,
    updateCandidateTool,
    listApplicationsTool,
    getApplicationTool,
    advanceApplicationTool,
    rejectApplicationTool,
    listJobsTool,
    getJobTool,
    createJobTool,
    listOffersTool,
    listUsersTool,
    getUserTool,
    listDepartmentsTool,
    listOfficesTool,
    listScheduledInterviewsTool,
    addCandidateNoteTool,
    manageCandidateTagsTool
  ],
  triggers: []
});
