import { Slate } from 'slates';
import { spec } from './spec';
import {
  createInvoice,
  createOrder,
  createVoucher,
  deleteOrder,
  deleteProject,
  deleteVoucher,
  getBalanceSheet,
  getDocumentContent,
  getInvoicePdf,
  getSupplierInvoicePdf,
  getVoucherPdf,
  invoiceOrder,
  listContacts,
  listCustomers,
  listDocumentArchive,
  listEmployees,
  listInvoices,
  listOrders,
  listPostingsByDate,
  listProducts,
  listProjects,
  listReferenceData,
  listSupplierInvoices,
  listSupplierInvoicesForApproval,
  listSuppliers,
  listVouchers,
  manageWebhookSubscription,
  registerInvoicePayment,
  sendInvoice,
  upsertContact,
  upsertCustomer,
  upsertProduct,
  upsertProject,
  upsertSupplier,
  whoAmI
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    whoAmI,
    listCustomers,
    upsertCustomer,
    listSuppliers,
    upsertSupplier,
    listContacts,
    upsertContact,
    listEmployees,
    listReferenceData,
    listProducts,
    upsertProduct,
    listInvoices,
    createInvoice,
    sendInvoice,
    registerInvoicePayment,
    getInvoicePdf,
    listOrders,
    createOrder,
    deleteOrder,
    invoiceOrder,
    listSupplierInvoices,
    listSupplierInvoicesForApproval,
    getSupplierInvoicePdf,
    listVouchers,
    createVoucher,
    getVoucherPdf,
    deleteVoucher,
    listPostingsByDate,
    getBalanceSheet,
    listProjects,
    upsertProject,
    deleteProject,
    listDocumentArchive,
    getDocumentContent,
    manageWebhookSubscription
  ],
  triggers: []
});
