import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCommentTool,
  addIssueRelationTool,
  addSubtaskTool,
  createEpicTool,
  createIssueTool,
  createSprintTool,
  createTagTool,
  createVersionTool,
  deleteCommentTool,
  deleteEpicTool,
  deleteIssueTool,
  deleteSprintTool,
  deleteSubtaskTool,
  deleteTagTool,
  deleteVersionTool,
  getIssueTool,
  listCommentsTool,
  listEpicsTool,
  listIssueTypesTool,
  listOrgMembersTool,
  listProjectMembersTool,
  listProjectsTool,
  listSprintsTool,
  listTagsTool,
  listVersionsTool,
  manageVersionLifecycleTool,
  queryIssuesTool,
  removeIssueRelationTool,
  updateCommentTool,
  updateEpicTool,
  updateIssueTool,
  updateSprintTool,
  updateSubtaskTool,
  updateVersionTool
} from './tools';
import {
  attachmentEventsTrigger,
  commentEventsTrigger,
  issueEventsTrigger,
  sprintEventsTrigger,
  subtaskEventsTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listProjectsTool,
    getIssueTool,
    createIssueTool,
    updateIssueTool,
    deleteIssueTool,
    queryIssuesTool,
    listIssueTypesTool,
    addSubtaskTool,
    updateSubtaskTool,
    deleteSubtaskTool,
    addIssueRelationTool,
    removeIssueRelationTool,
    listSprintsTool,
    createSprintTool,
    updateSprintTool,
    deleteSprintTool,
    listEpicsTool,
    createEpicTool,
    updateEpicTool,
    deleteEpicTool,
    listVersionsTool,
    createVersionTool,
    updateVersionTool,
    deleteVersionTool,
    manageVersionLifecycleTool,
    listCommentsTool,
    addCommentTool,
    updateCommentTool,
    deleteCommentTool,
    listTagsTool,
    createTagTool,
    deleteTagTool,
    listOrgMembersTool,
    listProjectMembersTool
  ],
  triggers: [
    issueEventsTrigger,
    commentEventsTrigger,
    sprintEventsTrigger,
    subtaskEventsTrigger,
    attachmentEventsTrigger
  ]
});
