import { Slate } from 'slates';
import { spec } from './spec';
import {
  cancelPickup,
  cancelShipment,
  createLabel,
  createManifest,
  createShipment,
  createWarehouse,
  deleteWarehouse,
  downloadShippingDocument,
  estimateRates,
  findServicePoints,
  getRates,
  getShippingResource,
  listCarriers,
  listLabels,
  listShipments,
  listShippingResources,
  listWarehouses,
  recognizeAddress,
  schedulePickup,
  trackPackage,
  updateShipment,
  updateWarehouse,
  validateAddress,
  voidLabel
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    validateAddress,
    recognizeAddress,
    getRates,
    estimateRates,
    createLabel,
    voidLabel,
    listLabels,
    trackPackage,
    createShipment,
    updateShipment,
    cancelShipment,
    listShipments,
    listCarriers,
    listWarehouses,
    createWarehouse,
    updateWarehouse,
    deleteWarehouse,
    findServicePoints,
    schedulePickup,
    cancelPickup,
    createManifest,
    getShippingResource,
    listShippingResources,
    downloadShippingDocument
  ],
  triggers: []
});
