import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAssignment,
  createClient,
  createExpense,
  createInvoice,
  createProject,
  createSection,
  createTask,
  deleteAssignment,
  deleteClient,
  deleteExpense,
  deleteInvoice,
  deleteProject,
  deleteSection,
  deleteTask,
  deleteTimeRecord,
  getProject,
  getReport,
  getRunningTimers,
  getTask,
  listAssignments,
  listClients,
  listExpenses,
  listInvoices,
  listProjects,
  listSections,
  listTasks,
  listTimeRecords,
  listUsers,
  logTime,
  startTimer,
  stopTimer,
  updateAssignment,
  updateClient,
  updateExpense,
  updateInvoice,
  updateProject,
  updateSection,
  updateTask,
  updateTimeRecord
} from './tools';
import {
  clientEvents,
  estimateEvents,
  projectEvents,
  sectionEvents,
  taskEvents,
  timeEvents,
  timerEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listUsers,
    listClients,
    createClient,
    updateClient,
    deleteClient,
    listProjects,
    getProject,
    createProject,
    updateProject,
    deleteProject,
    listTasks,
    getTask,
    createTask,
    updateTask,
    deleteTask,
    listTimeRecords,
    logTime,
    updateTimeRecord,
    deleteTimeRecord,
    startTimer,
    stopTimer,
    getRunningTimers,
    listExpenses,
    createExpense,
    updateExpense,
    deleteExpense,
    listInvoices,
    createInvoice,
    updateInvoice,
    deleteInvoice,
    listAssignments,
    createAssignment,
    updateAssignment,
    deleteAssignment,
    listSections,
    createSection,
    updateSection,
    deleteSection,
    getReport
  ] as any,
  triggers: [
    projectEvents,
    taskEvents,
    timeEvents,
    timerEvents,
    sectionEvents,
    clientEvents,
    estimateEvents
  ] as any
});
