import { Slate } from 'slates';
import { spec } from './spec';
import {
  createEndpoint,
  createNetworkVolume,
  createPod,
  createTemplate,
  deleteEndpoint,
  getBilling,
  getCurrentUser,
  getEndpoint,
  getJobStatus,
  getJobStream,
  getNetworkVolume,
  getPod,
  getTemplate,
  listComputeTypes,
  listContainerRegistryAuths,
  listDataCenters,
  listEndpoints,
  listNetworkVolumes,
  listPods,
  listTemplates,
  manageContainerRegistryAuth,
  manageJob,
  manageNetworkVolume,
  managePod,
  manageTemplate,
  runJob,
  updateEndpoint,
  updatePod
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    listPods,
    getPod,
    createPod,
    updatePod,
    managePod,
    listEndpoints,
    getEndpoint,
    createEndpoint,
    updateEndpoint,
    deleteEndpoint,
    runJob,
    getJobStatus,
    manageJob,
    listNetworkVolumes,
    createNetworkVolume,
    manageNetworkVolume,
    listTemplates,
    createTemplate,
    manageTemplate,
    getBilling,
    getCurrentUser,
    getJobStream,
    getTemplate,
    getNetworkVolume,
    listComputeTypes,
    listDataCenters,
    listContainerRegistryAuths,
    manageContainerRegistryAuth
  ],
  triggers: []
});
