import { Slate } from 'slates';
import { spec } from './spec';
import {
  batchScrapeTool,
  cancelAgentTool,
  cancelBatchScrapeTool,
  cancelCrawlTool,
  crawlWebsiteTool,
  createBrowserSessionTool,
  createMonitorTool,
  deleteBrowserSessionTool,
  deleteMonitorTool,
  executeBrowserCodeTool,
  extractDataTool,
  getActiveCrawlsTool,
  getAgentStatusTool,
  getBatchScrapeErrorsTool,
  getBatchScrapeStatusTool,
  getCrawlErrorsTool,
  getCrawlStatusTool,
  getCreditUsageTool,
  getExtractStatusTool,
  getHistoricalCreditUsageTool,
  getHistoricalTokenUsageTool,
  getMonitorCheckTool,
  getMonitorTool,
  getQueueStatusTool,
  getScrapeStatusTool,
  getTokenUsageTool,
  interactWithPageTool,
  listActivityTool,
  listBrowserSessionsTool,
  listMonitorChecksTool,
  listMonitorsTool,
  mapWebsiteTool,
  parseFileTool,
  previewCrawlParamsTool,
  runAgentTool,
  runMonitorTool,
  scrapePageTool,
  searchWebTool,
  stopPageInteractionTool,
  updateMonitorTool
} from './tools';
import {
  agentEventsTrigger,
  batchScrapeEventsTrigger,
  crawlEventsTrigger,
  extractEventsTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    scrapePageTool.build(),
    getScrapeStatusTool.build(),
    interactWithPageTool.build(),
    stopPageInteractionTool.build(),
    parseFileTool.build(),
    crawlWebsiteTool.build(),
    getCrawlStatusTool.build(),
    cancelCrawlTool.build(),
    getCrawlErrorsTool.build(),
    previewCrawlParamsTool.build(),
    getActiveCrawlsTool.build(),
    searchWebTool.build(),
    mapWebsiteTool.build(),
    extractDataTool.build(),
    getExtractStatusTool.build(),
    batchScrapeTool.build(),
    getBatchScrapeStatusTool.build(),
    cancelBatchScrapeTool.build(),
    getBatchScrapeErrorsTool.build(),
    runAgentTool.build(),
    getAgentStatusTool.build(),
    cancelAgentTool.build(),
    createBrowserSessionTool.build(),
    listBrowserSessionsTool.build(),
    executeBrowserCodeTool.build(),
    deleteBrowserSessionTool.build(),
    createMonitorTool.build(),
    listMonitorsTool.build(),
    getMonitorTool.build(),
    updateMonitorTool.build(),
    deleteMonitorTool.build(),
    runMonitorTool.build(),
    listMonitorChecksTool.build(),
    getMonitorCheckTool.build(),
    getCreditUsageTool.build(),
    getHistoricalCreditUsageTool.build(),
    getTokenUsageTool.build(),
    getHistoricalTokenUsageTool.build(),
    getQueueStatusTool.build(),
    listActivityTool.build()
  ],
  triggers: [
    crawlEventsTrigger.build(),
    batchScrapeEventsTrigger.build(),
    extractEventsTrigger.build(),
    agentEventsTrigger.build()
  ]
});
