import { Slate } from 'slates';
import { spec } from './spec';
import {
  addRecipient,
  createContact,
  createDocument,
  createDocumentFolder,
  createDocumentLink,
  deleteContact,
  deleteDocument,
  downloadDocument,
  getDocument,
  getDocumentStatus,
  getTemplate,
  linkCrmObject,
  listContacts,
  listContentLibrary,
  listDocumentFolders,
  listDocuments,
  listForms,
  listMembers,
  listTemplates,
  manageDocumentStatus,
  removeRecipient,
  renameDocumentFolder,
  sendDocument,
  sendReminder,
  updateContact,
  updateDocument,
  updateRecipient
} from './tools';
import { documentEvents, templateEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createDocument,
    updateDocument,
    listDocuments,
    getDocument,
    getDocumentStatus,
    sendDocument,
    manageDocumentStatus,
    deleteDocument,
    createDocumentLink,
    downloadDocument,
    listTemplates,
    getTemplate,
    createContact,
    listContacts,
    updateContact,
    deleteContact,
    addRecipient,
    updateRecipient,
    removeRecipient,
    linkCrmObject,
    sendReminder,
    listMembers,
    listForms,
    listContentLibrary,
    listDocumentFolders,
    createDocumentFolder,
    renameDocumentFolder
  ],
  triggers: [documentEvents, templateEvents]
});
