import { Slate } from 'slates';
import { slackChatAdapter } from './chat';
import { spec } from './spec';
import {
  createCanvas,
  createSlackList,
  createSlackListItem,
  deleteCanvas,
  deleteSlackListItems,
  downloadSlackList,
  editCanvas,
  getConversationHistory,
  getConversationInfo,
  getMessage,
  getMessagePermalink,
  getTeamInfo,
  getUserInfo,
  listConversations,
  listSlackListItems,
  lookupCanvasSections,
  manageBookmarks,
  manageCanvasAccess,
  manageChannel,
  manageChannelMembers,
  manageDnd,
  manageFiles,
  managePins,
  managePresence,
  manageReactions,
  manageReminders,
  manageScheduledMessages,
  manageSlackListAccess,
  manageUserGroups,
  manageUserStatus,
  markConversationRead,
  openConversation,
  readFile,
  readThread,
  scheduleMessage,
  searchChannels,
  searchEmojis,
  searchFiles,
  searchMessages,
  searchPublic,
  searchPublicAndPrivate,
  searchUsers,
  sendMessage,
  updateMessage,
  updateSlackListItems,
  updateUserProfile,
  uploadFile,
  whoAmI
} from './tools';
import {
  appMentioned,
  channelArchived,
  channelCreated,
  channelRenamed,
  channelUnarchived,
  memberJoinedChannel,
  memberLeftChannel,
  messageDeleted,
  messageEdited,
  newFile,
  newMessage,
  newReaction,
  reactionRemoved,
  slackEventsTriggerGroup,
  teamJoin,
  userChange,
  userGroupCreated,
  userGroupMembersChanged,
  userGroupUpdated
} from './triggers';

export let provider = Slate.create({
  spec,
  triggerGroups: [slackEventsTriggerGroup],
  tools: [
    sendMessage,
    updateMessage,
    scheduleMessage,
    manageScheduledMessages,
    getConversationHistory,
    getConversationInfo,
    openConversation,
    listConversations,
    manageChannel,
    manageChannelMembers,
    getUserInfo,
    manageUserStatus,
    manageReactions,
    managePins,
    manageFiles,
    searchMessages,
    searchFiles,
    manageReminders,
    manageUserGroups,
    manageBookmarks,
    getTeamInfo,
    whoAmI,
    readThread,
    getMessagePermalink,
    readFile,
    uploadFile,
    searchPublic,
    searchPublicAndPrivate,
    searchChannels,
    searchUsers,
    createCanvas,
    editCanvas,
    lookupCanvasSections,
    searchEmojis,
    updateUserProfile,
    createSlackList,
    listSlackListItems,
    createSlackListItem,
    updateSlackListItems,
    deleteSlackListItems,
    manageCanvasAccess,
    deleteCanvas,
    manageSlackListAccess,
    downloadSlackList,
    getMessage,
    markConversationRead,
    manageDnd,
    managePresence
  ],

  adapters: [slackChatAdapter],

  triggers: [
    newMessage,
    newMessageWebhook,
    channelActivity,
    newReaction,
    newFile,
    userChange
    messageEdited,
    messageDeleted,
    appMentioned,
    newReaction,
    reactionRemoved,
    newFile,
    memberJoinedChannel,
    memberLeftChannel,
    teamJoin,
    channelCreated,
    channelRenamed,
    channelArchived,
    channelUnarchived,
    userChange,
    userGroupCreated,
    userGroupUpdated,
    userGroupMembersChanged
  ]
});
