import { Slate } from 'slates';
import { spec } from './spec';
import {
  createComment,
  createCompany,
  createConversation,
  createCustomField,
  createPhase,
  createProject,
  createSpace,
  createTask,
  createTimeEntry,
  deleteCustomField,
  deletePhase,
  deleteProject,
  deleteSpace,
  deleteTask,
  deleteTimeEntry,
  getProject,
  getTask,
  listComments,
  listCompanies,
  listConversations,
  listCustomFields,
  listPhases,
  listProjects,
  listResourceAllocations,
  listSpaces,
  listTasks,
  listTemplates,
  listTimeEntries,
  listUsers,
  searchInvoices,
  updateCompany,
  updatePhase,
  updateProject,
  updateSpace,
  updateTask,
  updateTimeEntry
} from './tools';
import { taskEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createProject,
    updateProject,
    getProject,
    listProjects,
    deleteProject,
    createTask,
    updateTask,
    getTask,
    listTasks,
    deleteTask,
    createPhase,
    updatePhase,
    listPhases,
    deletePhase,
    createCompany,
    updateCompany,
    listCompanies,
    listUsers,
    createTimeEntry,
    updateTimeEntry,
    deleteTimeEntry,
    listTimeEntries,
    createSpace,
    listSpaces,
    updateSpace,
    deleteSpace,
    createConversation,
    listConversations,
    createComment,
    listComments,
    listTemplates,
    listCustomFields,
    createCustomField,
    deleteCustomField,
    listResourceAllocations,
    searchInvoices
  ],
  triggers: [taskEvents]
});
