export type EmojiFormats = {
  slack: string | string[];
  unicode: string | string[];
};

export let DEFAULT_EMOJI_MAP: Record<string, EmojiFormats> = {
  thumbs_up: { slack: ['+1', 'thumbsup'], unicode: '👍' },
  thumbs_down: { slack: ['-1', 'thumbsdown'], unicode: '👎' },
  clap: { slack: 'clap', unicode: '👏' },
  wave: { slack: 'wave', unicode: '👋' },
  pray: { slack: 'pray', unicode: '🙏' },
  muscle: { slack: 'muscle', unicode: '💪' },
  ok_hand: { slack: 'ok_hand', unicode: '👌' },
  point_up: { slack: 'point_up', unicode: '👆' },
  point_down: { slack: 'point_down', unicode: '👇' },
  point_left: { slack: 'point_left', unicode: '👈' },
  point_right: { slack: 'point_right', unicode: '👉' },
  raised_hands: { slack: 'raised_hands', unicode: '🙌' },
  shrug: { slack: 'shrug', unicode: '🤷' },
  facepalm: { slack: 'facepalm', unicode: '🤦' },

  heart: { slack: 'heart', unicode: ['❤️', '❤'] },
  smile: { slack: ['smile', 'slightly_smiling_face'], unicode: '😊' },
  laugh: { slack: ['laughing', 'satisfied', 'joy'], unicode: ['😂', '😆'] },
  thinking: { slack: 'thinking_face', unicode: '🤔' },
  sad: { slack: ['cry', 'sad', 'white_frowning_face'], unicode: '😢' },
  cry: { slack: 'sob', unicode: '😭' },
  angry: { slack: 'angry', unicode: '😠' },
  love_eyes: { slack: 'heart_eyes', unicode: '😍' },
  cool: { slack: 'sunglasses', unicode: '😎' },
  wink: { slack: 'wink', unicode: '😉' },
  surprised: { slack: 'open_mouth', unicode: '😮' },
  worried: { slack: 'worried', unicode: '😟' },
  confused: { slack: 'confused', unicode: '😕' },
  neutral: { slack: 'neutral_face', unicode: '😐' },
  sleeping: { slack: 'sleeping', unicode: '😴' },
  sick: { slack: 'nauseated_face', unicode: '🤢' },
  mind_blown: { slack: 'exploding_head', unicode: '🤯' },
  relieved: { slack: 'relieved', unicode: '😌' },
  grimace: { slack: 'grimacing', unicode: '😬' },
  rolling_eyes: { slack: 'rolling_eyes', unicode: '🙄' },
  hug: { slack: 'hugging_face', unicode: '🤗' },
  zany: { slack: 'zany_face', unicode: '🤪' },

  check: {
    slack: ['white_check_mark', 'heavy_check_mark'],
    unicode: ['✅', '✔️']
  },
  x: { slack: ['x', 'heavy_multiplication_x'], unicode: ['❌', '✖️'] },
  question: { slack: 'question', unicode: '❓' },
  exclamation: { slack: 'exclamation', unicode: '❗' },
  warning: { slack: 'warning', unicode: '⚠️' },
  stop: { slack: 'octagonal_sign', unicode: '🛑' },
  info: { slack: 'information_source', unicode: 'ℹ️' },
  '100': { slack: '100', unicode: '💯' },
  fire: { slack: 'fire', unicode: '🔥' },
  star: { slack: 'star', unicode: '⭐' },
  sparkles: { slack: 'sparkles', unicode: '✨' },
  lightning: { slack: 'zap', unicode: '⚡' },
  boom: { slack: 'boom', unicode: '💥' },
  eyes: { slack: 'eyes', unicode: '👀' },

  green_circle: { slack: 'large_green_circle', unicode: '🟢' },
  yellow_circle: { slack: 'large_yellow_circle', unicode: '🟡' },
  red_circle: { slack: 'red_circle', unicode: '🔴' },
  blue_circle: { slack: 'large_blue_circle', unicode: '🔵' },
  white_circle: { slack: 'white_circle', unicode: '⚪' },
  black_circle: { slack: 'black_circle', unicode: '⚫' },

  rocket: { slack: 'rocket', unicode: '🚀' },
  party: { slack: ['tada', 'partying_face'], unicode: ['🎉', '🥳'] },
  confetti: { slack: 'confetti_ball', unicode: '🎊' },
  balloon: { slack: 'balloon', unicode: '🎈' },
  gift: { slack: 'gift', unicode: '🎁' },
  trophy: { slack: 'trophy', unicode: '🏆' },
  medal: { slack: 'first_place_medal', unicode: '🥇' },
  lightbulb: { slack: 'bulb', unicode: '💡' },
  gear: { slack: 'gear', unicode: '⚙️' },
  wrench: { slack: 'wrench', unicode: '🔧' },
  hammer: { slack: 'hammer', unicode: '🔨' },
  bug: { slack: 'bug', unicode: '🐛' },
  link: { slack: 'link', unicode: '🔗' },
  lock: { slack: 'lock', unicode: '🔒' },
  unlock: { slack: 'unlock', unicode: '🔓' },
  key: { slack: 'key', unicode: '🔑' },
  pin: { slack: 'pushpin', unicode: '📌' },
  memo: { slack: 'memo', unicode: '📝' },
  clipboard: { slack: 'clipboard', unicode: '📋' },
  calendar: { slack: 'calendar', unicode: '📅' },
  clock: { slack: 'clock1', unicode: '🕐' },
  hourglass: { slack: 'hourglass', unicode: '⏳' },
  bell: { slack: 'bell', unicode: '🔔' },
  megaphone: { slack: 'mega', unicode: '📢' },
  speech_bubble: { slack: 'speech_balloon', unicode: '💬' },
  email: { slack: 'email', unicode: '📧' },
  inbox: { slack: 'inbox_tray', unicode: '📥' },
  outbox: { slack: 'outbox_tray', unicode: '📤' },
  package: { slack: 'package', unicode: '📦' },
  folder: { slack: 'file_folder', unicode: '📁' },
  file: { slack: 'page_facing_up', unicode: '📄' },
  chart_up: { slack: 'chart_with_upwards_trend', unicode: '📈' },
  chart_down: { slack: 'chart_with_downwards_trend', unicode: '📉' },
  coffee: { slack: 'coffee', unicode: '☕' },
  pizza: { slack: 'pizza', unicode: '🍕' },
  beer: { slack: 'beer', unicode: '🍺' },

  arrow_up: { slack: 'arrow_up', unicode: '⬆️' },
  arrow_down: { slack: 'arrow_down', unicode: '⬇️' },
  arrow_left: { slack: 'arrow_left', unicode: '⬅️' },
  arrow_right: { slack: 'arrow_right', unicode: '➡️' },
  refresh: { slack: 'arrows_counterclockwise', unicode: '🔄' },

  sun: { slack: 'sunny', unicode: '☀️' },
  cloud: { slack: 'cloud', unicode: '☁️' },
  rain: { slack: 'rain_cloud', unicode: '🌧️' },
  snow: { slack: 'snowflake', unicode: '❄️' },
  rainbow: { slack: 'rainbow', unicode: '🌈' }
};
