import { Slate } from 'slates';
import { spec } from './spec';
import {
  addContactToList,
  createContact,
  createNote,
  deleteContact,
  deleteConversation,
  deleteFile,
  deleteNote,
  deleteTemplate,
  getChannel,
  getContact,
  getConversation,
  getCurrentUser,
  getFile,
  getInbox,
  getLabel,
  getMessageAnalytics,
  getTemplate,
  getUser,
  listChannels,
  listContactLists,
  listContacts,
  listConversations,
  listFiles,
  listInboxes,
  listLabels,
  listNotes,
  listTemplates,
  listUsers,
  removeContactFromList,
  searchContacts,
  sendMessage,
  updateContact,
  updateConversation,
  updateNote
} from './tools';
import { contactEvents, conversationEvents, messageEvents, noteEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    sendMessage,
    createContact,
    getContact,
    updateContact,
    deleteContact,
    listContacts,
    searchContacts,
    listConversations,
    getConversation,
    updateConversation,
    deleteConversation,
    createNote,
    listNotes,
    updateNote,
    deleteNote,
    listChannels,
    getChannel,
    listTemplates,
    getTemplate,
    deleteTemplate,
    listLabels,
    getLabel,
    listFiles,
    getFile,
    deleteFile,
    listUsers,
    getUser,
    getCurrentUser,
    getMessageAnalytics,
    listInboxes,
    getInbox,
    listContactLists,
    addContactToList,
    removeContactFromList
  ],
  triggers: [messageEvents, contactEvents, conversationEvents, noteEvents]
});
