import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCategoryTool,
  createCommentTool,
  createPageTool,
  createPostTool,
  createTagTool,
  deleteCategoryTool,
  deleteCommentTool,
  deleteMediaTool,
  deletePageTool,
  deletePostTool,
  deleteTagTool,
  getCategoryTool,
  getCurrentUserTool,
  getMediaTool,
  getPostTool,
  getSiteInfoTool,
  getSiteSettingsTool,
  getSiteStatsTool,
  getTagTool,
  listCategoriesTool,
  listCommentsTool,
  listMediaTool,
  listPagesTool,
  listPostsTool,
  listTagsTool,
  listUsersTool,
  moderateCommentTool,
  searchContentTool,
  updateCategoryTool,
  updateMediaTool,
  updatePageTool,
  updatePostTool,
  updateSiteSettingsTool,
  updateTagTool,
  uploadMediaTool
} from './tools';
import {
  inboundWebhook,
  newCommentTrigger,
  pageChangesTrigger,
  postChangesTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listPostsTool,
    getPostTool,
    createPostTool,
    updatePostTool,
    deletePostTool,
    listPagesTool,
    createPageTool,
    updatePageTool,
    deletePageTool,
    listCommentsTool,
    createCommentTool,
    moderateCommentTool,
    deleteCommentTool,
    uploadMediaTool,
    listMediaTool,
    getMediaTool,
    updateMediaTool,
    deleteMediaTool,
    listCategoriesTool,
    createCategoryTool,
    getCategoryTool,
    updateCategoryTool,
    deleteCategoryTool,
    listTagsTool,
    createTagTool,
    getTagTool,
    updateTagTool,
    deleteTagTool,
    listUsersTool,
    getCurrentUserTool,
    getSiteInfoTool,
    getSiteSettingsTool,
    updateSiteSettingsTool,
    getSiteStatsTool,
    searchContentTool
  ],
  triggers: [inboundWebhook, postChangesTrigger, newCommentTrigger, pageChangesTrigger]
});
