import { Slate } from 'slates';
import { spec } from './spec';
import {
  createDashboard,
  deleteDashboard,
  downloadDatasourceInstanceData,
  getDashboard,
  getDatasource,
  getDatasourceInstanceData,
  getKlip,
  getProfile,
  listClients,
  listDashboards,
  listDatasourceInstances,
  listDatasources,
  listGroups,
  listKlips,
  listPublishedLinks,
  listRoles,
  listUsers,
  manageClient,
  manageDatasource,
  manageGroup,
  manageKlip,
  managePublishedLink,
  manageRole,
  manageUser,
  refreshDatasource,
  updateDashboard
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    listDashboards,
    getDashboard,
    createDashboard,
    updateDashboard,
    deleteDashboard,
    listKlips,
    getKlip,
    manageKlip,
    listDatasources,
    getDatasource,
    manageDatasource,
    refreshDatasource,
    getDatasourceInstanceData,
    downloadDatasourceInstanceData,
    listDatasourceInstances,
    listGroups,
    listUsers,
    manageUser,
    listRoles,
    manageRole,
    listClients,
    manageClient,
    manageGroup,
    listPublishedLinks,
    managePublishedLink,
    getProfile
  ],
  triggers: []
});
