import { Slate } from 'slates';
import { spec } from './spec';
import {
  addTicketReply,
  createArticle,
  createCompany,
  createContact,
  createTicket,
  createTimeEntry,
  deleteCompany,
  deleteContact,
  deleteTicket,
  deleteTimeEntry,
  getAccount,
  getArticle,
  getCompany,
  getContact,
  getCurrentAgent,
  getHelpdeskSettings,
  getTicket,
  listAgents,
  listBusinessHours,
  listCannedResponseFolders,
  listCannedResponses,
  listCompanies,
  listContacts,
  listConversations,
  listFields,
  listGroups,
  listKnowledgeBase,
  listProducts,
  listSatisfactionRatings,
  listSlaPolicies,
  listTickets,
  listTimeEntries,
  searchCompanies,
  searchContacts,
  searchTickets,
  updateCompany,
  updateContact,
  updateTicket,
  updateTimeEntry
} from './tools';
import { contactEvents, ticketEvents, ticketEventsWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createTicket,
    getTicket,
    updateTicket,
    listTickets,
    searchTickets,
    deleteTicket,
    addTicketReply,
    listConversations,
    createContact,
    getContact,
    updateContact,
    deleteContact,
    listContacts,
    searchContacts,
    createCompany,
    getCompany,
    updateCompany,
    deleteCompany,
    listCompanies,
    searchCompanies,
    listAgents,
    getCurrentAgent,
    listGroups,
    getAccount,
    getHelpdeskSettings,
    listFields,
    listProducts,
    listBusinessHours,
    listSlaPolicies,
    listSatisfactionRatings,
    listCannedResponseFolders,
    listCannedResponses,
    listKnowledgeBase,
    getArticle,
    createArticle,
    listTimeEntries,
    createTimeEntry,
    updateTimeEntry,
    deleteTimeEntry
  ],
  triggers: [ticketEvents, contactEvents, ticketEventsWebhook]
});
