import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCollector,
  createContact,
  createContactList,
  createContactsBulk,
  createSurvey,
  deleteCollector,
  deleteContactList,
  deleteSurvey,
  exportResponses,
  getFileUrl,
  getResource,
  getResponse,
  getResponses,
  getSurvey,
  getUser,
  listCollectors,
  listContactLists,
  listContacts,
  listReferenceData,
  listSurveys,
  manageContact,
  sendInvitation,
  updateCollector,
  updateSurvey
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    listSurveys,
    getSurvey,
    createSurvey,
    updateSurvey,
    deleteSurvey,
    createCollector,
    updateCollector,
    listCollectors,
    deleteCollector,
    getResponses,
    getResponse,
    listContactLists,
    createContactList,
    listContacts,
    createContact,
    createContactsBulk,
    deleteContactList,
    sendInvitation,
    getUser,
    getResource,
    manageContact,
    listReferenceData,
    exportResponses,
    getFileUrl
  ],
  triggers: []
});
