import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCaseComment,
  executeConnector,
  exportSavedObjects,
  getEnrollmentTokens,
  getKibanaStatus,
  listAgentPolicies,
  listConnectors,
  listConnectorTypes,
  listDataViews,
  listFleetAgents,
  listPackagePolicies,
  listRoles,
  listRuleTypes,
  listSpaces,
  manageAgentPolicy,
  manageCase,
  manageConnector,
  manageDataView,
  manageDefaultDataView,
  managePackagePolicy,
  manageRole,
  manageRule,
  manageRuleSnooze,
  manageSavedObject,
  manageSLO,
  manageSpace,
  searchCases,
  searchRules,
  searchSavedObjects,
  searchSLOs
} from './tools';
import { caseChanges, inboundWebhook, ruleStatusChanges } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchSavedObjects,
    manageSavedObject,
    exportSavedObjects,
    listDataViews,
    manageDataView,
    manageDefaultDataView,
    listSpaces,
    manageSpace,
    listRuleTypes,
    searchRules,
    manageRule,
    manageRuleSnooze,
    listConnectorTypes,
    listConnectors,
    manageConnector,
    executeConnector,
    searchCases,
    manageCase,
    addCaseComment,
    searchSLOs,
    manageSLO,
    listAgentPolicies,
    manageAgentPolicy,
    listFleetAgents,
    getEnrollmentTokens,
    listPackagePolicies,
    managePackagePolicy,
    listRoles,
    manageRole,
    getKibanaStatus
  ],
  triggers: [inboundWebhook, ruleStatusChanges, caseChanges]
});
