import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  coreCreateItem,
  datafactoryCreateDataflow,
  datafactoryCreatePipeline,
  datafactoryExecuteQuery,
  datafactoryGetPipeline,
  datafactoryListDataflows,
  datafactoryListPipelines,
  datafactoryRunPipeline,
  docsApiExamples,
  docsBestPractices,
  docsItemDefinitions,
  docsPlatformApiSpec,
  docsWorkloadApiSpec,
  docsWorkloads,
  onelakeCreateDirectory,
  onelakeDeleteDirectory,
  onelakeDeleteFile,
  onelakeDownloadFile,
  onelakeGetTable,
  onelakeGetTableConfig,
  onelakeGetTableNamespace,
  onelakeListFiles,
  onelakeListItems,
  onelakeListItemsDfs,
  onelakeListTableNamespaces,
  onelakeListTables,
  onelakeListWorkspaces,
  onelakeUploadFile
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    docsWorkloads,
    docsWorkloadApiSpec,
    docsPlatformApiSpec,
    docsItemDefinitions,
    docsBestPractices,
    docsApiExamples,
    onelakeListWorkspaces,
    onelakeListItems,
    onelakeListItemsDfs,
    onelakeListFiles,
    onelakeDownloadFile,
    onelakeUploadFile,
    onelakeDeleteFile,
    onelakeCreateDirectory,
    onelakeDeleteDirectory,
    onelakeGetTableConfig,
    onelakeListTableNamespaces,
    onelakeGetTableNamespace,
    onelakeListTables,
    onelakeGetTable,
    coreCreateItem,
    datafactoryListPipelines,
    datafactoryCreatePipeline,
    datafactoryGetPipeline,
    datafactoryRunPipeline,
    datafactoryListDataflows,
    datafactoryCreateDataflow,
    datafactoryExecuteQuery
  ],
  triggers: []
});
