import { Slate } from 'slates';
import { spec } from './spec';
import {
  captureEventTool,
  createAnnotationTool,
  createCohortTool,
  createDashboardTool,
  createExperimentTool,
  createFeatureFlagTool,
  createSurveyTool,
  deleteAnnotationTool,
  deleteDashboardTool,
  deleteFeatureFlagTool,
  deletePersonTool,
  deleteSurveyTool,
  evaluateFeatureFlagsTool,
  getCohortTool,
  getDashboardTool,
  getExperimentTool,
  getFeatureFlagTool,
  getInsightTool,
  getPersonTool,
  getSessionRecordingTool,
  getSurveyTool,
  listAnnotationsTool,
  listCohortsTool,
  listDashboardsTool,
  listEventDefinitionsTool,
  listExperimentsTool,
  listFeatureFlagsTool,
  listInsightsTool,
  listPersonsTool,
  listProjectsTool,
  listPropertyDefinitionsTool,
  listSessionRecordingsTool,
  listSurveysTool,
  runQueryTool,
  updateDashboardTool,
  updateExperimentTool,
  updateFeatureFlagTool,
  updateSurveyTool
} from './tools';
import { featureFlagChangesTrigger, inboundWebhook, newEventsTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    captureEventTool,
    listPersonsTool,
    getPersonTool,
    deletePersonTool,
    listFeatureFlagsTool,
    getFeatureFlagTool,
    createFeatureFlagTool,
    updateFeatureFlagTool,
    deleteFeatureFlagTool,
    evaluateFeatureFlagsTool,
    listExperimentsTool,
    getExperimentTool,
    createExperimentTool,
    updateExperimentTool,
    listSurveysTool,
    getSurveyTool,
    createSurveyTool,
    updateSurveyTool,
    deleteSurveyTool,
    listDashboardsTool,
    getDashboardTool,
    createDashboardTool,
    updateDashboardTool,
    deleteDashboardTool,
    listInsightsTool,
    getInsightTool,
    listCohortsTool,
    getCohortTool,
    createCohortTool,
    listAnnotationsTool,
    createAnnotationTool,
    deleteAnnotationTool,
    runQueryTool,
    listSessionRecordingsTool,
    getSessionRecordingTool,
    listEventDefinitionsTool,
    listPropertyDefinitionsTool,
    listProjectsTool
  ],
  triggers: [inboundWebhook, newEventsTrigger, featureFlagChangesTrigger]
});
