import { ChatAdapter } from '@slates/adapter-chat';
import {
  chatAddReaction,
  chatDeleteMessage,
  chatDownloadFile,
  chatEditMessage,
  chatGetAuthenticatedUser,
  chatGetChannel,
  chatGetMessage,
  chatGetSetup,
  chatGetThread,
  chatGetUser,
  chatGetWorkspace,
  chatListChannelMembers,
  chatListChannels,
  chatListMessages,
  chatListReactions,
  chatListThreads,
  chatListWorkspaces,
  chatMarkMessageRead,
  chatOpenGroupDm,
  chatOpenModal,
  chatOpenSingleDm,
  chatRemoveReaction,
  chatReplyMessage,
  chatRespondToCommand,
  chatSearchMessages,
  chatSearchUsers,
  chatSendEphemeralMessage,
  chatSendMessage,
  chatStartTyping,
  chatUploadFile
} from './tools';
import {
  chatActionInvoked,
  chatCommandInvoked,
  chatMemberJoined,
  chatMemberLeft,
  chatMentionReceived,
  chatMessageDeleted,
  chatMessageReceived,
  chatMessageUpdated,
  chatModalClosed,
  chatModalSubmitted,
  chatOptionsLoad,
  chatReactionAdded,
  chatReactionRemoved
} from './triggers';

export let slackChatTools = [
  chatSendMessage,
  chatEditMessage,
  chatDeleteMessage,
  chatGetMessage,
  chatListMessages,
  chatSearchMessages,
  chatReplyMessage,
  chatSendEphemeralMessage,
  chatMarkMessageRead,
  chatAddReaction,
  chatRemoveReaction,
  chatListReactions,
  chatListChannels,
  chatGetChannel,
  chatListWorkspaces,
  chatGetWorkspace,
  chatListChannelMembers,
  chatListThreads,
  chatGetThread,
  chatOpenSingleDm,
  chatOpenGroupDm,
  chatGetUser,
  chatGetAuthenticatedUser,
  chatSearchUsers,
  chatUploadFile,
  chatDownloadFile,
  chatOpenModal,
  chatRespondToCommand,
  chatStartTyping,
  chatGetSetup
];

export let slackChatTriggers = [
  chatMessageReceived,
  chatMessageUpdated,
  chatMessageDeleted,
  chatMentionReceived,
  chatReactionAdded,
  chatReactionRemoved,
  chatActionInvoked,
  chatModalSubmitted,
  chatModalClosed,
  chatOptionsLoad,
  chatCommandInvoked,
  chatMemberJoined,
  chatMemberLeft
];

export let slackChatAdapter = ChatAdapter.register({
  tools: slackChatTools,
  triggers: slackChatTriggers,
  capabilities: {
    content_markdown: true,
    content_images: true,
    content_rich_links: true,
    content_fields: true,
    content_tables: true,
    content_charts: true,
    content_cards: true,
    content_sections: true,
    content_actions: true,
    attachment_image: true,
    attachment_file: true,
    attachment_video: true,
    attachment_audio: true,
    action_buttons: true,
    action_link_buttons: true,
    action_selects: true,
    action_radio_selects: true,
    action_external_selects: true,
    action_open_modal: true,
    modal_text_input: true,
    modal_date_input: true,
    modal_number_input: true,
    modal_selects: true,
    modal_notify_on_close: true,
    message_ephemeral_native: true,
    message_quote: false,
    message_unfurls: true,
    message_mentions: true,
    reaction_custom_emoji: true,
    channel_private: true,
    channel_shared: true,
    channel_announcement: false,
    channel_forum: false,
    thread_posts: true,
    thread_subject: false,
    resource_context: false,
    command_freeform: true,
    command_structured_options: false,
    command_subcommands: false
  }
});

export * from './tools';
export * from './triggers';
