import { Slate } from 'slates';
import { spec } from './spec';
import {
  assignRepositoryTeam,
  createAccessToken,
  createOrgAccessToken,
  createRepository,
  createTeam,
  createWebhook,
  deleteAccessToken,
  deleteOrgAccessToken,
  deleteRepository,
  deleteTag,
  deleteTeam,
  deleteWebhook,
  getAccessToken,
  getOrgAccessToken,
  getRepository,
  getTag,
  listAccessTokens,
  listAuditLogActions,
  listAuditLogs,
  listOrgAccessTokens,
  listOrgMembers,
  listRepositories,
  listTags,
  listTeams,
  listWebhooks,
  manageTeamMembers,
  removeOrgMember,
  searchRepositories,
  updateAccessToken,
  updateOrgAccessToken,
  updateOrgMemberRole,
  updateRepository,
  updateRepositoryImmutableTags,
  verifyRepositoryImmutableTags
} from './tools';
import { imagePush } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listRepositories,
    getRepository,
    createRepository,
    updateRepository,
    deleteRepository,
    listTags,
    getTag,
    deleteTag,
    searchRepositories,
    listOrgMembers,
    updateOrgMemberRole,
    removeOrgMember,
    listTeams,
    createTeam,
    deleteTeam,
    manageTeamMembers,
    assignRepositoryTeam,
    listWebhooks,
    createWebhook,
    deleteWebhook,
    listAccessTokens,
    getAccessToken,
    createAccessToken,
    updateAccessToken,
    deleteAccessToken,
    listOrgAccessTokens,
    getOrgAccessToken,
    createOrgAccessToken,
    updateOrgAccessToken,
    deleteOrgAccessToken,
    updateRepositoryImmutableTags,
    verifyRepositoryImmutableTags,
    listAuditLogs,
    listAuditLogActions
  ],
  triggers: [imagePush]
});
