import { Slate } from 'slates';
import { spec } from './spec';
import {
  changePostStatusTool,
  createChangelogEntryTool,
  createCommentTool,
  createOrUpdateUserTool,
  createPostTool,
  createVoteTool,
  deleteCommentTool,
  deleteCompanyTool,
  deletePostTool,
  deleteUserTool,
  deleteVoteTool,
  enqueueAutopilotFeedbackTool,
  listBoardsTool,
  listChangelogEntriesTool,
  listCommentsTool,
  listCompaniesTool,
  listOpportunitiesTool,
  listPostsTool,
  listStatusChangesTool,
  listUsersTool,
  listVotesTool,
  manageCategoriesTool,
  managePostOrganizationTool,
  manageTagsTool,
  retrieveBoardTool,
  retrievePostTool,
  retrieveUserTool,
  updateCompanyTool,
  updatePostTool
} from './tools';
import { commentEventsTrigger, postEventsTrigger, voteEventsTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listBoardsTool,
    retrieveBoardTool,
    createPostTool,
    retrievePostTool,
    listPostsTool,
    updatePostTool,
    deletePostTool,
    changePostStatusTool,
    managePostOrganizationTool,
    createCommentTool,
    listCommentsTool,
    deleteCommentTool,
    createVoteTool,
    listVotesTool,
    deleteVoteTool,
    createOrUpdateUserTool,
    retrieveUserTool,
    listUsersTool,
    deleteUserTool,
    listCompaniesTool,
    updateCompanyTool,
    deleteCompanyTool,
    manageCategoriesTool,
    manageTagsTool,
    createChangelogEntryTool,
    listChangelogEntriesTool,
    listStatusChangesTool,
    enqueueAutopilotFeedbackTool,
    listOpportunitiesTool
  ],
  triggers: [postEventsTrigger, commentEventsTrigger, voteEventsTrigger]
});
