import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCompany,
  createDeal,
  createNote,
  createPerson,
  createReminder,
  deleteCompany,
  deleteDeal,
  deleteNote,
  deletePerson,
  deleteReminder,
  getCompany,
  getCurrentUser,
  getDeal,
  getPerson,
  listCompanies,
  listCustomFields,
  listDeals,
  listGroups,
  listNotes,
  listPeople,
  listReminders,
  listTasks,
  manageTask,
  updateCompany,
  updateDeal,
  updateNote,
  updatePerson
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getCurrentUser,
    listTasks,
    manageTask,
    createPerson,
    updatePerson,
    getPerson,
    listPeople,
    deletePerson,
    createCompany,
    updateCompany,
    getCompany,
    listCompanies,
    deleteCompany,
    createDeal,
    updateDeal,
    getDeal,
    listDeals,
    deleteDeal,
    createNote,
    updateNote,
    listNotes,
    deleteNote,
    createReminder,
    listReminders,
    deleteReminder,
    listGroups,
    listCustomFields
  ],
  triggers: []
});
