import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAccount,
  createContract,
  createExpenseReport,
  createInvoice,
  createPurchaseOrder,
  createReceipt,
  createRequisition,
  createSupplier,
  createUser,
  getInvoice,
  getPurchaseOrder,
  getResource,
  processApproval,
  searchAccounts,
  searchApprovals,
  searchContracts,
  searchExpenseReports,
  searchInvoices,
  searchPurchaseOrders,
  searchReceipts,
  searchRequisitions,
  searchSuppliers,
  searchUsers,
  updatePurchaseOrder,
  updateSupplier,
  updateUser
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getResource,
    searchPurchaseOrders,
    getPurchaseOrder,
    createPurchaseOrder,
    updatePurchaseOrder,
    searchInvoices,
    getInvoice,
    createInvoice,
    searchSuppliers,
    createSupplier,
    updateSupplier,
    searchRequisitions,
    createRequisition,
    searchExpenseReports,
    createExpenseReport,
    searchContracts,
    createContract,
    searchApprovals,
    processApproval,
    searchUsers,
    createUser,
    updateUser,
    searchAccounts,
    createAccount,
    searchReceipts,
    createReceipt
  ],
  triggers: []
});
