import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  createHook,
  createSite,
  createSnippet,
  createSplitTest,
  deleteEnvVar,
  deleteFormSubmission,
  deleteHook,
  deleteSite,
  deleteSnippet,
  getDeploy,
  getFormSubmission,
  getSite,
  listAccounts,
  listDeploys,
  listDnsZones,
  listEnvVars,
  listFormSubmissions,
  listForms,
  listHooks,
  listHookTypes,
  listSites,
  listSnippets,
  listSplitTests,
  manageBuildHooks,
  manageBuilds,
  manageDeploy,
  manageDnsRecords,
  manageDnsZone,
  manageFormSubmissionState,
  manageSiteFiles,
  manageSiteMetadata,
  purgeCache,
  setEnvVars,
  toggleSplitTest,
  updateHook,
  updateSite,
  updateSnippet,
  updateSplitTest
} from './tools';
import { deployEvents, formSubmissionEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listSites,
    getSite,
    createSite,
    updateSite,
    deleteSite,
    listDeploys,
    getDeploy,
    manageDeploy,
    listEnvVars,
    setEnvVars,
    deleteEnvVar,
    listForms,
    listFormSubmissions,
    getFormSubmission,
    manageFormSubmissionState,
    deleteFormSubmission,
    listDnsZones,
    manageDnsRecords,
    manageDnsZone,
    listSnippets,
    createSnippet,
    updateSnippet,
    deleteSnippet,
    listHooks,
    listHookTypes,
    createHook,
    updateHook,
    deleteHook,
    manageBuildHooks,
    manageBuilds,
    listSplitTests,
    createSplitTest,
    updateSplitTest,
    toggleSplitTest,
    purgeCache,
    listAccounts,
    manageSiteMetadata,
    manageSiteFiles
  ],
  triggers: [deployEvents, formSubmissionEvents]
});
