import { Slate } from 'slates';
import { spec } from './spec';
import {
  cancelTransferTool,
  createAssetReportTool,
  createLinkTokenTool,
  createTransferTool,
  enrichTransactionsTool,
  evaluateSignalTool,
  exchangePublicTokenTool,
  getAccountsTool,
  getAssetReportTool,
  getAuthTool,
  getBalancesTool,
  getHoldingsTool,
  getIdentityTool,
  getInstitutionTool,
  getInvestmentTransactionsTool,
  getItemTool,
  getLiabilitiesTool,
  getTransactionsTool,
  getTransferTool,
  listTransfersTool,
  manageTransferAuthorizationTool,
  removeAssetReportTool,
  removeItemTool,
  searchInstitutionsTool,
  syncTransactionsTool
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getAccountsTool,
    getBalancesTool,
    syncTransactionsTool,
    getTransactionsTool,
    getAuthTool,
    getIdentityTool,
    getHoldingsTool,
    getInvestmentTransactionsTool,
    getLiabilitiesTool,
    searchInstitutionsTool,
    getInstitutionTool,
    createLinkTokenTool,
    exchangePublicTokenTool,
    getItemTool,
    removeItemTool,
    createTransferTool,
    getTransferTool,
    listTransfersTool,
    evaluateSignalTool,
    enrichTransactionsTool,
    createAssetReportTool,
    getAssetReportTool,
    manageTransferAuthorizationTool,
    cancelTransferTool,
    removeAssetReportTool
  ],
  triggers: []
});
