import { Slate } from 'slates';
import { spec } from './spec';
import {
  addComment,
  createPortfolio,
  createProject,
  createSection,
  createTag,
  createTask,
  deleteProject,
  deleteSection,
  deleteTask,
  getGoal,
  getPortfolio,
  getProject,
  getTask,
  getUser,
  listComments,
  listGoals,
  listPortfolios,
  listProjects,
  listSections,
  listSubtasks,
  listTags,
  listTasks,
  listTeams,
  listTimeTrackingEntries,
  listUsers,
  listWorkspaces,
  manageAttachments,
  manageCustomFields,
  manageProjectTemplates,
  searchTasks,
  typeaheadSearch,
  updatePortfolio,
  updateProject,
  updateSection,
  updateTask
} from './tools';
import { projectEvents, taskChangesWebhook, taskEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listWorkspaces,
    listProjects,
    getProject,
    createProject,
    updateProject,
    deleteProject,
    listTasks,
    getTask,
    createTask,
    updateTask,
    deleteTask,
    searchTasks,
    listSubtasks,
    listSections,
    createSection,
    updateSection,
    deleteSection,
    listComments,
    addComment,
    listTags,
    createTag,
    manageAttachments,
    manageCustomFields,
    listPortfolios,
    getPortfolio,
    createPortfolio,
    updatePortfolio,
    manageProjectTemplates,
    listGoals,
    getGoal,
    listUsers,
    getUser,
    listTeams,
    listTimeTrackingEntries,
    typeaheadSearch
  ],
  triggers: [projectEvents, taskEvents, taskChangesWebhook]
});
