import { Slate } from 'slates';
import { spec } from './spec';
import {
  cancelRun,
  createEmbeddingUrl,
  createProject,
  deactivateUser,
  deleteGroup,
  exportProject,
  getCollection,
  getCurrentUser,
  getDataConnection,
  getGroup,
  getProject,
  getQueriedTables,
  getRunStatus,
  listCollections,
  listDataConnections,
  listGroups,
  listProjectRuns,
  listProjects,
  listUsers,
  manageCollection,
  manageGroup,
  manageProjectSharing,
  runProject,
  updateProjectStatus
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    listProjects,
    getProject,
    createProject,
    updateProjectStatus,
    runProject,
    getRunStatus,
    cancelRun,
    listProjectRuns,
    manageProjectSharing,
    createEmbeddingUrl,
    listUsers,
    deactivateUser,
    manageGroup,
    listGroups,
    deleteGroup,
    manageCollection,
    listCollections,
    listDataConnections,
    getDataConnection,
    getQueriedTables,
    getCurrentUser,
    getGroup,
    getCollection,
    exportProject
  ],
  triggers: []
});
