import { Slate } from 'slates';
import { spec } from './spec';
import {
  chargeAuthorization,
  createCustomer,
  createDedicatedVirtualAccount,
  createPaymentPage,
  createPaymentRequest,
  createPlan,
  createRefund,
  createSubaccount,
  createSubscription,
  createTransferRecipient,
  disableSubscription,
  enableSubscription,
  getCustomer,
  getSubscription,
  initializeTransaction,
  initiateTransfer,
  listBanks,
  listCustomers,
  listDedicatedVirtualAccounts,
  listDisputes,
  listPaymentPages,
  listPaymentRequests,
  listPlans,
  listRefunds,
  listSettlements,
  listSubaccounts,
  listSubscriptions,
  listTransactions,
  listTransfers,
  resolveCardBin,
  resolveDispute,
  updateCustomer,
  updatePaymentPage,
  updatePlan,
  verifyBankAccount,
  verifyTransaction
} from './tools';
import {
  customerIdentificationEvents,
  dedicatedVirtualAccountEvents,
  disputeEvents,
  invoiceEvents,
  refundEvents,
  subscriptionEvents,
  transactionEvents,
  transferEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    initializeTransaction,
    verifyTransaction,
    listTransactions,
    chargeAuthorization,
    createCustomer,
    getCustomer,
    updateCustomer,
    listCustomers,
    createPlan,
    listPlans,
    updatePlan,
    createSubscription,
    getSubscription,
    listSubscriptions,
    disableSubscription,
    enableSubscription,
    initiateTransfer,
    createTransferRecipient,
    listTransfers,
    createRefund,
    listRefunds,
    listSettlements,
    createPaymentPage,
    listPaymentPages,
    updatePaymentPage,
    createPaymentRequest,
    listPaymentRequests,
    createSubaccount,
    listSubaccounts,
    createDedicatedVirtualAccount,
    listDedicatedVirtualAccounts,
    listDisputes,
    resolveDispute,
    verifyBankAccount,
    listBanks,
    resolveCardBin
  ],
  triggers: [
    transactionEvents,
    transferEvents,
    subscriptionEvents,
    invoiceEvents,
    refundEvents,
    disputeEvents,
    customerIdentificationEvents,
    dedicatedVirtualAccountEvents
  ]
});
