import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCommentTool,
  cancelWorkflowTool,
  copyItemTool,
  createAuditReportTool,
  createFolderTool,
  createGroupTool,
  createLinkTool,
  createUserTool,
  createWorkflowTool,
  deleteCommentTool,
  deleteGroupTool,
  deleteItemTool,
  deleteLinkTool,
  deleteUserTool,
  emptyTrashTool,
  getAuditReportTool,
  getFileInfoTool,
  getPermissionsTool,
  getUserTool,
  getWorkflowTool,
  listCommentsTool,
  listFolderTool,
  listGroupsTool,
  listLinksTool,
  listTrashTool,
  listUsersTool,
  listWorkflowTasksTool,
  lockFileTool,
  moveItemTool,
  restoreFromTrashTool,
  searchTool,
  setMetadataTool,
  setPermissionsTool,
  updateGroupTool,
  updateUserTool
} from './tools';
import { contentEventsTrigger, fileActivityTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listFolderTool,
    getFileInfoTool,
    createFolderTool,
    copyItemTool,
    moveItemTool,
    deleteItemTool,
    lockFileTool,
    createLinkTool,
    listLinksTool,
    deleteLinkTool,
    getPermissionsTool,
    setPermissionsTool,
    listUsersTool,
    getUserTool,
    createUserTool,
    updateUserTool,
    deleteUserTool,
    listGroupsTool,
    createGroupTool,
    updateGroupTool,
    deleteGroupTool,
    searchTool,
    addCommentTool,
    listCommentsTool,
    deleteCommentTool,
    setMetadataTool,
    listTrashTool,
    restoreFromTrashTool,
    emptyTrashTool,
    createWorkflowTool,
    getWorkflowTool,
    listWorkflowTasksTool,
    cancelWorkflowTool,
    createAuditReportTool,
    getAuditReportTool
  ],
  triggers: [contentEventsTrigger, fileActivityTrigger]
});
