import { SlateTool } from 'slates';
import { z } from 'zod';
import { OwlClient } from '../lib/client';
import { spec } from '../spec';

export let mintTokens = SlateTool.create(spec, {
  name: 'Mint ERC721 Tokens',
  key: 'mint_tokens',
  description: `Mint one or more ERC721 tokens (NFTs) from a deployed collection to specified recipients.
Recipients can be email addresses, user IDs, or Ethereum wallet addresses.
Token IDs are auto-generated by the contract.
Supports both inline metadata and template-based minting.`,
  instructions: [
    'Provide either metadata or a templateId, not both.',
    'Recipients can be email addresses (for project users), user IDs, or Ethereum addresses.',
    'The collection must already be deployed before minting.'
  ],
  tags: {
    destructive: false,
    readOnly: false
  }
})
  .input(
    z.object({
      chainId: z.number().describe('Chain ID where the collection is deployed'),
      contractAddress: z
        .string()
        .describe('Contract address of the deployed ERC721 collection'),
      recipients: z
        .array(z.string())
        .describe('Array of recipients: email addresses, user IDs, or Ethereum addresses'),
      metadata: z
        .object({
          name: z.string().optional().describe('Token name'),
          description: z.string().optional().describe('Token description'),
          image: z.string().optional().describe('Token image URL or base64-encoded image'),
          attributes: z
            .array(
              z.object({
                trait_type: z.string().describe('Attribute name'),
                value: z.string().describe('Attribute value')
              })
            )
            .optional()
            .describe('Token attributes/traits')
        })
        .optional()
        .describe('Inline metadata for the minted tokens'),
      templateId: z
        .string()
        .optional()
        .describe('ID of a previously created token template to use for metadata')
    })
  )
  .output(
    z.object({
      tokens: z
        .array(z.record(z.string(), z.unknown()))
        .optional()
        .describe('Array of minted token details including tokenId and recipient'),
      userOpHash: z.string().optional().describe('Transaction hash for the mint operation'),
      metadata: z
        .record(z.string(), z.unknown())
        .optional()
        .describe('Metadata applied to the minted tokens')
    })
  )
  .handleInvocation(async ctx => {
    let client = new OwlClient({ token: ctx.auth.token });

    let chainId = ctx.input.chainId ?? ctx.config.chainId;
    if (!chainId) {
      throw new Error(
        'chainId is required. Provide it in the input or set a default in the configuration.'
      );
    }

    ctx.info({
      message: 'Minting tokens',
      contractAddress: ctx.input.contractAddress,
      recipientCount: ctx.input.recipients.length,
      chainId
    });

    let result = await client.mintBatchERC721({
      chainId,
      contractAddress: ctx.input.contractAddress,
      to: ctx.input.recipients,
      metadata: ctx.input.metadata,
      projectTokenTemplateId: ctx.input.templateId
    });

    let tokenCount = result.tokens?.length ?? ctx.input.recipients.length;

    return {
      output: {
        tokens: result.tokens,
        userOpHash: result.userOpHash,
        metadata: result.metadata
      },
      message: `Minted **${tokenCount}** token(s) on chain ${chainId} to ${ctx.input.recipients.length} recipient(s). Transaction: \`${result.userOpHash}\``
    };
  })
  .build();
