import { Slate } from 'slates';
import { spec } from './spec';
import {
  createOrUpdateCategory,
  createOrUpdateCustomer,
  createOrUpdateDiscount,
  createOrUpdateItem,
  createOrUpdateModifier,
  createOrUpdateSupplier,
  createOrUpdateTax,
  createReceipt,
  createRefund,
  deleteCategory,
  deleteCustomer,
  deleteDiscount,
  deleteItem,
  deleteModifier,
  deleteSupplier,
  deleteTax,
  getInventory,
  getItem,
  getMerchant,
  getReceipt,
  listCategories,
  listCustomers,
  listDiscounts,
  listEmployees,
  listItems,
  listModifiers,
  listPaymentTypes,
  listReceipts,
  listShifts,
  listStores,
  listSuppliers,
  listTaxes,
  updateInventory
} from './tools';
import {
  customerEvents,
  inventoryEvents,
  itemEvents,
  receiptEvents,
  shiftEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listItems,
    getItem,
    createOrUpdateItem,
    deleteItem,
    listCustomers,
    createOrUpdateCustomer,
    deleteCustomer,
    listReceipts,
    getReceipt,
    createReceipt,
    createRefund,
    getInventory,
    updateInventory,
    listCategories,
    createOrUpdateCategory,
    deleteCategory,
    listDiscounts,
    createOrUpdateDiscount,
    deleteDiscount,
    listModifiers,
    createOrUpdateModifier,
    deleteModifier,
    listTaxes,
    createOrUpdateTax,
    deleteTax,
    listSuppliers,
    createOrUpdateSupplier,
    deleteSupplier,
    listEmployees,
    listStores,
    listShifts,
    listPaymentTypes,
    getMerchant
  ],
  triggers: [receiptEvents, itemEvents, inventoryEvents, customerEvents, shiftEvents]
});
