import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

export let getCampaignReport = SlateTool.create(spec, {
  name: 'Get Campaign Report',
  key: 'get_campaign_report',
  description: `Retrieve the performance report for a sent campaign. Includes delivery rate, opens, clicks, bounces, unsubscribes, and other engagement metrics.
Only available for campaigns that have been sent.`,
  tags: {
    destructive: false,
    readOnly: true
  }
})
  .input(
    z.object({
      campaignId: z.number().describe('ID of the campaign to get the report for')
    })
  )
  .output(
    z.object({
      campaignId: z.number().describe('Campaign ID'),
      campaignName: z.string().describe('Campaign name'),
      campaignSubject: z.string().describe('Campaign subject line'),
      campaignStatus: z.string().describe('Campaign status'),
      deliveryRate: z.number().describe('Percentage of emails successfully delivered'),
      totalShipped: z.number().describe('Total number of emails sent'),
      uniqueOpens: z.number().describe('Number of unique opens'),
      totalOpens: z.number().describe('Total number of opens (including repeats)'),
      lastOpenDate: z.string().optional().describe('Date of the most recent open'),
      uniqueClicks: z.number().describe('Number of unique clicks'),
      totalClicks: z.number().describe('Total number of clicks (including repeats)'),
      lastClickDate: z.string().optional().describe('Date of the most recent click'),
      totalUnopened: z.number().describe('Number of emails that were not opened'),
      hardBounces: z.number().describe('Number of permanent delivery failures'),
      softBounces: z.number().describe('Number of temporary delivery failures'),
      totalUnsubscribes: z
        .number()
        .describe('Number of unsubscribes generated by this campaign')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({
      token: ctx.auth.token,
      accountEmail: ctx.config.accountEmail
    });

    let report = await client.getCampaignReport(ctx.input.campaignId);

    return {
      output: {
        campaignId: report.campaignId,
        campaignName: report.campaignName,
        campaignSubject: report.campaignSubject,
        campaignStatus: report.campaignStatus,
        deliveryRate: report.deliveryRate,
        totalShipped: report.totalShipped,
        uniqueOpens: report.uniqueOpens,
        totalOpens: report.totalOpens,
        lastOpenDate: report.lastOpenDate,
        uniqueClicks: report.uniqueClicks,
        totalClicks: report.totalClicks,
        lastClickDate: report.lastClickDate,
        totalUnopened: report.totalUnopened,
        hardBounces: report.hardBounces,
        softBounces: report.softBounces,
        totalUnsubscribes: report.totalUnsubscribes
      },
      message: `Campaign **${report.campaignName}**: ${report.deliveryRate}% delivery rate, ${report.uniqueOpens} unique opens, ${report.uniqueClicks} unique clicks, ${report.hardBounces + report.softBounces} bounces.`
    };
  })
  .build();
