import { Slate } from 'slates';
import { spec } from './spec';
import {
  assignIpAddress,
  controlMachine,
  createApp,
  createMachine,
  createVolume,
  deleteApp,
  deleteIpAssignment,
  deleteMachine,
  getApp,
  getMachine,
  getMachineMemory,
  listApps,
  listIpAssignments,
  listMachineEvents,
  listMachineProcesses,
  listMachines,
  listMachineVersions,
  listOrgMachines,
  listOrgVolumes,
  listRegions,
  listVolumes,
  manageCertificates,
  manageMachineLease,
  manageMachineMetadata,
  manageSecrets,
  manageVolume,
  requestOidcToken,
  updateMachine,
  waitForMachine
} from './tools';
import { appMachinesChanged, inboundWebhook, machineStateChanged } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listApps,
    getApp,
    createApp,
    deleteApp,
    listIpAssignments,
    assignIpAddress,
    deleteIpAssignment,
    listRegions,
    listOrgMachines,
    listOrgVolumes,
    listMachines,
    getMachine,
    getMachineMemory,
    listMachineEvents,
    listMachineProcesses,
    listMachineVersions,
    createMachine,
    updateMachine,
    controlMachine,
    deleteMachine,
    waitForMachine,
    manageMachineLease,
    manageMachineMetadata,
    listVolumes,
    createVolume,
    manageVolume,
    manageSecrets,
    manageCertificates,
    requestOidcToken
  ],
  triggers: [inboundWebhook, machineStateChanged, appMachinesChanged]
});
