import { Slate } from 'slates';
import { spec } from './spec';
import {
  answerTool,
  cancelWebsetTool,
  createEnrichmentTool,
  createExportTool,
  createMonitorTool,
  createResearchTool,
  createWebsetTool,
  deleteEnrichmentTool,
  deleteMonitorTool,
  deleteWebsetItemTool,
  deleteWebsetTool,
  findSimilarTool,
  getContentsTool,
  getExportTool,
  getResearchTool,
  getTeamInfoTool,
  getWebsetItemTool,
  getWebsetTool,
  listWebsetItemsTool,
  listWebsetsTool,
  searchTool,
  updateEnrichmentTool,
  updateWebsetTool
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    searchTool,
    getContentsTool,
    findSimilarTool,
    answerTool,
    createResearchTool,
    getResearchTool,
    createWebsetTool,
    getWebsetTool,
    listWebsetsTool,
    updateWebsetTool,
    deleteWebsetTool,
    cancelWebsetTool,
    listWebsetItemsTool,
    getWebsetItemTool,
    deleteWebsetItemTool,
    createEnrichmentTool,
    updateEnrichmentTool,
    deleteEnrichmentTool,
    createMonitorTool,
    deleteMonitorTool,
    createExportTool,
    getExportTool,
    getTeamInfoTool
  ],
  triggers: []
});
