import { createApiServiceError, SlateTool } from 'slates';
import { z } from 'zod';
import {
  type LookerAlert,
  type LookerAlertDestination,
  type LookerAlertPatch,
  LookerClient,
  type LookerFullUpdateAlert,
  type LookerWriteAlertAppliedDashboardFilter
} from '../lib/client';
import { spec } from '../spec';

let comparisonTypes = [
  'EQUAL_TO',
  'GREATER_THAN',
  'GREATER_THAN_OR_EQUAL_TO',
  'LESS_THAN',
  'LESS_THAN_OR_EQUAL_TO',
  'INCREASES_BY',
  'DECREASES_BY',
  'CHANGES_BY'
] as const;

let alertFieldFilterSchema = z.object({
  fieldName: z.string().describe('Field name'),
  fieldValue: z.unknown().describe('Field value to match'),
  filterValue: z
    .string()
    .nullable()
    .optional()
    .describe('Filter value, normally null except for location fields')
});

let appliedDashboardFilterSchema = z.object({
  filterTitle: z.string().nullable().describe('Dashboard filter title'),
  fieldName: z.string().describe('Dashboard filter field name'),
  filterValue: z.string().describe('Looker filter expression value')
});

let alertDestinationSchema = z.object({
  destinationType: z
    .string()
    .describe('Destination type; Looker supports "EMAIL" and "ACTION_HUB"'),
  emailAddress: z
    .string()
    .nullable()
    .optional()
    .describe('Email address for an EMAIL destination'),
  actionHubIntegrationId: z
    .string()
    .nullable()
    .optional()
    .describe('Integration ID for an ACTION_HUB destination'),
  actionHubFormParamsJson: z
    .string()
    .nullable()
    .optional()
    .describe('JSON form parameters for an ACTION_HUB destination')
});

let alertOutputSchema = z.object({
  alertId: z.string().describe('Alert ID'),
  customTitle: z.string().nullable().optional().describe('Custom alert title'),
  comparisonType: z.string().describe('Comparison used by the alert condition'),
  threshold: z.number().describe('Alert threshold value'),
  cron: z
    .string()
    .describe('Vixie-style cron schedule; Looker requires intervals longer than 15 minutes'),
  queryId: z.string().nullable().optional().describe('Query ID evaluated by the alert'),
  dashboardElementId: z
    .string()
    .nullable()
    .optional()
    .describe('User-defined dashboard element ID'),
  lookmlDashboardId: z.string().nullable().optional().describe('LookML dashboard ID'),
  lookmlLinkId: z.string().nullable().optional().describe('LookML dashboard element ID'),
  description: z.string().nullable().optional().describe('Alert description'),
  enhancements: z
    .string()
    .nullable()
    .optional()
    .describe('Additional alert behavior, such as STRATEGIC_NARRATIVE'),
  destinations: z
    .array(alertDestinationSchema)
    .nullable()
    .describe('Notification destinations'),
  appliedDashboardFilters: z
    .array(
      appliedDashboardFilterSchema.extend({
        filterDescription: z
          .string()
          .nullable()
          .optional()
          .describe('Human-readable filter description generated by Looker')
      })
    )
    .nullable()
    .optional()
    .describe('Dashboard filters applied to the alert query'),
  fieldName: z.string().describe('Monitored field name'),
  fieldTitle: z.string().describe('Monitored field title'),
  fieldFilters: z
    .array(alertFieldFilterSchema)
    .nullable()
    .optional()
    .describe('Additional filters on the monitored field'),
  followed: z.boolean().optional().describe('Whether the current user follows the alert'),
  followable: z.boolean().optional().describe('Whether users may follow the alert'),
  isDisabled: z.boolean().optional().describe('Whether the alert is disabled'),
  disabledReason: z.string().nullable().optional().describe('Reason the alert is disabled'),
  isPublic: z.boolean().optional().describe('Whether the alert is public'),
  ownerId: z.string().describe('Alert owner user ID'),
  ownerDisplayName: z.string().nullable().optional().describe('Alert owner display name'),
  investigativeContentType: z
    .string()
    .nullable()
    .optional()
    .describe('Investigative content type'),
  investigativeContentId: z
    .string()
    .nullable()
    .optional()
    .describe('Investigative content ID'),
  investigativeContentTitle: z
    .string()
    .nullable()
    .optional()
    .describe('Investigative content title'),
  customUrlBase: z.string().nullable().optional().describe('Custom alert URL domain'),
  customUrlParams: z
    .string()
    .nullable()
    .optional()
    .describe('Custom alert URL path and params'),
  customUrlLabel: z.string().nullable().optional().describe('Custom alert URL label'),
  showCustomUrl: z.boolean().optional().describe('Whether notifications use the custom URL'),
  deleted: z
    .boolean()
    .optional()
    .describe('Whether this operation permanently deleted the alert')
});

type AlertDestinationInput = z.infer<typeof alertDestinationSchema>;

let validationError = (message: string, reason: string) =>
  createApiServiceError(message, { reason });

let mapDestinations = (
  destinations: AlertDestinationInput[],
  action: 'create' | 'update'
): LookerAlertDestination[] => {
  if (destinations.length === 0) {
    throw validationError(
      `At least one destination is required for ${action} action.`,
      'looker_alert_destination_required'
    );
  }

  let destinationType = destinations[0]?.destinationType;
  if (!destinations.every(destination => destination.destinationType === destinationType)) {
    throw validationError(
      'All alert destinations must have the same destinationType.',
      'looker_alert_destination_types_must_match'
    );
  }

  return destinations.map(destination => {
    if (destination.destinationType === 'EMAIL') {
      if (!destination.emailAddress) {
        throw validationError(
          'emailAddress is required for every EMAIL destination.',
          'looker_alert_email_address_required'
        );
      }
      if (
        destination.actionHubIntegrationId != null ||
        destination.actionHubFormParamsJson != null
      ) {
        throw validationError(
          'ACTION_HUB fields cannot be used with an EMAIL destination.',
          'looker_alert_destination_fields_invalid'
        );
      }
    } else if (destination.destinationType === 'ACTION_HUB') {
      if (!destination.actionHubIntegrationId) {
        throw validationError(
          'actionHubIntegrationId is required for every ACTION_HUB destination.',
          'looker_alert_action_hub_integration_required'
        );
      }
      if (destination.emailAddress != null) {
        throw validationError(
          'emailAddress cannot be used with an ACTION_HUB destination.',
          'looker_alert_destination_fields_invalid'
        );
      }
    } else {
      throw validationError(
        'destinationType must be EMAIL or ACTION_HUB.',
        'looker_alert_destination_type_invalid'
      );
    }

    return {
      destination_type: destination.destinationType,
      email_address: destination.emailAddress,
      action_hub_integration_id: destination.actionHubIntegrationId,
      action_hub_form_params_json: destination.actionHubFormParamsJson
    };
  });
};

let mapAlert = (alert: LookerAlert, deleted = false) => {
  if (typeof alert?.id !== 'string' || alert.id.length === 0) {
    throw validationError(
      'Looker returned an alert without an ID.',
      'looker_alert_invalid_response'
    );
  }
  if (!alert.field?.name || !alert.field.title) {
    throw validationError(
      'Looker returned an alert without its monitored field.',
      'looker_alert_invalid_response'
    );
  }
  if (typeof alert.owner_id !== 'string' || alert.owner_id.length === 0) {
    throw validationError(
      'Looker returned an alert without an owner ID.',
      'looker_alert_invalid_response'
    );
  }
  if (typeof alert.comparison_type !== 'string' || typeof alert.cron !== 'string') {
    throw validationError(
      'Looker returned an alert without its condition or schedule.',
      'looker_alert_invalid_response'
    );
  }
  if (typeof alert.threshold !== 'number') {
    throw validationError(
      'Looker returned an alert without a numeric threshold.',
      'looker_alert_invalid_response'
    );
  }

  return {
    alertId: alert.id,
    customTitle: alert.custom_title,
    comparisonType: alert.comparison_type,
    threshold: alert.threshold,
    cron: alert.cron,
    queryId: alert.query_id,
    dashboardElementId: alert.dashboard_element_id,
    lookmlDashboardId: alert.lookml_dashboard_id,
    lookmlLinkId: alert.lookml_link_id,
    description: alert.description,
    enhancements: alert.enhancements,
    destinations:
      alert.destinations === null
        ? null
        : alert.destinations?.map(destination => ({
            destinationType: destination.destination_type,
            emailAddress: destination.email_address,
            actionHubIntegrationId: destination.action_hub_integration_id,
            actionHubFormParamsJson: destination.action_hub_form_params_json
          })),
    appliedDashboardFilters:
      alert.applied_dashboard_filters === null
        ? null
        : alert.applied_dashboard_filters?.map(filter => ({
            filterTitle: filter.filter_title,
            fieldName: filter.field_name,
            filterValue: filter.filter_value,
            filterDescription: filter.filter_description
          })),
    fieldName: alert.field.name,
    fieldTitle: alert.field.title,
    fieldFilters:
      alert.field.filter === null
        ? null
        : alert.field.filter?.map(filter => ({
            fieldName: filter.field_name,
            fieldValue: filter.field_value,
            filterValue: filter.filter_value
          })),
    followed: alert.followed,
    followable: alert.followable,
    isDisabled: alert.is_disabled,
    disabledReason: alert.disabled_reason,
    isPublic: alert.is_public,
    ownerId: alert.owner_id,
    ownerDisplayName: alert.owner_display_name,
    investigativeContentType: alert.investigative_content_type,
    investigativeContentId: alert.investigative_content_id,
    investigativeContentTitle: alert.investigative_content_title,
    customUrlBase: alert.custom_url_base,
    customUrlParams: alert.custom_url_params,
    customUrlLabel: alert.custom_url_label,
    showCustomUrl: alert.show_custom_url,
    deleted: deleted || undefined
  };
};

let alertLabel = (alert: ReturnType<typeof mapAlert>) => alert.customTitle || alert.alertId;

export let manageAlert = SlateTool.create(spec, {
  name: 'Manage Alert',
  key: 'manage_alert',
  description: `Get, create, update, permanently delete, or search data-driven alerts on dashboard tiles. Alerts trigger notifications when data meets specified conditions.`,
  instructions: [
    'To search alerts: set action to "list" and optionally provide pagination, grouping, execution-state, frequency, date-range, or owner filters.',
    'To get: set action to "get" with alertId.',
    'To create: set action to "create" with either dashboardElementId or both lookmlDashboardId and lookmlLinkId, plus comparisonType, threshold, cron, fieldTitle, fieldName, and destinations.',
    'To update: set action to "update" with alertId and at least one field to change. Looker applies owner, disabled, public, threshold, and enhancement-only updates selectively; other changes replace the complete alert definition while preserving omitted values.',
    'To permanently delete: set action to "delete" with alertId.'
  ]
})
  .input(
    z.object({
      action: z
        .enum(['get', 'list', 'create', 'update', 'delete'])
        .describe('Action to perform'),
      alertId: z.string().optional().describe('Alert ID (required for get, update, delete)'),
      limit: z.number().int().min(0).optional().describe('Maximum list results to return'),
      offset: z.number().int().min(0).optional().describe('Number of list results to skip'),
      groupBy: z
        .enum(['dashboard', 'owner'])
        .optional()
        .describe('Dimension by which Looker orders list results'),
      disabled: z.boolean().optional().describe('Filter list results by disabled state'),
      frequency: z
        .string()
        .optional()
        .describe(
          'Filter list results by frequency, such as monthly, weekly, daily, hourly, or minutes'
        ),
      conditionMet: z
        .boolean()
        .optional()
        .describe('Filter list results by whether the last execution met the condition'),
      lastRunStart: z
        .string()
        .optional()
        .describe('Inclusive start of the last-run timestamp range'),
      lastRunEnd: z.string().optional().describe('End of the last-run timestamp range'),
      allOwners: z
        .boolean()
        .optional()
        .describe('Admin-only list filter that includes alerts from all owners'),
      dashboardElementId: z
        .string()
        .nullable()
        .optional()
        .describe('User-defined dashboard element ID to monitor'),
      lookmlDashboardId: z
        .string()
        .nullable()
        .optional()
        .describe('LookML dashboard ID to monitor'),
      lookmlLinkId: z
        .string()
        .nullable()
        .optional()
        .describe('LookML dashboard element ID to monitor'),
      queryId: z.string().nullable().optional().describe('Query ID evaluated by the alert'),
      comparisonType: z
        .enum(comparisonTypes)
        .optional()
        .describe(`Comparison type: ${comparisonTypes.join(', ')}`),
      threshold: z.number().optional().describe('Numeric threshold, including zero'),
      cron: z
        .string()
        .optional()
        .describe('Vixie-style cron schedule; intervals must be longer than 15 minutes'),
      customTitle: z
        .string()
        .nullable()
        .optional()
        .describe('Custom alert title; null clears it'),
      description: z
        .string()
        .nullable()
        .optional()
        .describe('Alert description; null clears it'),
      fieldTitle: z.string().optional().describe('Title of the field to monitor'),
      fieldName: z.string().optional().describe('Name of the field to monitor'),
      fieldFilters: z
        .array(alertFieldFilterSchema)
        .nullable()
        .optional()
        .describe('Advanced filters that further restrict the monitored field'),
      appliedDashboardFilters: z
        .array(appliedDashboardFilterSchema)
        .nullable()
        .optional()
        .describe('Dashboard filters applied to the alert query'),
      destinations: z
        .array(alertDestinationSchema)
        .optional()
        .describe('One or more notification destinations, all of the same destination type'),
      ownerId: z.string().optional().describe('Alert owner user ID'),
      isDisabled: z.boolean().optional().describe('Whether the alert is disabled'),
      disabledReason: z
        .string()
        .nullable()
        .optional()
        .describe('Reason the alert is disabled; null clears it'),
      isPublic: z.boolean().optional().describe('Whether the alert is public'),
      enhancements: z
        .enum(['NONE', 'STRATEGIC_NARRATIVE'])
        .nullable()
        .optional()
        .describe('Additional alert behavior; null clears it'),
      customUrlBase: z
        .string()
        .nullable()
        .optional()
        .describe('Custom notification URL domain from the admin allowlist'),
      customUrlParams: z
        .string()
        .nullable()
        .optional()
        .describe('Custom notification URL path and parameters'),
      customUrlLabel: z
        .string()
        .nullable()
        .optional()
        .describe('Custom notification URL label'),
      showCustomUrl: z
        .boolean()
        .optional()
        .describe('Whether alert notifications use the custom URL'),
      previousTimeSeriesId: z
        .string()
        .nullable()
        .optional()
        .describe('Create-only second-latest time-series reference'),
      latestTimeSeriesId: z
        .string()
        .nullable()
        .optional()
        .describe('Create-only latest time-series reference')
    })
  )
  .output(
    z.object({
      alert: alertOutputSchema.optional().describe('Alert details'),
      alerts: z.array(alertOutputSchema).optional().describe('List of alerts'),
      count: z.number().optional().describe('Number of results returned')
    })
  )
  .handleInvocation(async ctx => {
    let client = new LookerClient({
      instanceUrl: ctx.config.instanceUrl,
      token: ctx.auth.token
    });

    let mapAppliedDashboardFilters = ():
      | LookerWriteAlertAppliedDashboardFilter[]
      | null
      | undefined => {
      if (
        ctx.input.appliedDashboardFilters === undefined ||
        ctx.input.appliedDashboardFilters === null
      ) {
        return ctx.input.appliedDashboardFilters;
      }
      return ctx.input.appliedDashboardFilters.map(filter => ({
        filter_title: filter.filterTitle,
        field_name: filter.fieldName,
        filter_value: filter.filterValue
      }));
    };

    let mapFieldFilters = () => {
      if (ctx.input.fieldFilters === undefined || ctx.input.fieldFilters === null) {
        return ctx.input.fieldFilters;
      }
      return ctx.input.fieldFilters.map(filter => ({
        field_name: filter.fieldName,
        field_value: filter.fieldValue,
        filter_value: filter.filterValue
      }));
    };

    if (
      ctx.input.comparisonType !== undefined &&
      !comparisonTypes.some(comparisonType => comparisonType === ctx.input.comparisonType)
    ) {
      throw validationError(
        `comparisonType must be one of: ${comparisonTypes.join(', ')}.`,
        'looker_alert_comparison_type_invalid'
      );
    }

    switch (ctx.input.action) {
      case 'list': {
        let alerts = await client.listAlerts({
          limit: ctx.input.limit,
          offset: ctx.input.offset,
          group_by: ctx.input.groupBy,
          disabled: ctx.input.disabled,
          frequency: ctx.input.frequency,
          condition_met: ctx.input.conditionMet,
          last_run_start: ctx.input.lastRunStart,
          last_run_end: ctx.input.lastRunEnd,
          all_owners: ctx.input.allOwners
        });
        if (!Array.isArray(alerts)) {
          throw validationError(
            'Looker returned an invalid alert search response.',
            'looker_alert_invalid_response'
          );
        }
        let mappedAlerts = alerts.map(alert => mapAlert(alert));
        return {
          output: { alerts: mappedAlerts, count: mappedAlerts.length },
          message: `Found **${mappedAlerts.length}** alert(s).`
        };
      }
      case 'get': {
        if (!ctx.input.alertId) {
          throw validationError(
            'alertId is required for get action.',
            'looker_alert_id_required'
          );
        }
        let alert = mapAlert(await client.getAlert(ctx.input.alertId));
        return {
          output: { alert },
          message: `Retrieved alert **${alertLabel(alert)}**`
        };
      }
      case 'create': {
        let hasDashboardElement = Boolean(ctx.input.dashboardElementId);
        let hasLookmlElement = Boolean(ctx.input.lookmlDashboardId && ctx.input.lookmlLinkId);
        if (!hasDashboardElement && !hasLookmlElement) {
          throw validationError(
            'Provide dashboardElementId, or both lookmlDashboardId and lookmlLinkId, for create action.',
            'looker_alert_dashboard_element_required'
          );
        }
        if (!ctx.input.comparisonType) {
          throw validationError(
            'comparisonType is required for create action.',
            'looker_alert_comparison_type_required'
          );
        }
        if (ctx.input.threshold === undefined) {
          throw validationError(
            'threshold is required for create action.',
            'looker_alert_threshold_required'
          );
        }
        if (!ctx.input.cron) {
          throw validationError(
            'cron is required for create action.',
            'looker_alert_cron_required'
          );
        }
        if (!ctx.input.fieldTitle || !ctx.input.fieldName) {
          throw validationError(
            'fieldTitle and fieldName are required for create action.',
            'looker_alert_field_required'
          );
        }
        if (!ctx.input.destinations) {
          throw validationError(
            'At least one destination is required for create action.',
            'looker_alert_destination_required'
          );
        }

        let alert = mapAlert(
          await client.createAlert({
            comparison_type: ctx.input.comparisonType,
            applied_dashboard_filters: mapAppliedDashboardFilters(),
            field: {
              title: ctx.input.fieldTitle,
              name: ctx.input.fieldName,
              filter: mapFieldFilters()
            },
            cron: ctx.input.cron,
            query_id: ctx.input.queryId,
            custom_url_base: ctx.input.customUrlBase,
            custom_url_params: ctx.input.customUrlParams,
            custom_url_label: ctx.input.customUrlLabel,
            show_custom_url: ctx.input.showCustomUrl,
            custom_title: ctx.input.customTitle,
            dashboard_element_id: ctx.input.dashboardElementId,
            lookml_dashboard_id: ctx.input.lookmlDashboardId,
            lookml_link_id: ctx.input.lookmlLinkId,
            destinations: mapDestinations(ctx.input.destinations, 'create'),
            threshold: ctx.input.threshold,
            description: ctx.input.description,
            owner_id: ctx.input.ownerId,
            is_disabled: ctx.input.isDisabled,
            disabled_reason: ctx.input.disabledReason,
            is_public: ctx.input.isPublic,
            enhancements: ctx.input.enhancements,
            time_series_condition_state:
              ctx.input.previousTimeSeriesId !== undefined ||
              ctx.input.latestTimeSeriesId !== undefined
                ? {
                    previous_time_series_id: ctx.input.previousTimeSeriesId,
                    latest_time_series_id: ctx.input.latestTimeSeriesId
                  }
                : undefined
          })
        );
        return {
          output: { alert },
          message: `Created alert **${alertLabel(alert)}**`
        };
      }
      case 'update': {
        if (!ctx.input.alertId) {
          throw validationError(
            'alertId is required for update action.',
            'looker_alert_id_required'
          );
        }
        if (
          ctx.input.previousTimeSeriesId !== undefined ||
          ctx.input.latestTimeSeriesId !== undefined
        ) {
          throw validationError(
            'previousTimeSeriesId and latestTimeSeriesId are create-only fields.',
            'looker_alert_time_series_state_create_only'
          );
        }

        let fullUpdateValues = [
          ctx.input.comparisonType,
          ctx.input.cron,
          ctx.input.queryId,
          ctx.input.customUrlBase,
          ctx.input.customUrlParams,
          ctx.input.customUrlLabel,
          ctx.input.showCustomUrl,
          ctx.input.customTitle,
          ctx.input.dashboardElementId,
          ctx.input.lookmlDashboardId,
          ctx.input.lookmlLinkId,
          ctx.input.description,
          ctx.input.destinations,
          ctx.input.fieldTitle,
          ctx.input.fieldName,
          ctx.input.fieldFilters,
          ctx.input.appliedDashboardFilters
        ];
        let patchValues = [
          ctx.input.ownerId,
          ctx.input.isDisabled,
          ctx.input.disabledReason,
          ctx.input.isPublic,
          ctx.input.threshold,
          ctx.input.enhancements
        ];
        let requiresFullUpdate = fullUpdateValues.some(value => value !== undefined);
        if (!requiresFullUpdate && !patchValues.some(value => value !== undefined)) {
          throw validationError(
            'Provide at least one alert field to update.',
            'looker_alert_update_required'
          );
        }

        let updated: LookerAlert;
        if (!requiresFullUpdate) {
          let patch: LookerAlertPatch = {};
          if (ctx.input.ownerId !== undefined) patch.owner_id = ctx.input.ownerId;
          if (ctx.input.isDisabled !== undefined) patch.is_disabled = ctx.input.isDisabled;
          if (ctx.input.disabledReason !== undefined)
            patch.disabled_reason = ctx.input.disabledReason;
          if (ctx.input.isPublic !== undefined) patch.is_public = ctx.input.isPublic;
          if (ctx.input.threshold !== undefined) patch.threshold = ctx.input.threshold;
          if (ctx.input.enhancements !== undefined)
            patch.enhancements = ctx.input.enhancements;
          updated = await client.patchAlert(ctx.input.alertId, patch);
        } else {
          let current = await client.getAlert(ctx.input.alertId);
          let comparisonType = ctx.input.comparisonType ?? current.comparison_type;
          let cron = ctx.input.cron ?? current.cron;
          let ownerId = ctx.input.ownerId ?? current.owner_id;
          let threshold = ctx.input.threshold ?? current.threshold;
          let destinations =
            ctx.input.destinations !== undefined
              ? mapDestinations(ctx.input.destinations, 'update')
              : current.destinations;
          let fieldTitle = ctx.input.fieldTitle ?? current.field?.title;
          let fieldName = ctx.input.fieldName ?? current.field?.name;

          if (!comparisonType || !cron || !ownerId || threshold === undefined) {
            throw validationError(
              'Looker did not return the fields required for a complete alert update.',
              'looker_alert_full_update_fields_missing'
            );
          }
          if (!destinations || destinations.length === 0 || !fieldTitle || !fieldName) {
            throw validationError(
              'Looker did not return the destinations or monitored field required for a complete alert update.',
              'looker_alert_full_update_fields_missing'
            );
          }

          let body: LookerFullUpdateAlert = {
            comparison_type: comparisonType,
            cron,
            destinations,
            field: {
              title: fieldTitle,
              name: fieldName,
              filter:
                ctx.input.fieldFilters !== undefined ? mapFieldFilters() : current.field.filter
            },
            owner_id: ownerId,
            threshold,
            applied_dashboard_filters:
              ctx.input.appliedDashboardFilters !== undefined
                ? mapAppliedDashboardFilters()
                : (current.applied_dashboard_filters?.map(filter => ({
                    filter_title: filter.filter_title,
                    field_name: filter.field_name,
                    filter_value: filter.filter_value
                  })) ?? current.applied_dashboard_filters),
            query_id: ctx.input.queryId !== undefined ? ctx.input.queryId : current.query_id,
            custom_url_base:
              ctx.input.customUrlBase !== undefined
                ? ctx.input.customUrlBase
                : current.custom_url_base,
            custom_url_params:
              ctx.input.customUrlParams !== undefined
                ? ctx.input.customUrlParams
                : current.custom_url_params,
            custom_url_label:
              ctx.input.customUrlLabel !== undefined
                ? ctx.input.customUrlLabel
                : current.custom_url_label,
            show_custom_url:
              ctx.input.showCustomUrl !== undefined
                ? ctx.input.showCustomUrl
                : current.show_custom_url,
            custom_title:
              ctx.input.customTitle !== undefined
                ? ctx.input.customTitle
                : current.custom_title,
            dashboard_element_id:
              ctx.input.dashboardElementId !== undefined
                ? ctx.input.dashboardElementId
                : current.dashboard_element_id,
            description:
              ctx.input.description !== undefined
                ? ctx.input.description
                : current.description,
            enhancements:
              ctx.input.enhancements !== undefined
                ? ctx.input.enhancements
                : current.enhancements,
            is_disabled:
              ctx.input.isDisabled !== undefined ? ctx.input.isDisabled : current.is_disabled,
            disabled_reason:
              ctx.input.disabledReason !== undefined
                ? ctx.input.disabledReason
                : current.disabled_reason,
            is_public:
              ctx.input.isPublic !== undefined ? ctx.input.isPublic : current.is_public,
            investigative_content_type: current.investigative_content_type,
            investigative_content_id: current.investigative_content_id,
            lookml_dashboard_id:
              ctx.input.lookmlDashboardId !== undefined
                ? ctx.input.lookmlDashboardId
                : current.lookml_dashboard_id,
            lookml_link_id:
              ctx.input.lookmlLinkId !== undefined
                ? ctx.input.lookmlLinkId
                : current.lookml_link_id
          };
          updated = await client.updateAlert(ctx.input.alertId, body);
        }

        let alert = mapAlert(updated);
        return {
          output: { alert },
          message: `Updated alert **${alertLabel(alert)}**`
        };
      }
      case 'delete': {
        if (!ctx.input.alertId) {
          throw validationError(
            'alertId is required for delete action.',
            'looker_alert_id_required'
          );
        }
        let alert = await client.getAlert(ctx.input.alertId);
        await client.deleteAlert(ctx.input.alertId);
        let deletedAlert = mapAlert(alert, true);
        return {
          output: { alert: deletedAlert },
          message: `Deleted alert **${alertLabel(deletedAlert)}**`
        };
      }
    }
  })
  .build();
