import { Slate } from 'slates';
import { spec } from './spec';
import {
  configureArchiving,
  createBoard,
  createExclusionRule,
  createPresetAlert,
  createView,
  deleteArchiveConfig,
  deleteBoard,
  deleteExclusionRule,
  deletePresetAlert,
  deleteView,
  exportLogs,
  getArchiveConfig,
  getIngestionStatus,
  getUsage,
  ingestLogs,
  listBoards,
  listExclusionRules,
  listPresetAlerts,
  listViews,
  resumeIngestion,
  searchLogs,
  suspendIngestion,
  updateExclusionRule,
  updatePresetAlert,
  updateView
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    ingestLogs,
    searchLogs,
    exportLogs,
    listViews,
    createView,
    updateView,
    deleteView,
    listPresetAlerts,
    createPresetAlert,
    updatePresetAlert,
    deletePresetAlert,
    listExclusionRules,
    createExclusionRule,
    updateExclusionRule,
    deleteExclusionRule,
    listBoards,
    createBoard,
    deleteBoard,
    getUsage,
    getIngestionStatus,
    suspendIngestion,
    resumeIngestion,
    getArchiveConfig,
    configureArchiving,
    deleteArchiveConfig
  ],
  triggers: []
});
