import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  createApplication,
  createEndpoint,
  createEventType,
  deleteApplication,
  deleteEndpoint,
  deleteEventType,
  expungeMessageContent,
  getApplication,
  getEndpoint,
  getEndpointHeaders,
  getEndpointSecret,
  getEndpointStats,
  getEndpointTransformation,
  getEventType,
  getMessage,
  getPortalAccess,
  importEventTypesFromOpenApi,
  listApplications,
  listAttemptsByEndpoint,
  listAttemptsByMessage,
  listEndpoints,
  listEventTypes,
  listMessages,
  precheckMessage,
  recoverEndpoint,
  resendMessage,
  rotateEndpointSecret,
  sendMessage,
  updateApplication,
  updateEndpoint,
  updateEndpointHeaders,
  updateEndpointTransformation,
  updateEventType
} from './tools';
import { operationalWebhooksTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listApplications,
    createApplication,
    getApplication,
    updateApplication,
    deleteApplication,
    sendMessage,
    listMessages,
    getMessage,
    precheckMessage,
    expungeMessageContent,
    getEndpoint,
    createEndpoint,
    listEndpoints,
    updateEndpoint,
    deleteEndpoint,
    getEndpointHeaders,
    updateEndpointHeaders,
    getEndpointSecret,
    rotateEndpointSecret,
    getEndpointTransformation,
    updateEndpointTransformation,
    listEventTypes,
    createEventType,
    getEventType,
    updateEventType,
    importEventTypesFromOpenApi,
    deleteEventType,
    listAttemptsByMessage,
    listAttemptsByEndpoint,
    resendMessage,
    recoverEndpoint,
    getPortalAccess,
    getEndpointStats
  ],
  triggers: [operationalWebhooksTrigger]
});
