import { SlateTool } from 'slates';
import { z } from 'zod';
import { AnthropicClient } from '../lib/client';
import { anthropicServiceError } from '../lib/errors';
import { spec } from '../spec';

let fileOutputSchema = z.object({
  fileId: z.string().describe('Anthropic file ID'),
  type: z.string().optional().describe('Object type'),
  filename: z.string().optional().describe('Original filename'),
  mimeType: z.string().optional().describe('MIME type'),
  sizeBytes: z.number().optional().describe('File size in bytes'),
  createdAt: z.string().optional().describe('RFC 3339 creation timestamp'),
  downloadable: z
    .boolean()
    .optional()
    .describe('Whether this file can be downloaded through the Files API')
});

let fileContentOutputSchema = z.object({
  fileId: z.string().describe('Anthropic file ID'),
  contentBase64: z.string().describe('Downloaded file content encoded as base64'),
  contentType: z.string().optional().describe('Downloaded response content type'),
  sizeBytes: z.number().describe('Downloaded content size in bytes')
});

export let manageFiles = SlateTool.create(spec, {
  name: 'Manage Files',
  key: 'manage_files',
  description: `Upload, list, retrieve metadata for, download, or delete Anthropic Files API files. Uploaded files can be referenced from Messages requests by file ID; generated downloadable files can be retrieved as base64 content.`,
  instructions: [
    'For "create": provide filename and contentBase64; mimeType defaults to application/octet-stream.',
    'For "list": optionally provide limit, afterId, or beforeId.',
    'For "get", "download", and "delete": provide fileId.',
    'Uploaded files are not always downloadable; Anthropic only allows downloading files that are marked downloadable, such as files generated by code execution.'
  ],
  tags: {
    destructive: true,
    readOnly: false
  }
})
  .input(
    z.object({
      action: z
        .enum(['create', 'list', 'get', 'download', 'delete'])
        .describe('Operation to perform'),
      fileId: z
        .string()
        .optional()
        .describe('File ID (required for get, download, and delete)'),
      filename: z.string().optional().describe('Filename for create'),
      contentBase64: z.string().optional().describe('Base64 encoded file content for create'),
      mimeType: z
        .string()
        .optional()
        .describe('MIME type for create, e.g. text/plain or application/pdf'),
      limit: z.number().optional().describe('Max files to return for list'),
      afterId: z.string().optional().describe('Pagination cursor after this file ID'),
      beforeId: z.string().optional().describe('Pagination cursor before this file ID')
    })
  )
  .output(
    z.object({
      file: fileOutputSchema.optional().describe('File metadata'),
      files: z.array(fileOutputSchema).optional().describe('List of files'),
      fileContent: fileContentOutputSchema.optional().describe('Downloaded file content'),
      deletedFile: z
        .object({
          fileId: z.string(),
          type: z.string().optional()
        })
        .optional()
        .describe('Deleted file result'),
      hasMore: z.boolean().optional().describe('Whether more list results are available'),
      firstId: z.string().optional().describe('First file ID in the page'),
      lastId: z.string().optional().describe('Last file ID in the page'),
      success: z.boolean().optional().describe('Whether a delete operation succeeded')
    })
  )
  .handleInvocation(async ctx => {
    let client = new AnthropicClient({
      token: ctx.auth.token,
      apiVersion: ctx.config.apiVersion
    });

    switch (ctx.input.action) {
      case 'create': {
        if (!ctx.input.filename || !ctx.input.contentBase64) {
          throw anthropicServiceError('filename and contentBase64 are required for "create"');
        }
        let file = await client.createFile({
          filename: ctx.input.filename,
          contentBase64: ctx.input.contentBase64,
          mimeType: ctx.input.mimeType
        });
        return {
          output: { file },
          message: `Uploaded file **${file.filename ?? ctx.input.filename}** as **${file.fileId}**.`
        };
      }
      case 'list': {
        let result = await client.listFiles({
          limit: ctx.input.limit,
          afterId: ctx.input.afterId,
          beforeId: ctx.input.beforeId
        });
        return {
          output: {
            files: result.files,
            hasMore: result.hasMore,
            firstId: result.firstId,
            lastId: result.lastId
          },
          message: `Found **${result.files.length}** file(s).${result.hasMore ? ' More files are available with pagination.' : ''}`
        };
      }
      case 'get': {
        if (!ctx.input.fileId) {
          throw anthropicServiceError('fileId is required for "get"');
        }
        let file = await client.getFile(ctx.input.fileId);
        return {
          output: { file },
          message: `Retrieved metadata for file **${file.fileId}**.`
        };
      }
      case 'download': {
        if (!ctx.input.fileId) {
          throw anthropicServiceError('fileId is required for "download"');
        }
        let fileContent = await client.downloadFile(ctx.input.fileId);
        return {
          output: { fileContent },
          message: `Downloaded file **${fileContent.fileId}** (${fileContent.sizeBytes} bytes).`
        };
      }
      case 'delete': {
        if (!ctx.input.fileId) {
          throw anthropicServiceError('fileId is required for "delete"');
        }
        let deletedFile = await client.deleteFile(ctx.input.fileId);
        return {
          output: { deletedFile, success: true },
          message: `Deleted file **${deletedFile.fileId}**.`
        };
      }
    }
  })
  .build();
