import { Slate } from 'slates';
import { spec } from './spec';
import {
  createChannel,
  createInvite,
  createRole,
  createServer,
  createWebhook,
  deleteChannel,
  deleteEmoji,
  deleteInvite,
  deleteMessages,
  deleteRole,
  deleteServer,
  editChannel,
  editMember,
  editMessage,
  editRole,
  editServer,
  executeWebhook,
  fetchChannel,
  fetchInvite,
  fetchMembers,
  fetchMessages,
  fetchServer,
  fetchServerEmoji,
  fetchServerInvites,
  fetchUser,
  fetchWebhooks,
  kickMember,
  manageBan,
  manageReactions,
  openDM,
  pinMessage,
  searchMessages,
  sendMessage
} from './tools';
import { channelMessage, inboundWebhook, newMessage, serverMemberChanges } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    sendMessage,
    editMessage,
    deleteMessages,
    fetchMessages,
    searchMessages,
    manageReactions,
    pinMessage,
    createServer,
    fetchServer,
    editServer,
    deleteServer,
    createChannel,
    fetchChannel,
    editChannel,
    deleteChannel,
    fetchMembers,
    editMember,
    kickMember,
    manageBan,
    fetchUser,
    openDM,
    createRole,
    editRole,
    deleteRole,
    createWebhook,
    fetchWebhooks,
    executeWebhook,
    fetchServerEmoji,
    deleteEmoji,
    createInvite,
    fetchInvite,
    deleteInvite,
    fetchServerInvites
  ],
  triggers: [inboundWebhook, newMessage, channelMessage, serverMemberChanges]
});
