import { Slate } from 'slates';
import { spec } from './spec';
import {
  convertLead,
  createCompany,
  createLead,
  createOpportunity,
  createPerson,
  createProject,
  createRelatedItem,
  createTask,
  deleteCompany,
  deleteLead,
  deleteOpportunity,
  deletePerson,
  deleteProject,
  deleteRelatedItem,
  deleteTask,
  getCompany,
  getLead,
  getOpportunity,
  getPerson,
  getProject,
  getRelatedItems,
  getTask,
  listActivityTypes,
  listContactTypes,
  listCustomerSources,
  listCustomFieldDefinitions,
  listLossReasons,
  listPipelines,
  listUsers,
  logActivity,
  searchActivities,
  searchCompanies,
  searchLeads,
  searchOpportunities,
  searchPeople,
  searchProjects,
  searchTasks,
  updateCompany,
  updateLead,
  updateOpportunity,
  updatePerson,
  updateProject,
  updateTask
} from './tools';
import { entityChange } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createPerson,
    getPerson,
    updatePerson,
    deletePerson,
    searchPeople,
    createCompany,
    getCompany,
    updateCompany,
    deleteCompany,
    searchCompanies,
    createLead,
    getLead,
    updateLead,
    deleteLead,
    searchLeads,
    convertLead,
    createOpportunity,
    getOpportunity,
    updateOpportunity,
    deleteOpportunity,
    searchOpportunities,
    createTask,
    getTask,
    updateTask,
    deleteTask,
    searchTasks,
    createProject,
    getProject,
    updateProject,
    deleteProject,
    searchProjects,
    logActivity,
    searchActivities,
    listActivityTypes,
    listPipelines,
    listCustomFieldDefinitions,
    listContactTypes,
    listCustomerSources,
    listLossReasons,
    listUsers,
    getRelatedItems,
    createRelatedItem,
    deleteRelatedItem
  ],
  triggers: [entityChange]
});
