import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

export let listNotifications = SlateTool.create(spec, {
  name: 'List Notifications',
  key: 'list_notifications',
  description: `Retrieves change notifications generated by monitors. Can be filtered by a specific monitor and/or date range.
Returns the current and previous content values along with alert metadata.`,
  instructions: [
    'Use ISO 8601 format for date parameters (e.g., "2024-01-15T00:00:00Z").',
    'Use continuationToken from a previous response to paginate through large result sets.'
  ],
  tags: {
    destructive: false,
    readOnly: true
  }
})
  .input(
    z.object({
      wachetId: z
        .string()
        .optional()
        .describe('Filter notifications to a specific monitor ID'),
      from: z.string().optional().describe('Start of date range filter (ISO 8601)'),
      to: z.string().optional().describe('End of date range filter (ISO 8601)'),
      count: z.number().optional().describe('Maximum number of notifications to return'),
      continuationToken: z
        .string()
        .optional()
        .describe('Pagination token from a previous response'),
      html: z.boolean().optional().describe('Whether to return HTML formatted alert content')
    })
  )
  .output(
    z.object({
      notifications: z
        .array(
          z.object({
            notificationId: z.string().describe('Notification ID'),
            alertType: z.string().describe('Alert type that triggered this notification'),
            current: z.string().optional().describe('Current content value'),
            comparand: z.string().optional().describe('Previous content value for comparison'),
            htmlContent: z
              .string()
              .optional()
              .describe('HTML formatted content (if html=true)'),
            error: z.string().optional().describe('Error message if applicable'),
            timestamp: z.string().describe('When the notification was generated'),
            serverTime: z.string().describe('Server timestamp'),
            wachetId: z.string().describe('Monitor that generated this notification'),
            wachetName: z.string().optional().describe('Name of the monitor'),
            url: z.string().optional().describe('Monitored URL')
          })
        )
        .describe('List of notifications'),
      continuationToken: z
        .string()
        .optional()
        .describe('Token to fetch the next page of results')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({ token: ctx.auth.token });

    let response = await client.listNotifications({
      taskId: ctx.input.wachetId,
      from: ctx.input.from,
      to: ctx.input.to,
      count: ctx.input.count,
      continuationToken: ctx.input.continuationToken,
      html: ctx.input.html
    });

    let notifications = (response.data ?? []).map(n => ({
      notificationId: n.id,
      alertType: n.type,
      current: n.current,
      comparand: n.comparand,
      htmlContent: n.html,
      error: n.error,
      timestamp: n.timestamp,
      serverTime: n.serverTime,
      wachetId: n.taskId,
      wachetName: n.taskName,
      url: n.url
    }));

    return {
      output: {
        notifications,
        continuationToken: response.continuationToken
      },
      message: `Retrieved **${notifications.length}** notification(s).${response.continuationToken ? ' More results available with continuation token.' : ''}`
    };
  })
  .build();
