import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCohort,
  createOutcome,
  createPersonaSet,
  createScope,
  createTarget,
  deleteCohort,
  deleteConnection,
  deleteDataset,
  deleteOutcome,
  getAccount,
  getCohort,
  getConnection,
  getDataset,
  getDependencyGraph,
  getOutcome,
  getPersonaSet,
  getRecommender,
  getScope,
  getStream,
  getTarget,
  listCohorts,
  listConnections,
  listDatasets,
  listOutcomes,
  listPersonaSets,
  listRecommenders,
  listScopes,
  listStreams,
  listTargets,
  listTraits,
  lookupPrediction,
  updateCohort
} from './tools';
import { resourceEvent } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listCohorts,
    getCohort,
    createCohort,
    updateCohort,
    deleteCohort,
    listOutcomes,
    getOutcome,
    createOutcome,
    deleteOutcome,
    listScopes,
    getScope,
    createScope,
    listTargets,
    getTarget,
    createTarget,
    listDatasets,
    getDataset,
    deleteDataset,
    listConnections,
    getConnection,
    deleteConnection,
    listPersonaSets,
    getPersonaSet,
    createPersonaSet,
    listRecommenders,
    getRecommender,
    lookupPrediction,
    listTraits,
    listStreams,
    getStream,
    getAccount,
    getDependencyGraph
  ],
  triggers: [resourceEvent]
});
