import { Slate } from 'slates';
import { spec } from './spec';
import {
  addSenderDomain,
  addSingleSender,
  addSmtpUser,
  addSuppressions,
  closeSubaccount,
  createSubaccount,
  createTemplate,
  createWebhook,
  deleteTemplate,
  editSmtpUser,
  editSubaccount,
  editTemplate,
  editWebhook,
  getEmailBounces,
  getEmailHistory,
  getEmailStatistics,
  listSenderDomains,
  listSingleSenders,
  listSmtpUsers,
  listSubaccounts,
  listWebhooks,
  removeSenderDomain,
  removeSingleSender,
  removeSmtpUser,
  removeSuppressions,
  removeWebhook,
  reopenSubaccount,
  searchActivity,
  searchEmails,
  searchTemplates,
  sendEmail,
  sendMimeEmail,
  sendSms,
  updateAllowedSenders,
  verifySenderDomain,
  viewAllowedSenders,
  viewSuppressions,
  viewTemplate
} from './tools';
import { emailActivityTrigger, emailEventsTrigger, smsEventsTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    sendEmail,
    sendMimeEmail,
    searchEmails,
    sendSms,
    createTemplate,
    editTemplate,
    deleteTemplate,
    searchTemplates,
    viewTemplate,
    getEmailStatistics,
    getEmailBounces,
    getEmailHistory,
    searchActivity,
    listSenderDomains,
    addSenderDomain,
    removeSenderDomain,
    verifySenderDomain,
    listSingleSenders,
    addSingleSender,
    removeSingleSender,
    viewSuppressions,
    addSuppressions,
    removeSuppressions,
    listSmtpUsers,
    addSmtpUser,
    editSmtpUser,
    removeSmtpUser,
    listWebhooks,
    createWebhook,
    editWebhook,
    removeWebhook,
    viewAllowedSenders,
    updateAllowedSenders,
    listSubaccounts,
    createSubaccount,
    editSubaccount,
    closeSubaccount,
    reopenSubaccount
  ],
  triggers: [emailEventsTrigger, smsEventsTrigger, emailActivityTrigger]
});
