import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  createDatabase,
  createDomain,
  createDroplet,
  createKubernetesCluster,
  createVolume,
  deleteApp,
  deleteDatabase,
  deleteDroplet,
  deleteKubernetesCluster,
  deleteVolume,
  deployApp,
  getAccount,
  getApp,
  getBilling,
  getKubeconfig,
  listAlertPolicies,
  listApps,
  listCdnEndpoints,
  listCertificates,
  listDatabases,
  listDomains,
  listDroplets,
  listFunctionNamespaces,
  listFunctionTriggers,
  listImages,
  listKubernetesClusters,
  listLoadBalancers,
  listProjects,
  listRegions,
  listSizes,
  listSnapshots,
  listVolumes,
  manageContainerRegistry,
  manageDatabaseUsers,
  manageDNSRecords,
  manageFirewall,
  manageNodePools,
  manageProject,
  manageProjectResources,
  manageReservedIPs,
  manageSSHKeys,
  manageTags,
  manageUptimeChecks,
  manageVolumeAttachment,
  manageVPC,
  performDropletAction
} from './tools';

import { inboundWebhook } from './triggers/inbound-webhook';

export let provider = Slate.create({
  spec,
  tools: [
    listDroplets,
    createDroplet,
    deleteDroplet,
    performDropletAction,
    listDatabases,
    createDatabase,
    deleteDatabase,
    manageDatabaseUsers,
    listDomains,
    createDomain,
    manageDNSRecords,
    listKubernetesClusters,
    createKubernetesCluster,
    deleteKubernetesCluster,
    getKubeconfig,
    manageNodePools,
    listApps,
    getApp,
    deployApp,
    deleteApp,
    listVolumes,
    createVolume,
    manageVolumeAttachment,
    deleteVolume,
    listLoadBalancers,
    manageFirewall,
    manageVPC,
    manageReservedIPs,
    listProjects,
    manageProject,
    manageProjectResources,
    manageSSHKeys,
    listAlertPolicies,
    manageUptimeChecks,
    getAccount,
    getBilling,
    listRegions,
    listSizes,
    listSnapshots,
    listImages,
    manageContainerRegistry,
    manageTags,
    listFunctionNamespaces,
    listFunctionTriggers,
    listCdnEndpoints,
    listCertificates
  ],
  triggers: [inboundWebhook]
});
