import { SlateDefaultPollingIntervalSeconds, SlateTrigger } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

let positionSchema = z
  .object({
    latitude: z.number().optional(),
    longitude: z.number().optional(),
    accuracy: z.number().optional(),
    speed: z.number().optional(),
    heading: z.number().optional(),
    distanceToLocation: z.number().optional().describe('Distance to order location in meters')
  })
  .optional();

export let mobileEvents = SlateTrigger.create(spec, {
  name: 'Mobile Events',
  key: 'mobile_events',
  description:
    'Real-time events generated by drivers through the OptimoRoute mobile app, including duty changes, route starts/ends, order service starts, completions, failures, and rejections.'
})
  .input(
    z.object({
      eventType: z.string().describe('Event type'),
      eventKey: z.string().describe('Unique event key for deduplication'),
      unixTimestamp: z.number().describe('Event timestamp (seconds since epoch)'),
      utcTime: z.string().describe('UTC datetime'),
      localTime: z.string().describe('Local datetime'),
      driverName: z.string().optional(),
      driverSerial: z.string().optional(),
      driverExternalId: z.string().optional(),
      orderNo: z.string().optional(),
      orderId: z.string().optional(),
      position: positionSchema,
      plannedStartTime: z.record(z.string(), z.unknown()).optional()
    })
  )
  .output(
    z.object({
      eventType: z
        .string()
        .describe(
          'on_duty, off_duty, start_route, end_route, start_service, success, failed, rejected, start_time_changed'
        ),
      unixTimestamp: z.number().describe('Event timestamp'),
      utcTime: z.string().describe('UTC datetime'),
      localTime: z.string().describe('Local datetime'),
      driverName: z.string().optional(),
      driverSerial: z.string().optional(),
      driverExternalId: z.string().optional(),
      orderNo: z.string().optional(),
      orderId: z.string().optional(),
      latitude: z.number().optional(),
      longitude: z.number().optional(),
      distanceToLocation: z.number().optional(),
      plannedStartTime: z.record(z.string(), z.unknown()).optional()
    })
  )
  .polling({
    options: {
      intervalInSeconds: SlateDefaultPollingIntervalSeconds
    },

    pollEvents: async ctx => {
      let client = new Client({ token: ctx.auth.token });

      let afterTag = (ctx.state as Record<string, unknown> | undefined)?.afterTag as
        | string
        | undefined;

      let result = await client.getEvents(afterTag);

      if (!result.success || !result.events || result.events.length === 0) {
        return {
          inputs: [],
          updatedState: {
            afterTag: result.tag || afterTag
          }
        };
      }

      let inputs = result.events.map((event: Record<string, unknown>, index: number) => ({
        eventType: event.event as string,
        eventKey: `${event.event}-${event.unixTimestamp}-${event.driverSerial || event.driverExternalId || ''}-${event.orderNo || event.orderId || ''}-${index}`,
        unixTimestamp: event.unixTimestamp as number,
        utcTime: event.utcTime as string,
        localTime: event.localTime as string,
        driverName: event.driverName as string | undefined,
        driverSerial: event.driverSerial as string | undefined,
        driverExternalId: event.driverExternalId as string | undefined,
        orderNo: event.orderNo as string | undefined,
        orderId: event.orderId as string | undefined,
        position: event.position as Record<string, unknown> | undefined,
        plannedStartTime: event.plannedStartTime as Record<string, unknown> | undefined
      }));

      return {
        inputs,
        updatedState: {
          afterTag: result.tag
        }
      };
    },

    handleEvent: async ctx => {
      let pos = ctx.input.position as Record<string, unknown> | undefined;

      return {
        type: `driver.${ctx.input.eventType}`,
        id: ctx.input.eventKey,
        output: {
          eventType: ctx.input.eventType,
          unixTimestamp: ctx.input.unixTimestamp,
          utcTime: ctx.input.utcTime,
          localTime: ctx.input.localTime,
          driverName: ctx.input.driverName,
          driverSerial: ctx.input.driverSerial,
          driverExternalId: ctx.input.driverExternalId,
          orderNo: ctx.input.orderNo,
          orderId: ctx.input.orderId,
          latitude: pos?.latitude as number | undefined,
          longitude: pos?.longitude as number | undefined,
          distanceToLocation: pos?.distanceToLocation as number | undefined,
          plannedStartTime: ctx.input.plannedStartTime
        }
      };
    }
  })
  .build();
