import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAppointment,
  createContact,
  createContactPerson,
  createCrewAvailability,
  createProject,
  createProjectRequest,
  createStockMovement,
  createSubproject,
  deleteAppointment,
  deleteContact,
  deleteContactPerson,
  deleteCost,
  deleteProjectRequest,
  getEquipment,
  getInvoice,
  getProject,
  listContacts,
  listContracts,
  listCosts,
  listCrew,
  listCrewAvailability,
  listEquipment,
  listInvoices,
  listProjects,
  listQuotes,
  listStockMovements,
  listSubrentals,
  updateAppointment,
  updateContact,
  updateContactPerson,
  updateCost,
  updateProjectRequest
} from './tools';
import { rentmanEvent } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listProjects,
    getProject,
    createProject,
    createSubproject,
    listContacts,
    createContact,
    updateContact,
    deleteContact,
    createContactPerson,
    updateContactPerson,
    deleteContactPerson,
    listEquipment,
    getEquipment,
    listCrew,
    createCrewAvailability,
    listCrewAvailability,
    listInvoices,
    getInvoice,
    listQuotes,
    listContracts,
    listSubrentals,
    createAppointment,
    updateAppointment,
    deleteAppointment,
    createProjectRequest,
    updateProjectRequest,
    deleteProjectRequest,
    createStockMovement,
    listStockMovements,
    listCosts,
    updateCost,
    deleteCost
  ],
  triggers: [rentmanEvent]
});
