import { Slate } from 'slates';
import { spec } from './spec';
import {
  backupDatabase,
  createAclRole,
  createAclRule,
  createAclUser,
  createCloudAccount,
  createDatabase,
  createSubscription,
  deleteAclRole,
  deleteAclRule,
  deleteAclUser,
  deleteCloudAccount,
  deleteDatabase,
  deleteSubscription,
  deleteUser,
  getDatabase,
  getLogs,
  getSubscription,
  getTask,
  importDatabase,
  listAclRoles,
  listAclRules,
  listAclUsers,
  listCloudAccounts,
  listDatabases,
  listEssentialsPlans,
  listPaymentMethods,
  listSubscriptions,
  listTasks,
  listUsers,
  updateAclRole,
  updateAclRule,
  updateAclUser,
  updateCloudAccount,
  updateDatabase,
  updateSubscription,
  updateUser
} from './tools';

import { inboundWebhook } from './triggers/inbound-webhook';

export let provider = Slate.create({
  spec,
  tools: [
    listSubscriptions,
    getSubscription,
    createSubscription,
    updateSubscription,
    deleteSubscription,
    listDatabases,
    getDatabase,
    createDatabase,
    updateDatabase,
    deleteDatabase,
    backupDatabase,
    importDatabase,
    listAclRules,
    createAclRule,
    updateAclRule,
    deleteAclRule,
    listAclRoles,
    createAclRole,
    updateAclRole,
    deleteAclRole,
    listAclUsers,
    createAclUser,
    updateAclUser,
    deleteAclUser,
    listUsers,
    updateUser,
    deleteUser,
    listCloudAccounts,
    createCloudAccount,
    updateCloudAccount,
    deleteCloudAccount,
    getTask,
    listTasks,
    getLogs,
    listPaymentMethods,
    listEssentialsPlans
  ],
  triggers: [inboundWebhook]
});
