import { Slate } from 'slates';
import { spec } from './spec';

import {
  createBill,
  createContact,
  createEstimate,
  createExpense,
  createInvoice,
  createProject,
  createTask,
  createTimeslip,
  deleteContact,
  deleteExpense,
  deleteInvoice,
  deleteProject,
  deleteTimeslip,
  emailInvoice,
  getBalanceSheet,
  getCompany,
  getContact,
  getInvoice,
  getProfitAndLoss,
  getTrialBalance,
  listBankAccounts,
  listBankTransactions,
  listBills,
  listCategories,
  listContacts,
  listCreditNotes,
  listEstimates,
  listExpenses,
  listInvoices,
  listProjects,
  listTasks,
  listTimeslips,
  listUsers,
  updateContact,
  updateExpense,
  updateInvoice,
  updateProject,
  updateTimeslip
} from './tools';

import {
  billChanges,
  contactChanges,
  expenseChanges,
  inboundWebhook,
  invoiceChanges,
  projectChanges
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listContacts,
    getContact,
    createContact,
    updateContact,
    deleteContact,
    listInvoices,
    getInvoice,
    createInvoice,
    updateInvoice,
    deleteInvoice,
    emailInvoice,
    listExpenses,
    createExpense,
    updateExpense,
    deleteExpense,
    listProjects,
    createProject,
    updateProject,
    deleteProject,
    listTimeslips,
    createTimeslip,
    updateTimeslip,
    deleteTimeslip,
    listBankAccounts,
    listBankTransactions,
    listBills,
    createBill,
    listEstimates,
    createEstimate,
    listTasks,
    createTask,
    listCreditNotes,
    getProfitAndLoss,
    getBalanceSheet,
    getTrialBalance,
    getCompany,
    listUsers,
    listCategories
  ],
  triggers: [
    inboundWebhook,
    invoiceChanges,
    contactChanges,
    expenseChanges,
    billChanges,
    projectChanges
  ]
});
