import { Slate } from 'slates';
import { spec } from './spec';
import {
  addSubscriberToForm,
  createSubscriber,
  getAccount,
  getAccountStats,
  getBroadcastLinkClicks,
  getBroadcastStats,
  getSubscriber,
  getSubscriberStats,
  listBroadcastStats,
  listEmailTemplates,
  listFormSubscribers,
  listForms,
  listSegments,
  listSubscribers,
  listSubscriberTags,
  listTagSubscribers,
  manageBroadcasts,
  manageCustomFields,
  managePosts,
  managePurchases,
  manageSequenceEmails,
  manageSequences,
  manageSnippets,
  manageTags,
  tagSubscriber,
  unsubscribe,
  updateSubscriber
} from './tools';
import { formSubscribeEvent, purchaseEvent, subscriberEvent, tagEvent } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    getAccount,
    getAccountStats,
    listSubscribers,
    getSubscriber,
    createSubscriber,
    updateSubscriber,
    unsubscribe,
    getSubscriberStats,
    listSubscriberTags,
    manageTags,
    tagSubscriber,
    listTagSubscribers,
    manageCustomFields,
    listForms,
    listFormSubscribers,
    addSubscriberToForm,
    manageBroadcasts,
    getBroadcastStats,
    listBroadcastStats,
    getBroadcastLinkClicks,
    manageSequences,
    manageSequenceEmails,
    listSegments,
    managePurchases,
    listEmailTemplates,
    managePosts,
    manageSnippets
  ],
  triggers: [subscriberEvent, tagEvent, purchaseEvent, formSubscribeEvent]
});
