import { Slate } from 'slates';
import { spec } from './spec';
import {
  addToLiveMeeting,
  askFred,
  continueAskFredThread,
  createLiveActionItem,
  createLiveSoundbite,
  createSoundbite,
  deleteAskFredThread,
  deleteTranscript,
  getAiApps,
  getAnalytics,
  getAskFredThread,
  getChannel,
  getSoundbite,
  getSummary,
  getTranscript,
  getUser,
  listActiveMeetings,
  listAskFredThreads,
  listChannels,
  listContacts,
  listLiveActionItems,
  listSoundbites,
  listTranscripts,
  listUserGroups,
  listUsers,
  moveMeetings,
  revokeMeetingAccess,
  setUserRole,
  shareMeeting,
  updateMeetingState,
  updateTranscript,
  uploadAudio
} from './tools';
import { transcriptionCompleted } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listTranscripts,
    getTranscript,
    getSummary,
    updateTranscript,
    deleteTranscript,
    uploadAudio,
    getUser,
    listUsers,
    listUserGroups,
    listContacts,
    setUserRole,
    addToLiveMeeting,
    listActiveMeetings,
    updateMeetingState,
    createLiveActionItem,
    createLiveSoundbite,
    listLiveActionItems,
    createSoundbite,
    listSoundbites,
    getSoundbite,
    listChannels,
    getChannel,
    moveMeetings,
    askFred,
    continueAskFredThread,
    listAskFredThreads,
    getAskFredThread,
    deleteAskFredThread,
    shareMeeting,
    revokeMeetingAccess,
    getAiApps,
    getAnalytics
  ],
  triggers: [transcriptionCompleted]
});
