import { Slate } from 'slates';
import { spec } from './spec';
import {
  analyzeTextTool,
  createKeyTool,
  createTemporaryTokenTool,
  deleteInvitationTool,
  deleteKeyTool,
  deleteProjectTool,
  getBalancesTool,
  getBalanceTool,
  getBillingBreakdownTool,
  getBillingFieldsTool,
  getKeyTool,
  getMemberScopesTool,
  getModelTool,
  getProjectModelTool,
  getProjectRequestTool,
  getProjectTool,
  getUsageBreakdownTool,
  getUsageFieldsTool,
  getUsageTool,
  listInvitationsTool,
  listKeysTool,
  listMembersTool,
  listModelsTool,
  listProjectModelsTool,
  listProjectRequestsTool,
  listProjectsTool,
  listPurchasesTool,
  removeMemberTool,
  sendInvitationTool,
  textToSpeechTool,
  transcribeAudioTool,
  updateMemberScopesTool,
  updateProjectTool
} from './tools';
import { transcriptionCallbackTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    transcribeAudioTool,
    textToSpeechTool,
    analyzeTextTool,
    createTemporaryTokenTool,
    listProjectsTool,
    getProjectTool,
    updateProjectTool,
    deleteProjectTool,
    listMembersTool,
    getMemberScopesTool,
    removeMemberTool,
    updateMemberScopesTool,
    listInvitationsTool,
    sendInvitationTool,
    deleteInvitationTool,
    listKeysTool,
    getKeyTool,
    createKeyTool,
    deleteKeyTool,
    listModelsTool,
    getModelTool,
    listProjectModelsTool,
    getProjectModelTool,
    getUsageTool,
    getUsageFieldsTool,
    getUsageBreakdownTool,
    listProjectRequestsTool,
    getProjectRequestTool,
    getBalancesTool,
    getBalanceTool,
    getBillingBreakdownTool,
    getBillingFieldsTool,
    listPurchasesTool
  ],
  triggers: [transcriptionCallbackTrigger]
});
