import { Slate } from 'slates';
import { spec } from './spec';
import {
  cancelDeploymentTool,
  createDomainTool,
  createEnvironmentTool,
  createProjectTool,
  createServiceTool,
  createVolumeTool,
  deleteDomainTool,
  deleteEnvironmentTool,
  deleteProjectTool,
  deleteServiceTool,
  deleteVariableTool,
  deleteVolumeTool,
  getDeploymentLogsTool,
  getDeploymentTool,
  getDomainsTool,
  getEnvironmentTool,
  getProjectTool,
  getServiceTool,
  getVariablesTool,
  listDeploymentsTool,
  listEnvironmentsTool,
  listProjectsTool,
  listVolumesTool,
  rollbackDeploymentTool,
  setVariablesTool,
  triggerDeploymentTool,
  updateProjectTool,
  updateServiceTool,
  updateVolumeTool
} from './tools';
import { projectWebhookTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listProjectsTool,
    getProjectTool,
    createProjectTool,
    updateProjectTool,
    deleteProjectTool,
    getServiceTool,
    createServiceTool,
    updateServiceTool,
    deleteServiceTool,
    listDeploymentsTool,
    getDeploymentTool,
    triggerDeploymentTool,
    rollbackDeploymentTool,
    cancelDeploymentTool,
    getDeploymentLogsTool,
    listEnvironmentsTool,
    getEnvironmentTool,
    createEnvironmentTool,
    deleteEnvironmentTool,
    getVariablesTool,
    setVariablesTool,
    deleteVariableTool,
    getDomainsTool,
    createDomainTool,
    deleteDomainTool,
    listVolumesTool,
    createVolumeTool,
    updateVolumeTool,
    deleteVolumeTool
  ],
  triggers: [projectWebhookTrigger]
});
