import { Slate } from 'slates';
import { spec } from './spec';
import {
  activateWorkflow,
  createCredential,
  createWorkflow,
  deleteCredential,
  deleteExecution,
  deleteWorkflow,
  discoverApi,
  generateAudit,
  getCredentialSchema,
  getExecution,
  getWorkflow,
  listCredentials,
  listExecutions,
  listUsers,
  listWorkflows,
  manageProjects,
  manageTags,
  manageVariables,
  manageWorkflowTags,
  retryExecution,
  sourceControlPull,
  stopExecution,
  transferResource,
  updateWorkflow
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    discoverApi,
    listWorkflows,
    getWorkflow,
    createWorkflow,
    updateWorkflow,
    deleteWorkflow,
    activateWorkflow,
    manageWorkflowTags,
    listExecutions,
    getExecution,
    retryExecution,
    stopExecution,
    deleteExecution,
    listCredentials,
    createCredential,
    deleteCredential,
    getCredentialSchema,
    listUsers,
    manageTags,
    manageVariables,
    manageProjects,
    transferResource,
    sourceControlPull,
    generateAudit
  ],
  triggers: []
});
