import { Slate } from 'slates';
import { spec } from './spec';
import {
  createDeploy,
  createOccurrence,
  deleteOccurrence,
  getDeploy,
  getItem,
  getMetrics,
  getOccurrence,
  getVersion,
  listDeploys,
  listEnvironments,
  listItems,
  listOccurrences,
  listUsers,
  manageAccessTokens,
  manageNotificationRules,
  manageProject,
  manageRqlJob,
  manageServiceLinks,
  manageTeam,
  manageTeamMembers,
  manageTeamProjects,
  runRqlQuery,
  updateItem
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    createOccurrence,
    deleteOccurrence,
    getDeploy,
    manageRqlJob,
    listItems,
    getItem,
    updateItem,
    listOccurrences,
    getOccurrence,
    createDeploy,
    listDeploys,
    manageProject,
    manageTeam,
    manageTeamMembers,
    manageTeamProjects,
    runRqlQuery,
    getMetrics,
    manageNotificationRules,
    listEnvironments,
    manageAccessTokens,
    manageServiceLinks,
    listUsers,
    getVersion
  ],
  triggers: []
});
