import { SlateTool } from 'slates';
import { z } from 'zod';
import { FirefliesClient } from '../lib/client';
import { spec } from '../spec';
import { appOutputSchema, assertLimit, assertNonNegativeSkip, mapAppOutput } from './shared';

export let getAiApps = SlateTool.create(spec, {
  name: 'Get AI App Results',
  key: 'get_ai_apps',
  description: `Retrieve results generated by AI Apps installed in your Fireflies workspace. Filter by a specific AI app or transcript to see the prompts and responses generated.`,
  tags: {
    readOnly: true
  }
})
  .input(
    z.object({
      appId: z.string().optional().describe('Filter results by a specific AI App ID'),
      transcriptId: z
        .string()
        .optional()
        .describe('Filter results by a specific transcript ID'),
      limit: z.number().optional().describe('Maximum number of results to return (max 10)'),
      skip: z.number().optional().describe('Number of results to skip for pagination')
    })
  )
  .output(
    z.object({
      outputs: z.array(appOutputSchema).describe('AI App output results')
    })
  )
  .handleInvocation(async ctx => {
    assertLimit(ctx.input.limit, 'limit', 10);
    assertNonNegativeSkip(ctx.input.skip);

    let client = new FirefliesClient({ token: ctx.auth.token });

    let result = await client.getAiApps({
      appId: ctx.input.appId,
      transcriptId: ctx.input.transcriptId,
      limit: ctx.input.limit,
      skip: ctx.input.skip
    });

    let outputs = (result?.outputs || []).map((output: any) => mapAppOutput(output));

    return {
      output: { outputs },
      message: `Retrieved **${outputs.length}** AI App result(s).`
    };
  })
  .build();
