import { Slate } from 'slates';
import { spec } from './spec';
import {
  adjustInventory,
  createCustomer,
  createInvoice,
  createOrder,
  createPayment,
  deleteCatalogObject,
  deleteCustomer,
  getCatalogObject,
  getCustomer,
  getInventory,
  getInvoice,
  getLocation,
  getMerchant,
  getOrder,
  getPayment,
  getRefund,
  listCustomers,
  listInvoices,
  listLocations,
  listPayments,
  listRefunds,
  manageInvoice,
  managePayment,
  payOrder,
  refundPayment,
  searchCatalog,
  searchCustomers,
  searchInvoices,
  searchOrders,
  updateCustomer,
  updateInvoice,
  updateOrder,
  upsertCatalogObject
} from './tools';
import {
  bookingEvents,
  catalogEvents,
  customerEvents,
  disputeEvents,
  inventoryEvents,
  invoiceEvents,
  loyaltyEvents,
  orderEvents,
  paymentEvents,
  refundEvents,
  subscriptionEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listPayments,
    getPayment,
    createPayment,
    managePayment,
    refundPayment,
    listRefunds,
    getRefund,
    searchOrders,
    getOrder,
    createOrder,
    updateOrder,
    payOrder,
    listCustomers,
    getCustomer,
    createCustomer,
    updateCustomer,
    deleteCustomer,
    searchCustomers,
    searchCatalog,
    getCatalogObject,
    upsertCatalogObject,
    deleteCatalogObject,
    getInventory,
    adjustInventory,
    listInvoices,
    getInvoice,
    createInvoice,
    updateInvoice,
    searchInvoices,
    manageInvoice,
    listLocations,
    getLocation,
    getMerchant
  ],
  triggers: [
    paymentEvents,
    orderEvents,
    customerEvents,
    invoiceEvents,
    catalogEvents,
    inventoryEvents,
    refundEvents,
    bookingEvents,
    disputeEvents,
    subscriptionEvents,
    loyaltyEvents
  ]
});
