import { Slate } from 'slates';
import { spec } from './spec';
import {
  createComment,
  createFolder,
  createGoal,
  createList,
  createSpace,
  createSpaceTag,
  createTask,
  createTimeEntry,
  deleteFolder,
  deleteGoal,
  deleteList,
  deleteSpace,
  deleteTask,
  getCustomFields,
  getFolders,
  getGoals,
  getLists,
  getSpaces,
  getSpaceTags,
  getTask,
  getTaskComments,
  getTimeEntries,
  getWorkspaceMembers,
  getWorkspaces,
  searchTasks,
  setCustomFieldValue,
  startTimer,
  stopTimer,
  updateFolder,
  updateGoal,
  updateList,
  updateSpace,
  updateTask
} from './tools';
import { taskEvents, workspaceEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchTasks,
    getTask,
    createTask,
    updateTask,
    deleteTask,
    getTaskComments,
    createComment,
    getLists,
    createList,
    updateList,
    deleteList,
    getSpaces,
    createSpace,
    updateSpace,
    deleteSpace,
    getFolders,
    createFolder,
    updateFolder,
    deleteFolder,
    getGoals,
    createGoal,
    updateGoal,
    deleteGoal,
    getSpaceTags,
    createSpaceTag,
    getCustomFields,
    setCustomFieldValue,
    getTimeEntries,
    createTimeEntry,
    startTimer,
    stopTimer,
    getWorkspaces,
    getWorkspaceMembers
  ],
  triggers: [taskEvents, workspaceEvents]
});
