import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAuthorization,
  createBucket,
  createDashboard,
  createDBRP,
  createLabel,
  createTask,
  createTelegraf,
  deleteAuthorization,
  deleteBucket,
  deleteDashboard,
  deleteData,
  deleteDBRP,
  deleteLabel,
  deleteSecrets,
  deleteTask,
  deleteTelegraf,
  getOrganizationMembers,
  getTask,
  getTaskRuns,
  getTelegraf,
  listAuthorizations,
  listBuckets,
  listChecks,
  listDashboards,
  listDBRPs,
  listLabels,
  listNotificationEndpoints,
  listNotificationRules,
  listOrganizations,
  listSecrets,
  listTasks,
  listTelegrafs,
  queryData,
  runTask,
  updateAuthorization,
  updateBucket,
  updateDashboard,
  updateLabel,
  updateTask,
  updateTelegraf,
  upsertSecrets,
  writeData
} from './tools';
import { bucketChangesTrigger, inboundWebhook, taskRunsTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    writeData,
    queryData,
    deleteData,
    listBuckets,
    createBucket,
    updateBucket,
    deleteBucket,
    listTasks,
    getTask,
    createTask,
    updateTask,
    deleteTask,
    runTask,
    getTaskRuns,
    listAuthorizations,
    createAuthorization,
    updateAuthorization,
    deleteAuthorization,
    listLabels,
    createLabel,
    updateLabel,
    deleteLabel,
    listDashboards,
    createDashboard,
    updateDashboard,
    deleteDashboard,
    listSecrets,
    upsertSecrets,
    deleteSecrets,
    listTelegrafs,
    getTelegraf,
    createTelegraf,
    updateTelegraf,
    deleteTelegraf,
    listChecks,
    listNotificationEndpoints,
    listNotificationRules,
    listOrganizations,
    getOrganizationMembers,
    listDBRPs,
    createDBRP,
    deleteDBRP
  ],
  triggers: [inboundWebhook, taskRunsTrigger, bucketChangesTrigger]
});
