import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  addContactsToSequence,
  bulkCreateAccounts,
  bulkCreateContacts,
  bulkUpdateAccounts,
  bulkUpdateContacts,
  createAccount,
  createCall,
  createContact,
  createDeal,
  createTask,
  enrichOrganization,
  enrichPerson,
  exportConversations,
  getAccount,
  getConversation,
  getDeal,
  getOrganization,
  getUsageStats,
  listDeals,
  listEmailAccounts,
  listOrganizationJobPostings,
  listStages,
  listUsers,
  queryAnalyticsReport,
  searchAccounts,
  searchCalls,
  searchContacts,
  searchConversations,
  searchNewsArticles,
  searchOrganizations,
  searchPeople,
  searchSequences,
  searchTasks,
  updateAccount,
  updateAccountOwners,
  updateCall,
  updateContact,
  updateContactOwners,
  updateContactSequenceStatus,
  updateContactStages,
  updateDeal
} from './tools';
import { contactChanges, dealChanges, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchPeople,
    searchOrganizations,
    getOrganization,
    enrichOrganization,
    listOrganizationJobPostings,
    searchNewsArticles,
    enrichPerson,
    searchContacts,
    createContact,
    updateContact,
    bulkCreateContacts,
    bulkUpdateContacts,
    updateContactStages,
    updateContactOwners,
    searchAccounts,
    getAccount,
    createAccount,
    updateAccount,
    bulkCreateAccounts,
    bulkUpdateAccounts,
    updateAccountOwners,
    listDeals,
    getDeal,
    createDeal,
    updateDeal,
    searchSequences,
    addContactsToSequence,
    updateContactSequenceStatus,
    searchTasks,
    createTask,
    searchCalls,
    createCall,
    updateCall,
    searchConversations,
    getConversation,
    exportConversations,
    queryAnalyticsReport,
    listUsers,
    listStages,
    listEmailAccounts,
    getUsageStats
  ],
  triggers: [inboundWebhook, contactChanges, dealChanges]
});
