import { Slate } from 'slates';
import { spec } from './spec';

import {
  createActivity,
  createCompany,
  createContact,
  createDeal,
  createNote,
  createProduct,
  createTicket,
  deleteActivity,
  deleteCompany,
  deleteContact,
  deleteDeal,
  deleteNote,
  deleteProduct,
  deleteTicket,
  getActivity,
  getCompany,
  getContact,
  getDeal,
  getNote,
  getProduct,
  getTicket,
  getUser,
  listUsers,
  searchActivities,
  searchCompanies,
  searchContacts,
  searchDeals,
  searchProducts,
  searchTickets,
  updateActivity,
  updateCompany,
  updateContact,
  updateDeal,
  updateNote,
  updateProduct,
  updateTicket
} from './tools';

import {
  activityEvents,
  companyEvents,
  contactEvents,
  dealEvents,
  inboundWebhook
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createContact,
    getContact,
    updateContact,
    deleteContact,
    searchContacts,
    createCompany,
    getCompany,
    updateCompany,
    deleteCompany,
    searchCompanies,
    createDeal,
    getDeal,
    updateDeal,
    deleteDeal,
    searchDeals,
    createActivity,
    getActivity,
    updateActivity,
    deleteActivity,
    searchActivities,
    createProduct,
    getProduct,
    updateProduct,
    deleteProduct,
    searchProducts,
    createTicket,
    getTicket,
    updateTicket,
    deleteTicket,
    searchTickets,
    createNote,
    getNote,
    updateNote,
    deleteNote,
    listUsers,
    getUser
  ],
  triggers: [inboundWebhook, contactEvents, companyEvents, dealEvents, activityEvents]
});
