import { Slate } from 'slates';
import { spec } from './spec';
import {
  addTicketConversation,
  createAsset,
  createChange,
  createKnowledgeBaseArticle,
  createProblem,
  createRequester,
  createTicket,
  deleteAsset,
  deleteChange,
  deleteProblem,
  deleteTicket,
  getAgent,
  getAsset,
  getChange,
  getDepartment,
  getKnowledgeBaseArticle,
  getProblem,
  getRequester,
  getServiceCatalogItem,
  getTicket,
  listAgents,
  listAssets,
  listChanges,
  listDepartments,
  listKnowledgeBaseArticles,
  listKnowledgeBaseCategories,
  listKnowledgeBaseFolders,
  listProblems,
  listRequesters,
  listServiceCatalogItems,
  listServiceCategories,
  listTickets,
  placeServiceRequest,
  searchTickets,
  updateAsset,
  updateChange,
  updateKnowledgeBaseArticle,
  updateProblem,
  updateRequester,
  updateTicket
} from './tools';
import { changeUpdates, inboundWebhook, ticketUpdates } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createTicket,
    getTicket,
    listTickets,
    updateTicket,
    deleteTicket,
    searchTickets,
    addTicketConversation,
    createProblem,
    getProblem,
    listProblems,
    updateProblem,
    deleteProblem,
    createChange,
    getChange,
    listChanges,
    updateChange,
    deleteChange,
    createAsset,
    getAsset,
    listAssets,
    updateAsset,
    deleteAsset,
    createRequester,
    getRequester,
    listRequesters,
    updateRequester,
    listAgents,
    getAgent,
    listKnowledgeBaseArticles,
    getKnowledgeBaseArticle,
    createKnowledgeBaseArticle,
    updateKnowledgeBaseArticle,
    listKnowledgeBaseCategories,
    listKnowledgeBaseFolders,
    listServiceCatalogItems,
    getServiceCatalogItem,
    placeServiceRequest,
    listServiceCategories,
    listDepartments,
    getDepartment
  ],
  triggers: [inboundWebhook, ticketUpdates, changeUpdates]
});
