import { Slate } from 'slates';
import { spec } from './spec';
import {
  createGroup,
  createSavedSearch,
  createSystem,
  deleteGroup,
  deleteSavedSearch,
  deleteSystem,
  downloadArchive,
  getAccountUsage,
  getDestination,
  getGroup,
  getSavedSearch,
  getSystem,
  getUsage,
  inviteUser,
  listArchives,
  listDestinations,
  listGroups,
  listSavedSearches,
  listSystems,
  listUsers,
  manageGroupMembership,
  removeUser,
  searchEvents,
  updateGroup,
  updateSavedSearch,
  updateSystem
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    downloadArchive,
    getSystem,
    getSavedSearch,
    getDestination,
    getUsage,
    searchEvents,
    listSystems,
    createSystem,
    updateSystem,
    deleteSystem,
    listGroups,
    getGroup,
    createGroup,
    updateGroup,
    deleteGroup,
    manageGroupMembership,
    listSavedSearches,
    createSavedSearch,
    updateSavedSearch,
    deleteSavedSearch,
    listUsers,
    inviteUser,
    removeUser,
    listArchives,
    getAccountUsage,
    listDestinations
  ],
  triggers: []
});
