import { Slate } from 'slates';
import { spec } from './spec';
import {
  getClient,
  getIdentity,
  getInvoice,
  getResource,
  listClients,
  listExpenses,
  listInvoices,
  listItems,
  listPayments,
  listProjects,
  listResources,
  listTaxes,
  listTimeEntries,
  manageClients,
  manageCreditNotes,
  manageEstimates,
  manageExpenses,
  manageInvoices,
  manageItems,
  managePayments,
  manageProjects,
  manageTaxes,
  manageTimeEntries
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getIdentity,
    getResource,
    listResources,
    manageClients,
    listClients,
    getClient,
    manageInvoices,
    listInvoices,
    getInvoice,
    managePayments,
    listPayments,
    manageEstimates,
    manageExpenses,
    listExpenses,
    manageTimeEntries,
    listTimeEntries,
    manageProjects,
    listProjects,
    manageTaxes,
    listTaxes,
    manageItems,
    listItems,
    manageCreditNotes
  ],
  triggers: []
});
