import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCustomer,
  createOrder,
  createProduct,
  createRefund,
  deleteCustomer,
  deleteOrder,
  deleteProduct,
  getCustomer,
  getOrder,
  getProduct,
  getSalesReport,
  getShippingMethods,
  getStoreSettings,
  getSystemStatus,
  listCustomers,
  listOrders,
  listProducts,
  manageCoupons,
  manageOrderNotes,
  managePaymentGateways,
  manageProductAttributes,
  manageProductCategories,
  manageProductReviews,
  manageProductTags,
  manageProductVariations,
  manageShippingClasses,
  manageShippingZones,
  manageTaxRates,
  manageWebhooks,
  updateCustomer,
  updateOrder,
  updateProduct,
  updateStoreSetting
} from './tools';
import { couponEvents, customerEvents, orderEvents, productEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listProducts,
    getProduct,
    createProduct,
    updateProduct,
    deleteProduct,
    manageProductVariations,
    manageProductCategories,
    listOrders,
    getOrder,
    createOrder,
    updateOrder,
    deleteOrder,
    manageOrderNotes,
    createRefund,
    listCustomers,
    getCustomer,
    createCustomer,
    updateCustomer,
    deleteCustomer,
    manageCoupons,
    manageProductTags,
    manageProductAttributes,
    manageProductReviews,
    getSalesReport,
    manageShippingZones,
    manageShippingClasses,
    getShippingMethods,
    manageTaxRates,
    getStoreSettings,
    updateStoreSetting,
    managePaymentGateways,
    manageWebhooks,
    getSystemStatus
  ],
  triggers: [orderEvents, productEvents, customerEvents, couponEvents]
});
