import { Slate } from 'slates';
import { spec } from './spec';
import {
  associateContactWithAccount,
  createNote,
  createOrUpdateAccount,
  createOrUpdateContact,
  createOrUpdateDeal,
  createOrUpdateTask,
  deleteAccount,
  deleteContact,
  deleteDeal,
  deleteTask,
  getAccount,
  getContact,
  getDeal,
  getTask,
  listAutomations,
  listCampaigns,
  listCustomFields,
  listPipelinesAndStages,
  listTasks,
  listTaskTypes,
  listUsers,
  manageContactAutomation,
  manageContactTags,
  manageListSubscription,
  manageLists,
  manageTags,
  manageWebhooks,
  searchAccounts,
  searchContacts,
  searchDeals
} from './tools';
import { campaignEvents, contactEvents, dealEvents, smsEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createOrUpdateContact,
    getContact,
    searchContacts,
    deleteContact,
    manageContactTags,
    manageListSubscription,
    manageContactAutomation,
    createOrUpdateDeal,
    getDeal,
    searchDeals,
    deleteDeal,
    manageTags,
    manageLists,
    listCampaigns,
    listAutomations,
    createOrUpdateAccount,
    getAccount,
    searchAccounts,
    deleteAccount,
    associateContactWithAccount,
    createNote,
    createOrUpdateTask,
    getTask,
    listTasks,
    deleteTask,
    listTaskTypes,
    listPipelinesAndStages,
    listCustomFields,
    listUsers,
    manageWebhooks
  ],
  triggers: [contactEvents, dealEvents, campaignEvents, smsEvents]
});
