import { createAxios, SlateAuth } from 'slates';
import { z } from 'zod';

let scopes = [
  {
    title: 'Recordings Export',
    description: 'Access recording URLs in call events',
    scope: 'recordings_export'
  },
  {
    title: 'Message Content Export',
    description: 'Export SMS content for the authenticated user',
    scope: 'message_content_export'
  },
  {
    title: 'Message Content Export (All)',
    description: 'Export company-wide SMS content',
    scope: 'message_content_export:all'
  },
  { title: 'Screen Pop', description: 'Use the screen pop API', scope: 'screen_pop' },
  { title: 'Calls List', description: 'Access the Call List API', scope: 'calls:list' },
  { title: 'Fax Message', description: 'Access Fax API and Events', scope: 'fax_message' },
  {
    title: 'Change Log',
    description: 'Create change log event subscriptions',
    scope: 'change_log'
  },
  {
    title: 'Offline Access',
    description: 'Obtain a refresh token to extend OAuth access token duration',
    scope: 'offline_access'
  }
];

let envToBaseUrl = (env: string) =>
  env === 'sandbox' ? 'https://sandbox.dialpad.com' : 'https://dialpad.com';

function createDialpadOauth(name: string, key: string, environment: 'production' | 'sandbox') {
  let baseUrl = envToBaseUrl(environment);

  return {
    type: 'auth.oauth' as const,
    name,
    key,
    docs: [
      {
        type: 'docs.auth.oauth',
        name: 'OAuth documentation',
        url: 'https://developers.dialpad.com/docs/oauth'
      },
      {
        type: 'docs.auth.oauth_scopes',
        name: 'OAuth scopes',
        url: 'https://developers.dialpad.com/docs/oauth#supported-scopes'
      }
    ],
    scopes,

    getAuthorizationUrl: async (ctx: any) => {
      let params = new URLSearchParams({
        client_id: ctx.clientId,
        redirect_uri: ctx.redirectUri,
        state: ctx.state,
        response_type: 'code'
      });
      if (ctx.scopes.length > 0) {
        params.set('scope', ctx.scopes.join(' '));
      }
      return { url: `${baseUrl}/oauth2/authorize?${params.toString()}` };
    },

    handleCallback: async (ctx: any) => {
      let axios = createAxios({ baseURL: baseUrl });
      let response = await axios.post(
        '/oauth2/token',
        {
          client_id: ctx.clientId,
          client_secret: ctx.clientSecret,
          code: ctx.code,
          grant_type: 'authorization_code',
          redirect_uri: ctx.redirectUri
        },
        { headers: { 'Content-Type': 'application/json' } }
      );
      let data = response.data;
      let expiresAt = data.expires_in
        ? new Date(Date.now() + data.expires_in * 1000).toISOString()
        : undefined;
      return {
        output: {
          token: data.access_token,
          refreshToken: data.refresh_token,
          expiresAt,
          environment
        }
      };
    },

    handleTokenRefresh: async (ctx: any) => {
      if (!ctx.output.refreshToken) {
        return { output: ctx.output };
      }
      let axios = createAxios({ baseURL: baseUrl });
      let response = await axios.post(
        '/oauth2/token',
        {
          client_id: ctx.clientId,
          client_secret: ctx.clientSecret,
          refresh_token: ctx.output.refreshToken,
          grant_type: 'refresh_token'
        },
        { headers: { 'Content-Type': 'application/json' } }
      );
      let data = response.data;
      let expiresAt = data.expires_in
        ? new Date(Date.now() + data.expires_in * 1000).toISOString()
        : undefined;
      return {
        output: {
          token: data.access_token,
          refreshToken: data.refresh_token || ctx.output.refreshToken,
          expiresAt,
          environment
        }
      };
    },

    getProfile: async (ctx: any) => {
      let axios = createAxios({ baseURL: baseUrl });
      let response = await axios.get('/api/v2/users/me', {
        headers: { Authorization: `Bearer ${ctx.output.token}` }
      });
      let user = response.data;
      return {
        profile: {
          id: String(user.id),
          email: user.emails?.[0],
          name: user.display_name || `${user.first_name || ''} ${user.last_name || ''}`.trim(),
          imageUrl: user.image_url
        }
      };
    }
  };
}

function createDialpadApiKey(
  name: string,
  key: string,
  environment: 'production' | 'sandbox'
) {
  let baseUrl = envToBaseUrl(environment);
  return {
    type: 'auth.token' as const,
    name,
    key,
    inputSchema: z.object({
      apiKey: z.string().describe('Dialpad API key generated by a Company Admin')
    }),
    getOutput: async (ctx: { input: { apiKey: string } }) => ({
      output: {
        token: ctx.input.apiKey,
        environment
      }
    }),
    getProfile: async (ctx: any) => {
      let axios = createAxios({ baseURL: baseUrl });
      let response = await axios.get('/api/v2/users/me', {
        headers: { Authorization: `Bearer ${ctx.output.token}` }
      });
      let user = response.data;
      return {
        profile: {
          id: String(user.id),
          email: user.emails?.[0],
          name: user.display_name || `${user.first_name || ''} ${user.last_name || ''}`.trim(),
          imageUrl: user.image_url
        }
      };
    }
  };
}

export let auth = SlateAuth.create()
  .output(
    z.object({
      token: z.string(),
      refreshToken: z.string().optional(),
      expiresAt: z.string().optional(),
      environment: z.enum(['production', 'sandbox'])
    })
  )
  .addOauth(createDialpadOauth('Production', 'oauth_production', 'production'))
  .addOauth(createDialpadOauth('Sandbox', 'oauth_sandbox', 'sandbox'))
  .addTokenAuth(
    createDialpadApiKey('API Key (Production)', 'api_key_production', 'production')
  )
  .addTokenAuth(createDialpadApiKey('API Key (Sandbox)', 'api_key_sandbox', 'sandbox'));
