import type { SuperGoogleToolManifestEntry } from '@slates/super-google-tools';

let include = (
  sourceIntegration: string,
  sourceKey: string,
  exposedKey?: string
): SuperGoogleToolManifestEntry => ({
  sourceIntegration,
  sourceKey,
  status: 'included',
  ...(exposedKey ? { exposedKey } : {})
});

export let superGoogle3Manifest: SuperGoogleToolManifestEntry[] = [
  include('compute-engine', 'create_instance'),
  include('compute-engine', 'delete_instance'),
  include('compute-engine', 'start_instance'),
  include('compute-engine', 'stop_instance'),
  include('compute-engine', 'reset_instance'),
  include('compute-engine', 'set_instance_machine_type'),
  include('compute-engine', 'get_instance_basic_info'),
  include('compute-engine', 'list_instances'),
  include('compute-engine', 'list_instance_attached_disks'),
  include('compute-engine', 'get_disk_basic_info'),
  include('compute-engine', 'get_disk_performance_config'),
  include('compute-engine', 'list_disks'),
  include('compute-engine', 'list_snapshots'),
  include('compute-engine', 'list_images'),
  include('compute-engine', 'list_machine_types'),
  include('compute-engine', 'list_accelerator_types'),
  include('compute-engine', 'get_instance_group_manager_basic_info'),
  include('compute-engine', 'list_instance_group_managers'),
  include('compute-engine', 'list_managed_instances'),
  include('compute-engine', 'get_instance_template_basic_info'),
  include('compute-engine', 'get_instance_template_properties'),
  include('compute-engine', 'list_instance_templates'),
  include('compute-engine', 'get_reservation_basic_info'),
  include('compute-engine', 'get_reservation_details'),
  include('compute-engine', 'list_reservations'),
  include('compute-engine', 'get_commitment_basic_info'),
  include('compute-engine', 'list_commitments'),
  include('compute-engine', 'list_commitment_reservations'),
  include('compute-engine', 'get_zone_operation'),

  include('bigquery', 'execute_query'),
  include('bigquery', 'execute_sql_readonly'),
  include('bigquery', 'list_datasets'),
  include('bigquery', 'get_dataset'),
  include('bigquery', 'create_dataset'),
  include('bigquery', 'update_dataset'),
  include('bigquery', 'delete_dataset'),
  include('bigquery', 'list_tables'),
  include('bigquery', 'get_table'),
  include('bigquery', 'create_table'),
  include('bigquery', 'update_table'),
  include('bigquery', 'delete_table'),
  include('bigquery', 'load_data'),
  include('bigquery', 'export_data'),
  include('bigquery', 'list_jobs'),
  include('bigquery', 'get_job'),
  include('bigquery', 'cancel_job'),
  include('bigquery', 'read_table_data'),
  include('bigquery', 'insert_rows'),
  include('bigquery', 'copy_table'),
  include('bigquery', 'list_models'),
  include('bigquery', 'get_model'),
  include('bigquery', 'update_model'),
  include('bigquery', 'delete_model'),
  include('bigquery', 'list_routines'),
  include('bigquery', 'get_routine'),
  include('bigquery', 'create_routine'),
  include('bigquery', 'delete_routine'),

  include('google-cloud-storage', 'list_buckets'),
  include('google-cloud-storage', 'get_bucket'),
  include('google-cloud-storage', 'manage_bucket'),
  include('google-cloud-storage', 'list_objects'),
  include('google-cloud-storage', 'get_object'),
  include('google-cloud-storage', 'upload_object'),
  include('google-cloud-storage', 'delete_object'),
  include('google-cloud-storage', 'copy_object'),
  include('google-cloud-storage', 'update_object_metadata'),
  include('google-cloud-storage', 'manage_bucket_iam'),
  include('google-cloud-storage', 'manage_lifecycle'),
  include('google-cloud-storage', 'manage_notifications'),

  include('google-cloud-functions', 'list_functions'),
  include('google-cloud-functions', 'get_function'),
  include('google-cloud-functions', 'create_function'),
  include('google-cloud-functions', 'update_function'),
  include('google-cloud-functions', 'delete_function'),
  include('google-cloud-functions', 'list_runtimes'),
  include('google-cloud-functions', 'generate_upload_url'),
  include('google-cloud-functions', 'generate_download_url'),
  include('google-cloud-functions', 'manage_iam_policy'),
  include('google-cloud-functions', 'get_operation', 'functions_get_operation'),

  include('google-cloud-speech', 'transcribe_audio'),
  include('google-cloud-speech', 'batch_transcribe_audio'),
  include('google-cloud-speech', 'get_operation', 'speech_get_operation'),
  include('google-cloud-speech', 'create_recognizer'),
  include('google-cloud-speech', 'get_recognizer'),
  include('google-cloud-speech', 'list_recognizers'),
  include('google-cloud-speech', 'update_recognizer'),
  include('google-cloud-speech', 'delete_recognizer'),
  include('google-cloud-speech', 'synthesize_speech'),
  include('google-cloud-speech', 'list_voices'),

  include('google-cloud-vision', 'analyze_image'),
  include('google-cloud-vision', 'detect_labels'),
  include('google-cloud-vision', 'detect_objects'),
  include('google-cloud-vision', 'detect_faces'),
  include('google-cloud-vision', 'detect_landmarks'),
  include('google-cloud-vision', 'detect_logos'),
  include('google-cloud-vision', 'detect_text'),
  include('google-cloud-vision', 'detect_safe_search'),
  include('google-cloud-vision', 'detect_image_properties'),
  include('google-cloud-vision', 'get_crop_hints'),
  include('google-cloud-vision', 'detect_web'),

  include('google-address-validation', 'validate_address'),
  include('google-address-validation', 'provide_validation_feedback'),

  include('firebase', 'manage_firestore_document'),
  include('firebase', 'query_firestore'),
  include('firebase', 'manage_realtime_data'),
  include('firebase', 'manage_user'),
  include('firebase', 'list_users'),
  include('firebase', 'lookup_user'),
  include('firebase', 'send_fcm_message'),
  include('firebase', 'manage_topic_subscriptions'),
  include('firebase', 'get_remote_config'),
  include('firebase', 'update_remote_config'),
  include('firebase', 'manage_storage'),
  include('firebase', 'get_firebase_apps')
];
