import { Slate } from 'slates';
import { spec } from './spec';
import {
  createMuralFromTemplateTool,
  createMuralTool,
  createRoomTool,
  createTagTool,
  createTemplateFromMuralTool,
  createWidgetTool,
  deleteMuralTool,
  deleteRoomTool,
  deleteTagTool,
  deleteTemplateTool,
  duplicateMuralTool,
  getChatHistoryTool,
  getCurrentUserTool,
  getMuralTool,
  getVotingResultsTool,
  getWidgetTool,
  inviteUsersTool,
  listMuralsTool,
  listMuralUsersTool,
  listRoomsTool,
  listTagsTool,
  listTemplatesTool,
  listVotingSessionsTool,
  listWidgetsTool,
  listWorkspacesTool,
  managePrivateModeTool,
  manageTimerTool,
  removeUsersTool,
  searchTool,
  startVotingSessionTool,
  updateMuralTool,
  updateRoomTool,
  updateTagTool,
  updateWidgetTool
} from './tools';
import { inboundWebhook, newMuralTrigger, newWidgetTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listWorkspacesTool,
    listRoomsTool,
    createRoomTool,
    updateRoomTool,
    deleteRoomTool,
    listMuralsTool,
    getMuralTool,
    createMuralTool,
    updateMuralTool,
    deleteMuralTool,
    duplicateMuralTool,
    listWidgetsTool,
    getWidgetTool,
    createWidgetTool,
    updateWidgetTool,
    listTagsTool,
    createTagTool,
    updateTagTool,
    deleteTagTool,
    listTemplatesTool,
    createTemplateFromMuralTool,
    createMuralFromTemplateTool,
    deleteTemplateTool,
    getCurrentUserTool,
    listMuralUsersTool,
    inviteUsersTool,
    removeUsersTool,
    searchTool,
    startVotingSessionTool,
    getVotingResultsTool,
    listVotingSessionsTool,
    manageTimerTool,
    managePrivateModeTool,
    getChatHistoryTool
  ],
  triggers: [inboundWebhook, newMuralTrigger, newWidgetTrigger]
});
