import { Slate } from 'slates';
import { spec } from './spec';

import {
  calculateTax,
  createCheckoutSession,
  createContact,
  createCreditNote,
  createEstimate,
  createExpense,
  createInvoice,
  createJurisdiction,
  createProduct,
  createRecurring,
  createReport,
  createTransaction,
  deleteContact,
  deleteEstimate,
  deleteExpense,
  deleteJurisdiction,
  deletePayment,
  deleteProduct,
  deleteRecurring,
  deliverCreditNote,
  deliverEstimate,
  deliverInvoice,
  getContact,
  getCreditNote,
  getEstimate,
  getExpense,
  getInvoice,
  getReportStatus,
  listCheckoutSessions,
  listContacts,
  listCreditNotes,
  listEstimates,
  listExpenses,
  listInvoices,
  listJurisdictions,
  listProducts,
  listRecurring,
  recordPayment,
  updateContact,
  updateExpense,
  updateInvoice,
  updateProduct,
  validateTaxId
} from './tools';

import {
  checkoutEvents,
  contactEvents,
  deliveryEvents,
  documentEvents,
  paymentEvents,
  thresholdEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    calculateTax,
    validateTaxId,
    listContacts,
    getContact,
    createContact,
    updateContact,
    deleteContact,
    listProducts,
    createProduct,
    updateProduct,
    deleteProduct,
    listInvoices,
    getInvoice,
    createInvoice,
    updateInvoice,
    deliverInvoice,
    listCreditNotes,
    getCreditNote,
    createCreditNote,
    deliverCreditNote,
    listExpenses,
    getExpense,
    createExpense,
    updateExpense,
    deleteExpense,
    listEstimates,
    getEstimate,
    createEstimate,
    deleteEstimate,
    deliverEstimate,
    listRecurring,
    createRecurring,
    deleteRecurring,
    recordPayment,
    deletePayment,
    listCheckoutSessions,
    createCheckoutSession,
    createReport,
    getReportStatus,
    listJurisdictions,
    createJurisdiction,
    deleteJurisdiction,
    createTransaction
  ],
  triggers: [
    documentEvents,
    contactEvents,
    paymentEvents,
    checkoutEvents,
    deliveryEvents,
    thresholdEvents
  ]
});
