import { Slate } from 'slates';
import { spec } from './spec';
import {
  createEntry,
  createOpportunity,
  createParty,
  createProject,
  createTask,
  deleteOpportunity,
  deleteParty,
  deleteProject,
  deleteTask,
  getCurrentUser,
  getOpportunity,
  getParty,
  getProject,
  listEntries,
  listOpportunities,
  listParties,
  listPipelines,
  listProjects,
  listTasks,
  listUsers,
  manageTags,
  searchParties,
  updateOpportunity,
  updateParty,
  updateProject,
  updateTask
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    listParties,
    getCurrentUser,
    getOpportunity,
    getParty,
    getProject,
    createParty,
    updateParty,
    deleteParty,
    searchParties,
    listOpportunities,
    createOpportunity,
    updateOpportunity,
    deleteOpportunity,
    listProjects,
    createProject,
    updateProject,
    deleteProject,
    listTasks,
    createTask,
    updateTask,
    deleteTask,
    listEntries,
    createEntry,
    manageTags,
    listPipelines,
    listUsers
  ],
  triggers: []
});
