import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAssistant,
  createChatflow,
  createDocumentStore,
  createFeedback,
  createLead,
  createTool,
  createVariable,
  deleteAssistant,
  deleteChatflow,
  deleteChatMessages,
  deleteDocumentStore,
  deleteDocumentStoreVectors,
  deleteTool,
  deleteVariable,
  getAssistant,
  getChatflow,
  getChatMessages,
  getDocumentStore,
  getDocumentStoreChunks,
  getTool,
  getUpsertHistory,
  listAssistants,
  listChatflows,
  listDocumentStores,
  listFeedback,
  listLeads,
  listTools,
  listVariables,
  ping,
  queryVectorStore,
  sendPrediction,
  updateAssistant,
  updateChatflow,
  updateDocumentStore,
  updateTool,
  updateVariable,
  upsertDocumentStore,
  upsertVectorData
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    sendPrediction,
    listChatflows,
    getChatflow,
    createChatflow,
    updateChatflow,
    deleteChatflow,
    listAssistants,
    getAssistant,
    createAssistant,
    updateAssistant,
    deleteAssistant,
    listDocumentStores,
    getDocumentStore,
    getDocumentStoreChunks,
    getTool,
    createDocumentStore,
    deleteDocumentStore,
    deleteDocumentStoreVectors,
    queryVectorStore,
    upsertVectorData,
    getChatMessages,
    deleteChatMessages,
    createFeedback,
    listFeedback,
    createLead,
    listLeads,
    listTools,
    createTool,
    updateTool,
    updateDocumentStore,
    upsertDocumentStore,
    deleteTool,
    listVariables,
    createVariable,
    updateVariable,
    deleteVariable,
    getUpsertHistory,
    ping
  ],
  triggers: []
});
