import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCommissionToConversion,
  approveCommission,
  cancelPayment,
  createAffiliate,
  createAffiliateGroup,
  createAffiliateProspect,
  createClick,
  createConversion,
  createCustomer,
  createPayment,
  deleteAffiliate,
  deleteAffiliateProspect,
  deleteConversion,
  deleteCustomer,
  disapproveCommission,
  getAffiliate,
  getCommission,
  getConversion,
  getCustomer,
  getProgram,
  listAffiliateGroups,
  listAffiliateProspects,
  listAffiliates,
  listBalances,
  listClicks,
  listCommissions,
  listConversions,
  listCustomers,
  listPayments,
  listProgramAffiliates,
  listPrograms,
  manageAffiliateGroup,
  manageAffiliatePayoutMethod,
  manageMlmParent,
  manageProgramAffiliate,
  updateAffiliateGroup,
  updateAffiliateMetaData,
  updateCommission,
  updateConversion,
  updateCustomerStatus
} from './tools';
import { affiliateEvents, customerEvents, paymentEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createAffiliate,
    getAffiliate,
    listAffiliates,
    deleteAffiliate,
    updateAffiliateMetaData,
    manageAffiliateGroup,
    manageAffiliatePayoutMethod,
    createConversion,
    getConversion,
    listConversions,
    updateConversion,
    deleteConversion,
    addCommissionToConversion,
    listCommissions,
    getCommission,
    updateCommission,
    approveCommission,
    disapproveCommission,
    createCustomer,
    getCustomer,
    listCustomers,
    updateCustomerStatus,
    deleteCustomer,
    listPrograms,
    getProgram,
    manageProgramAffiliate,
    listProgramAffiliates,
    listBalances,
    createPayment,
    listPayments,
    cancelPayment,
    createClick,
    listClicks,
    listAffiliateGroups,
    createAffiliateGroup,
    updateAffiliateGroup,
    createAffiliateProspect,
    listAffiliateProspects,
    deleteAffiliateProspect,
    manageMlmParent
  ],
  triggers: [affiliateEvents, customerEvents, paymentEvents]
});
