import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCustomerNote,
  addLeadNote,
  batchCreateContacts,
  createCustomer,
  createLead,
  createPolicy,
  createServiceTicket,
  createTask,
  deleteCustomer,
  deleteLead,
  deletePolicy,
  deleteTask,
  getCustomer,
  getLead,
  getOpportunity,
  listReferenceData,
  manageLeadOpportunity,
  manageLeadQuote,
  manageOpportunity,
  manageOpportunityDriver,
  manageOpportunityVehicle,
  searchCustomers,
  searchLeads,
  searchServiceTickets,
  searchTasks,
  updateCustomer,
  updateLead,
  updatePolicy,
  updateServiceTicket,
  updateTask
} from './tools';
import { inboundWebhook, newLeadTrigger, serviceTicketUpdatedTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchLeads,
    getLead,
    createLead,
    updateLead,
    deleteLead,
    manageLeadOpportunity,
    manageLeadQuote,
    addLeadNote,
    searchCustomers,
    getCustomer,
    createCustomer,
    updateCustomer,
    deleteCustomer,
    addCustomerNote,
    searchTasks,
    createTask,
    updateTask,
    deleteTask,
    createPolicy,
    updatePolicy,
    deletePolicy,
    getOpportunity,
    manageOpportunity,
    manageOpportunityDriver,
    manageOpportunityVehicle,
    searchServiceTickets,
    createServiceTicket,
    updateServiceTicket,
    batchCreateContacts,
    listReferenceData
  ],
  triggers: [inboundWebhook, newLeadTrigger, serviceTicketUpdatedTrigger]
});
