import { Slate } from 'slates';
import { spec } from './spec';
import {
  createCompany,
  createDomain,
  createLead,
  createNote,
  createSequence,
  createSequenceStep,
  createTag,
  deleteCompany,
  deleteDomain,
  deleteLead,
  deleteNote,
  deleteSequence,
  deleteSequenceStep,
  deleteTag,
  findEmail,
  getCompany,
  getDomains,
  getLead,
  getNote,
  getSequence,
  listTags,
  searchCompanies,
  searchLeads,
  updateCompany,
  updateLead,
  updateNote,
  updateSequence,
  updateSequenceStep,
  updateTag,
  verifyEmail
} from './tools';
import { contactEvent } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    findEmail,
    verifyEmail,
    getLead,
    searchLeads,
    createLead,
    updateLead,
    deleteLead,
    getCompany,
    searchCompanies,
    createCompany,
    updateCompany,
    deleteCompany,
    getSequence,
    createSequence,
    updateSequence,
    deleteSequence,
    createSequenceStep,
    updateSequenceStep,
    deleteSequenceStep,
    listTags,
    createTag,
    updateTag,
    deleteTag,
    getNote,
    createNote,
    updateNote,
    deleteNote,
    getDomains,
    createDomain,
    deleteDomain
  ],
  triggers: [contactEvent]
});
