import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

export let getAccountInfo = SlateTool.create(spec, {
  name: 'Get Account Info',
  key: 'get_account_info',
  description:
    'Retrieve APIFRAME account details for the configured API key, including remaining credits and plan.',
  tags: {
    destructive: false,
    readOnly: true
  }
})
  .input(z.object({}))
  .output(
    z.object({
      email: z.string().optional().describe('Account email address'),
      credits: z.number().optional().describe('Remaining APIFRAME credits'),
      totalImages: z.number().optional().describe('Total images generated by the account'),
      plan: z.string().optional().describe('Current APIFRAME plan')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({
      token: ctx.auth.token,
      baseUrl: ctx.config.baseUrl
    });

    let account = await client.getAccountInfo();

    return {
      output: {
        email: account.email,
        credits: account.credits,
        totalImages: account.total_images,
        plan: account.plan
      },
      message: `APIFRAME account${account.plan ? ` on ${account.plan} plan` : ''}${account.credits !== undefined ? ` has ${account.credits} credits remaining` : ''}.`
    };
  })
  .build();
