import { Slate } from 'slates';
import { spec } from './spec';
import {
  createDatabase,
  createDatabaseToken,
  createGroup,
  createGroupToken,
  deleteDatabase,
  deleteGroup,
  getCurrentUser,
  getDatabase,
  getGroup,
  getOrganization,
  invalidateDatabaseTokens,
  invalidateGroupTokens,
  listAuditLogs,
  listDatabases,
  listGroups,
  listLocations,
  listOrganizations,
  manageApiTokens,
  manageGroupLocations,
  manageMembers,
  transferGroup,
  unarchiveGroup,
  updateDatabaseConfiguration
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getCurrentUser,
    listOrganizations,
    listDatabases,
    createDatabase,
    getDatabase,
    deleteDatabase,
    updateDatabaseConfiguration,
    createDatabaseToken,
    invalidateDatabaseTokens,
    listGroups,
    createGroup,
    getGroup,
    deleteGroup,
    manageGroupLocations,
    createGroupToken,
    invalidateGroupTokens,
    transferGroup,
    unarchiveGroup,
    listLocations,
    getOrganization,
    manageMembers,
    manageApiTokens,
    listAuditLogs
  ],
  triggers: []
});
