import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  addComment,
  addLabels,
  createBlogPost,
  createPage,
  deleteAttachment,
  deleteBlogPost,
  deleteComment,
  deletePage,
  deletePageProperty,
  getAttachment,
  getAttachments,
  getBlogPost,
  getComments,
  getContentRestrictions,
  getContentVersions,
  getCurrentUser,
  getLabels,
  getPage,
  getPageChildren,
  getPageProperties,
  getSpace,
  listBlogPosts,
  listGroups,
  listPages,
  listSpaces,
  removeContentRestrictions,
  removeLabel,
  searchContent,
  setPageProperty,
  updateBlogPost,
  updateContentRestrictions,
  updatePage,
  uploadAttachment
} from './tools';
import {
  attachmentEvents,
  blogEvents,
  commentEvents,
  labelEvents,
  pageEvents,
  spaceEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    getPage,
    listPages,
    createPage,
    updatePage,
    deletePage,
    getPageChildren,
    listBlogPosts,
    getBlogPost,
    createBlogPost,
    updateBlogPost,
    deleteBlogPost,
    listSpaces,
    getSpace,
    getComments,
    addComment,
    deleteComment,
    searchContent,
    getLabels,
    addLabels,
    removeLabel,
    getContentRestrictions,
    updateContentRestrictions,
    removeContentRestrictions,
    getCurrentUser,
    listGroups,
    getAttachments,
    uploadAttachment,
    getAttachment,
    deleteAttachment,
    getContentVersions,
    getPageProperties,
    setPageProperty,
    deletePageProperty
  ],
  triggers: [pageEvents, blogEvents, commentEvents, spaceEvents, attachmentEvents, labelEvents]
});
