import { Slate } from 'slates';
import { spec } from './spec';
import {
  clearItemUpdatesTool,
  createBoardTool,
  createColumnTool,
  createFolderTool,
  createGroupTool,
  createItemTool,
  createSubitemTool,
  createUpdateTool,
  createWebhookTool,
  createWorkspaceTool,
  deleteColumnTool,
  deleteFolderTool,
  deleteUpdateTool,
  deleteWebhookTool,
  duplicateBoardTool,
  duplicateItemTool,
  editUpdateTool,
  getActivityLogsTool,
  listBoardsTool,
  listColumnsTool,
  listFoldersTool,
  listGroupsTool,
  listItemsTool,
  listTagsTool,
  listTeamsTool,
  listUpdatesTool,
  listUsersTool,
  listWebhooksTool,
  listWorkspacesTool,
  moveBoardTool,
  moveItemTool,
  pinUpdateTool,
  reactToUpdateTool,
  sendNotificationTool,
  setItemDescriptionTool,
  updateBoardTool,
  updateColumnMetadataTool,
  updateFolderTool,
  updateGroupTool,
  updateItemTool,
  updateWorkspaceTool
} from './tools';
import { columnValueChangesTrigger, itemEventsTrigger, updateEventsTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listBoardsTool,
    createBoardTool,
    updateBoardTool,
    duplicateBoardTool,
    moveBoardTool,
    listItemsTool,
    createItemTool,
    updateItemTool,
    duplicateItemTool,
    moveItemTool,
    setItemDescriptionTool,
    createSubitemTool,
    listGroupsTool,
    createGroupTool,
    updateGroupTool,
    listColumnsTool,
    createColumnTool,
    updateColumnMetadataTool,
    deleteColumnTool,
    listUpdatesTool,
    createUpdateTool,
    editUpdateTool,
    reactToUpdateTool,
    pinUpdateTool,
    clearItemUpdatesTool,
    deleteUpdateTool,
    listUsersTool,
    listTeamsTool,
    listWorkspacesTool,
    createWorkspaceTool,
    updateWorkspaceTool,
    listFoldersTool,
    createFolderTool,
    updateFolderTool,
    deleteFolderTool,
    listWebhooksTool,
    createWebhookTool,
    deleteWebhookTool,
    sendNotificationTool,
    listTagsTool,
    getActivityLogsTool
  ],
  triggers: [itemEventsTrigger, columnValueChangesTrigger, updateEventsTrigger]
});
