import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

export let getOptimization = SlateTool.create(spec, {
  name: 'Get Optimization',
  key: 'get_optimization',
  description: `Retrieve an optimization problem by ID, or list all optimizations. Returns the optimization state, routes, and addresses.
Use this to check optimization status, retrieve computed routes, or browse all optimizations.`,
  tags: {
    readOnly: true
  }
})
  .input(
    z.object({
      optimizationProblemId: z
        .string()
        .optional()
        .describe('ID of a specific optimization to retrieve. Omit to list all.'),
      limit: z
        .number()
        .optional()
        .describe('Max number of optimizations to return when listing'),
      offset: z.number().optional().describe('Pagination offset when listing')
    })
  )
  .output(
    z.object({
      optimizations: z
        .array(
          z.object({
            optimizationProblemId: z.string().describe('Optimization problem ID'),
            state: z.number().optional().describe('Optimization state'),
            routeCount: z.number().optional().describe('Number of routes'),
            addressCount: z.number().optional().describe('Number of addresses'),
            routes: z.array(z.any()).optional().describe('Routes generated by optimization'),
            addresses: z.array(z.any()).optional().describe('Addresses in the optimization'),
            parameters: z.any().optional().describe('Optimization parameters')
          })
        )
        .describe('List of optimizations')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({ token: ctx.auth.token });

    if (ctx.input.optimizationProblemId) {
      let result = await client.getOptimization(ctx.input.optimizationProblemId);
      return {
        output: {
          optimizations: [
            {
              optimizationProblemId: result.optimization_problem_id,
              state: result.state,
              routeCount: result.routes?.length,
              addressCount: result.addresses?.length,
              routes: result.routes,
              addresses: result.addresses,
              parameters: result.parameters
            }
          ]
        },
        message: `Retrieved optimization **${result.optimization_problem_id}** (state: ${result.state}).`
      };
    }

    let result = await client.getOptimizations({
      limit: ctx.input.limit,
      offset: ctx.input.offset
    });
    let items = Array.isArray(result) ? result : result.optimizations || [];

    return {
      output: {
        optimizations: items.map((o: any) => ({
          optimizationProblemId: o.optimization_problem_id,
          state: o.state,
          routeCount: o.routes?.length,
          addressCount: o.addresses?.length,
          parameters: o.parameters
        }))
      },
      message: `Retrieved ${items.length} optimization(s).`
    };
  })
  .build();
