import { Slate } from 'slates';
import { spec } from './spec';
import {
  assignGroupItemToUser,
  assignKpiToUser,
  createCategory,
  createGroup,
  createGroupItem,
  createKpi,
  createKpiUnit,
  createUser,
  deleteCategory,
  deleteGroup,
  deleteGroupItem,
  deleteKpi,
  deleteKpiEntry,
  deleteKpiUnit,
  deleteUser,
  getKpi,
  getKpiReport,
  listCategories,
  listGroups,
  listKpiConfiguration,
  listKpiEntries,
  listKpis,
  listUserGroupItems,
  listUserKpis,
  listUsers,
  recordKpiEntriesBatch,
  recordKpiEntry,
  removeGroupItemFromUser,
  removeKpiFromUser,
  updateCategory,
  updateGroup,
  updateGroupItem,
  updateKpi,
  updateUser
} from './tools';
import { inboundWebhook, newKpiEntries } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listKpis,
    getKpi,
    createKpi,
    updateKpi,
    deleteKpi,
    listKpiEntries,
    recordKpiEntry,
    recordKpiEntriesBatch,
    deleteKpiEntry,
    listUsers,
    createUser,
    updateUser,
    deleteUser,
    listUserKpis,
    assignKpiToUser,
    removeKpiFromUser,
    listGroups,
    createGroup,
    updateGroup,
    deleteGroup,
    createGroupItem,
    updateGroupItem,
    deleteGroupItem,
    listUserGroupItems,
    assignGroupItemToUser,
    removeGroupItemFromUser,
    listCategories,
    createCategory,
    updateCategory,
    deleteCategory,
    getKpiReport,
    listKpiConfiguration,
    createKpiUnit,
    deleteKpiUnit
  ],
  triggers: [inboundWebhook, newKpiEntries]
});
