import { Slate } from 'slates';
import { spec } from './spec';
import {
  appendMessages,
  chunkText,
  createMemory,
  createPipe,
  createThread,
  deleteDocument,
  deleteMemory,
  deleteThread,
  generateEmbeddings,
  generateImages,
  getThread,
  listDocuments,
  listMemories,
  listMessages,
  listPipes,
  parseDocument,
  retrieveMemory,
  retryDocumentEmbeddings,
  runAgent,
  runPipe,
  updatePipe,
  updateThread,
  uploadDocument,
  webCrawl,
  webSearch
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    createPipe,
    listPipes,
    updatePipe,
    runPipe,
    createMemory,
    listMemories,
    deleteMemory,
    retrieveMemory,
    uploadDocument,
    listDocuments,
    deleteDocument,
    retryDocumentEmbeddings,
    createThread,
    getThread,
    updateThread,
    deleteThread,
    appendMessages,
    listMessages,
    parseDocument,
    runAgent,
    chunkText,
    generateEmbeddings,
    generateImages,
    webSearch,
    webCrawl
  ],
  triggers: []
});
