import { Slate } from 'slates';
import { spec } from './spec';
import {
  createApp,
  createGroup,
  createUser,
  deleteApp,
  deleteGroup,
  deleteUser,
  getGroup,
  getOrganization,
  getSourceControlConfig,
  getUser,
  getWorkflowRun,
  listAccessTokens,
  listApps,
  listEnvironments,
  listFolders,
  listGroups,
  listPermissions,
  listResources,
  listSpaces,
  listUsers,
  listWorkflows,
  manageFolder,
  manageGroupMembers,
  managePermissions,
  manageSpace,
  manageUserAttributes,
  updateApp,
  updateGroup,
  updateUser
} from './tools';
import { inboundWebhook, userChanges } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listUsers,
    getUser,
    createUser,
    updateUser,
    deleteUser,
    manageUserAttributes,
    listGroups,
    getGroup,
    createGroup,
    updateGroup,
    deleteGroup,
    manageGroupMembers,
    listApps,
    createApp,
    updateApp,
    deleteApp,
    listFolders,
    manageFolder,
    managePermissions,
    listPermissions,
    listResources,
    listEnvironments,
    listWorkflows,
    getWorkflowRun,
    listSpaces,
    manageSpace,
    getSourceControlConfig,
    getOrganization,
    listAccessTokens
  ],
  triggers: [inboundWebhook, userChanges]
});
