import { Slate } from 'slates';
import { spec } from './spec';
import {
  createBoard,
  createCategory,
  createExclusionRule,
  createPresetAlert,
  createView,
  deleteArchiveConfig,
  deleteBoard,
  deleteCategory,
  deleteExclusionRule,
  deletePresetAlert,
  deleteView,
  exportLogs,
  getArchiveConfig,
  getBoard,
  getIngestionStatus,
  getUsage,
  getView,
  ingestLogs,
  listBoards,
  listCategories,
  listExclusionRules,
  listPresetAlerts,
  listViews,
  resumeIngestion,
  saveArchiveConfig,
  suspendIngestion,
  updateCategory,
  updateExclusionRule,
  updatePresetAlert,
  updateView
} from './tools';
import { alertWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    ingestLogs,
    exportLogs,
    listViews,
    getView,
    createView,
    updateView,
    deleteView,
    listPresetAlerts,
    createPresetAlert,
    updatePresetAlert,
    deletePresetAlert,
    listBoards,
    getBoard,
    createBoard,
    deleteBoard,
    listExclusionRules,
    createExclusionRule,
    updateExclusionRule,
    deleteExclusionRule,
    getArchiveConfig,
    saveArchiveConfig,
    deleteArchiveConfig,
    listCategories,
    createCategory,
    updateCategory,
    deleteCategory,
    getIngestionStatus,
    suspendIngestion,
    resumeIngestion,
    getUsage
  ],
  triggers: [alertWebhook]
});
