import { Slate } from 'slates';
import { spec } from './spec';

import {
  addComment,
  createAccount,
  createAnalyticsExport,
  createAnalyticsReport,
  createContact,
  createLink,
  createMessageTemplate,
  createTag,
  deleteAccount,
  deleteContact,
  deleteMessageTemplate,
  deleteTag,
  getAccount,
  getAnalyticsExport,
  getChannel,
  getContact,
  getConversation,
  getInbox,
  getKnowledgeBaseContent,
  getTeam,
  getTeammate,
  listAccounts,
  listChannels,
  listContacts,
  listConversations,
  listEvents,
  listInboxes,
  listKnowledgeBases,
  listLinks,
  listMessageTemplates,
  listTags,
  listTeammates,
  listTeams,
  manageTeamMembers,
  mergeContacts,
  sendMessage,
  sendReply,
  updateAccount,
  updateContact,
  updateConversation,
  updateLink,
  updateMessageTemplate,
  updateTag,
  updateTeammate
} from './tools';

import { conversationEvent, webhookEvent } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listConversations.build(),
    getConversation.build(),
    updateConversation.build(),
    sendMessage.build(),
    sendReply.build(),
    listContacts.build(),
    getContact.build(),
    createContact.build(),
    updateContact.build(),
    deleteContact.build(),
    mergeContacts.build(),
    listAccounts.build(),
    getAccount.build(),
    createAccount.build(),
    updateAccount.build(),
    deleteAccount.build(),
    listTags.build(),
    createTag.build(),
    updateTag.build(),
    deleteTag.build(),
    addComment.build(),
    listTeammates.build(),
    getTeammate.build(),
    updateTeammate.build(),
    listChannels.build(),
    getChannel.build(),
    listInboxes.build(),
    getInbox.build(),
    listTeams.build(),
    getTeam.build(),
    manageTeamMembers.build(),
    listLinks.build(),
    createLink.build(),
    updateLink.build(),
    listMessageTemplates.build(),
    createMessageTemplate.build(),
    updateMessageTemplate.build(),
    deleteMessageTemplate.build(),
    createAnalyticsExport.build(),
    getAnalyticsExport.build(),
    createAnalyticsReport.build(),
    listKnowledgeBases.build(),
    getKnowledgeBaseContent.build(),
    listEvents.build()
  ],
  triggers: [conversationEvent.build(), webhookEvent.build()]
});
