import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { hellosignServiceError } from '../lib/errors';
import { spec } from '../spec';

let bulkSendJobSchema = z.object({
  bulkSendJobId: z.string().describe('Bulk send job ID'),
  total: z.number().optional().describe('Number of signature requests in the job'),
  isCreator: z.boolean().optional().describe('Whether the authenticated account created it'),
  createdAt: z.string().optional().describe('Creation timestamp (ISO 8601)')
});

let signatureRequestSummarySchema = z.object({
  signatureRequestId: z.string().describe('Signature request ID'),
  title: z.string().optional().describe('Title'),
  subject: z.string().optional().describe('Subject'),
  isComplete: z.boolean().optional().describe('Whether all signers completed'),
  isDeclined: z.boolean().optional().describe('Whether a signer declined'),
  hasError: z.boolean().optional().describe('Whether Dropbox Sign reports an error'),
  requesterEmailAddress: z.string().optional().describe('Requester email address')
});

let mapBulkSendJob = (job: any) => ({
  bulkSendJobId: job.bulk_send_job_id,
  total: job.total,
  isCreator: job.is_creator,
  createdAt: job.created_at ? new Date(job.created_at * 1000).toISOString() : undefined
});

let mapSignatureRequest = (request: any) => ({
  signatureRequestId: request.signature_request_id,
  title: request.title,
  subject: request.subject,
  isComplete: request.is_complete,
  isDeclined: request.is_declined,
  hasError: request.has_error,
  requesterEmailAddress: request.requester_email_address
});

export let manageBulkSendJobs = SlateTool.create(spec, {
  name: 'Manage Bulk Send Jobs',
  key: 'manage_bulk_send_jobs',
  description: `List Dropbox Sign bulk send jobs or retrieve a specific job with its generated signature requests.`,
  instructions: [
    'Use action "list" to page through accessible bulk send jobs.',
    'Use action "get" with bulkSendJobId to retrieve a job and its generated signature requests.'
  ],
  tags: {
    destructive: false,
    readOnly: true
  }
})
  .input(
    z.object({
      action: z.enum(['list', 'get']).describe('Action to perform'),
      bulkSendJobId: z.string().optional().describe('Required for action "get"'),
      page: z.number().optional().describe('Page number (default 1)'),
      pageSize: z.number().optional().describe('Results per page, 1-100 (default 20)')
    })
  )
  .output(
    z.object({
      action: z.string().describe('Action performed'),
      bulkSendJobs: z
        .array(bulkSendJobSchema)
        .optional()
        .describe('Bulk send jobs returned by list'),
      bulkSendJob: bulkSendJobSchema.optional().describe('Bulk send job returned by get'),
      signatureRequests: z
        .array(signatureRequestSummarySchema)
        .optional()
        .describe('Signature requests generated by the job'),
      page: z.number().optional().describe('Current page'),
      numPages: z.number().optional().describe('Total pages'),
      numResults: z.number().optional().describe('Total results')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({
      token: ctx.auth.token,
      authMethod: ctx.auth.authMethod
    });

    if (ctx.input.action === 'get') {
      if (!ctx.input.bulkSendJobId) {
        throw hellosignServiceError('bulkSendJobId is required for the "get" action.');
      }

      let result = await client.getBulkSendJob(
        ctx.input.bulkSendJobId,
        ctx.input.page,
        ctx.input.pageSize
      );
      let listInfo = result.list_info;

      return {
        output: {
          action: ctx.input.action,
          bulkSendJob: mapBulkSendJob(result.bulk_send_job),
          signatureRequests: (result.signature_requests || []).map(mapSignatureRequest),
          page: listInfo?.page,
          numPages: listInfo?.num_pages,
          numResults: listInfo?.num_results
        },
        message: `Bulk send job **${ctx.input.bulkSendJobId}** retrieved.`
      };
    }

    let result = await client.listBulkSendJobs(ctx.input.page, ctx.input.pageSize);
    return {
      output: {
        action: ctx.input.action,
        bulkSendJobs: result.bulkSendJobs.map(mapBulkSendJob),
        page: result.listInfo.page,
        numPages: result.listInfo.numPages,
        numResults: result.listInfo.numResults
      },
      message: `Found **${result.listInfo.numResults}** bulk send job(s). Showing page ${result.listInfo.page} of ${result.listInfo.numPages}.`
    };
  })
  .build();
