import { Slate } from 'slates';
import { spec } from './spec';
import {
  cancelPrediction,
  cancelTraining,
  createDeployment,
  createFile,
  createModel,
  createTraining,
  deleteDeployment,
  deleteFile,
  deleteModel,
  deleteModelVersion,
  downloadFile,
  getAccount,
  getCollection,
  getDeployment,
  getFile,
  getModel,
  getModelReadme,
  getModelVersion,
  getPrediction,
  getTraining,
  getWebhookSigningSecret,
  listCollections,
  listDeployments,
  listFiles,
  listHardware,
  listModelExamples,
  listModelVersions,
  listPredictions,
  listPublicModels,
  listTrainings,
  runPrediction,
  searchModels,
  updateDeployment,
  updateModel
} from './tools';
import { inboundWebhook, predictionCompleted, trainingCompleted } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    runPrediction,
    getPrediction,
    listPredictions,
    cancelPrediction,
    getModel,
    createModel,
    updateModel,
    deleteModel,
    listPublicModels,
    searchModels,
    listModelVersions,
    getModelVersion,
    deleteModelVersion,
    getModelReadme,
    listModelExamples,
    createTraining,
    getTraining,
    listTrainings,
    cancelTraining,
    createDeployment,
    getDeployment,
    listDeployments,
    updateDeployment,
    deleteDeployment,
    listCollections,
    getCollection,
    createFile,
    listFiles,
    getFile,
    downloadFile,
    deleteFile,
    listHardware,
    getWebhookSigningSecret,
    getAccount
  ],
  triggers: [inboundWebhook, predictionCompleted, trainingCompleted]
});
