import { Slate } from 'slates';
import { spec } from './spec';
import {
  cancelDowntime,
  deleteDashboard,
  deleteIncident,
  deleteMonitor,
  deleteSlo,
  getDashboard,
  getDowntime,
  getEvent,
  getIncident,
  getMetricMetadata,
  getMonitor,
  getSlo,
  listActiveMetrics,
  listDashboards,
  listDowntimes,
  listEvents,
  listHosts,
  listIncidents,
  listMonitors,
  listSlos,
  listSyntheticsTests,
  listUsers,
  manageDashboard,
  manageIncident,
  manageMonitor,
  manageSlo,
  manageSynthetics,
  muteMonitor,
  postEvent,
  queryMetrics,
  scheduleDowntime,
  searchLogs,
  submitLogs,
  submitMetrics,
  triggerSynthetics
} from './tools';
import {
  inboundWebhook,
  incidentUpdateTrigger,
  monitorAlertTrigger,
  newEventTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    queryMetrics,
    submitMetrics,
    listActiveMetrics,
    getMetricMetadata,
    manageMonitor,
    listMonitors,
    getMonitor,
    deleteMonitor,
    muteMonitor,
    manageDashboard,
    listDashboards,
    getDashboard,
    deleteDashboard,
    postEvent,
    listEvents,
    getEvent,
    manageIncident,
    listIncidents,
    getIncident,
    deleteIncident,
    searchLogs,
    submitLogs,
    manageSlo,
    listSlos,
    getSlo,
    deleteSlo,
    manageSynthetics,
    listSyntheticsTests,
    triggerSynthetics,
    listUsers,
    listHosts,
    scheduleDowntime,
    listDowntimes,
    getDowntime,
    cancelDowntime
  ],
  triggers: [inboundWebhook, monitorAlertTrigger, newEventTrigger, incidentUpdateTrigger]
});
