import { Slate } from 'slates';
import { spec } from './spec';
import {
  createConnection,
  createDestination,
  createGroup,
  createTeam,
  createTransformation,
  createWebhook,
  deleteConnection,
  deleteDestination,
  deleteGroup,
  deleteTeam,
  deleteTransformation,
  deleteUser,
  deleteWebhook,
  getConnection,
  getConnectionSchema,
  getConnectorType,
  getDestination,
  getGroup,
  getTeam,
  getTransformation,
  getUser,
  inviteUser,
  listConnections,
  listConnectorTypes,
  listDestinations,
  listGroups,
  listTeams,
  listTransformations,
  listUsers,
  listWebhooks,
  manageTeamMembership,
  reloadConnectionSchema,
  runTransformation,
  triggerSync,
  updateConnection,
  updateConnectionSchema,
  updateDestination,
  updateGroup,
  updateTeam,
  updateTransformation,
  updateUser,
  updateWebhook
} from './tools';
import { fivetranEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listGroups,
    getGroup,
    createGroup,
    updateGroup,
    deleteGroup,
    listConnections,
    getConnection,
    createConnection,
    updateConnection,
    deleteConnection,
    triggerSync,
    getConnectionSchema,
    updateConnectionSchema,
    reloadConnectionSchema,
    listDestinations,
    getDestination,
    createDestination,
    updateDestination,
    deleteDestination,
    listUsers,
    getUser,
    inviteUser,
    updateUser,
    deleteUser,
    listTeams,
    getTeam,
    createTeam,
    updateTeam,
    deleteTeam,
    manageTeamMembership,
    listTransformations,
    getTransformation,
    createTransformation,
    updateTransformation,
    deleteTransformation,
    runTransformation,
    listConnectorTypes,
    getConnectorType,
    listWebhooks,
    createWebhook,
    updateWebhook,
    deleteWebhook
  ],
  triggers: [fivetranEvents]
});
