import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  addCommentTool,
  createFilterTool,
  createIssueTool,
  createSprintTool,
  createVersionTool,
  deleteCommentTool,
  deleteFilterTool,
  deleteIssueLinkTool,
  deleteIssueTool,
  deleteVersionTool,
  deleteWorklogTool,
  getFilterTool,
  getIssueTool,
  getTransitionsTool,
  linkIssuesTool,
  listBoardsTool,
  listCommentsTool,
  listFavouriteFiltersTool,
  listIssueLinkTypesTool,
  listProjectsTool,
  listSprintsTool,
  listVersionsTool,
  listWorklogsTool,
  logWorkTool,
  moveIssuesToSprintTool,
  searchIssuesTool,
  searchUsersTool,
  updateCommentTool,
  updateFilterTool,
  updateIssueTool,
  updateVersionTool,
  updateWorklogTool
} from './tools';
import {
  boardEventsTrigger,
  commentEventsTrigger,
  issueEventsTrigger,
  projectEventsTrigger,
  sprintEventsTrigger,
  versionEventsTrigger,
  worklogEventsTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createIssueTool,
    getIssueTool,
    updateIssueTool,
    deleteIssueTool,
    searchIssuesTool,
    addCommentTool,
    updateCommentTool,
    deleteCommentTool,
    listCommentsTool,
    logWorkTool,
    listWorklogsTool,
    updateWorklogTool,
    deleteWorklogTool,
    listProjectsTool,
    listSprintsTool,
    createSprintTool,
    moveIssuesToSprintTool,
    listBoardsTool,
    listVersionsTool,
    createVersionTool,
    updateVersionTool,
    deleteVersionTool,
    linkIssuesTool,
    listIssueLinkTypesTool,
    deleteIssueLinkTool,
    createFilterTool,
    getFilterTool,
    updateFilterTool,
    deleteFilterTool,
    listFavouriteFiltersTool,
    searchUsersTool,
    getTransitionsTool
  ],
  triggers: [
    issueEventsTrigger,
    commentEventsTrigger,
    sprintEventsTrigger,
    projectEventsTrigger,
    versionEventsTrigger,
    worklogEventsTrigger,
    boardEventsTrigger
  ]
});
