import { Slate } from 'slates';
import { spec } from './spec';
import {
  deleteUsers,
  exportUsers,
  getCampaignAnalytics,
  getCampaignDetails,
  getCanvasAnalytics,
  getCanvasDetails,
  getCustomEventAnalytics,
  getKpiAnalytics,
  getPurchaseAnalytics,
  getSegmentAnalytics,
  getSegmentDetails,
  getSubscriptionStatus,
  listCampaigns,
  listCanvases,
  listCatalogs,
  listSegments,
  manageCatalogItems,
  manageCatalogs,
  manageContentBlocks,
  manageEmailList,
  manageEmailTemplates,
  manageSmsInvalidPhoneNumbers,
  manageUserIdentity,
  mergeUsers,
  scheduleMessage,
  sendMessage,
  trackUsers,
  triggerCampaign,
  triggerCanvas,
  updateSubscriptionStatus
} from './tools';
import { campaignActivity, emailBlocklistActivity, inboundWebhook } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    trackUsers,
    sendMessage,
    triggerCampaign,
    triggerCanvas,
    exportUsers,
    deleteUsers,
    mergeUsers,
    manageUserIdentity,
    listCampaigns,
    getCampaignDetails,
    getCampaignAnalytics,
    listCanvases,
    getCanvasDetails,
    getCanvasAnalytics,
    listSegments,
    getSegmentDetails,
    getSegmentAnalytics,
    updateSubscriptionStatus,
    getSubscriptionStatus,
    manageCatalogs,
    listCatalogs,
    manageCatalogItems,
    manageEmailList,
    manageSmsInvalidPhoneNumbers,
    manageEmailTemplates,
    manageContentBlocks,
    getKpiAnalytics,
    getCustomEventAnalytics,
    getPurchaseAnalytics,
    scheduleMessage
  ],
  triggers: [inboundWebhook, campaignActivity, emailBlocklistActivity]
});
