import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

export let detectAiImage = SlateTool.create(spec, {
  name: 'Detect AI Image',
  key: 'detect_ai_image',
  description: `Analyzes an image to determine whether it was generated by AI or created by a human. Returns a human score (0-100), AI and human probability percentages, and extracts provenance metadata including C2PA content credentials, EXIF/IPTC data, and AI watermark detection.

Identifies images from major AI generators including ChatGPT Images, Midjourney, Stable Diffusion, Adobe Firefly, Ideogram, Leonardo, Runway, and others. Also detects manipulated faces, identity swaps, synthetic personas, and deepfakes.`,
  constraints: [
    'Image must be publicly accessible via URL.',
    'Supported formats: JPG, JPEG, PNG, WEBP.',
    'Minimum resolution: 256x256 pixels.',
    'Costs 300 credits per image.'
  ],
  tags: {
    destructive: false,
    readOnly: true
  }
})
  .input(
    z.object({
      imageUrl: z
        .string()
        .describe('Publicly accessible URL of the image to analyze (JPG, JPEG, PNG, or WEBP)'),
      version: z
        .string()
        .optional()
        .describe('Detection model version: "1", "2", "3", or "latest"')
    })
  )
  .output(
    z.object({
      humanScore: z
        .number()
        .describe('Human likelihood score (0-100). Higher means more likely human-created'),
      humanProbability: z
        .number()
        .describe('Probability the image was created by a human (percentage)'),
      aiProbability: z
        .number()
        .describe('Probability the image was generated by AI (percentage)'),
      modelVersion: z.string().describe('Detection model version used'),
      mimeType: z.string().describe('MIME type of the analyzed image'),
      c2pa: z.unknown().nullable().describe('C2PA content provenance metadata, if present'),
      exif: z.unknown().nullable().describe('EXIF/IPTC metadata extracted from the image'),
      imageMetadata: z.unknown().nullable().describe('Additional image technical metadata'),
      aiWatermarkDetected: z
        .boolean()
        .describe('Whether an AI watermark was detected in the image'),
      aiWatermarkIssuers: z
        .unknown()
        .nullable()
        .describe('Details about detected AI watermark issuers'),
      creditsUsed: z.number().describe('Number of credits consumed'),
      creditsRemaining: z.number().describe('Remaining account credits')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({ token: ctx.auth.token });

    let result = await client.detectImage({
      url: ctx.input.imageUrl,
      version: ctx.input.version
    });

    return {
      output: {
        humanScore: result.score,
        humanProbability: result.human_probability,
        aiProbability: result.ai_probability,
        modelVersion: result.version,
        mimeType: result.mime_type,
        c2pa: result.c2pa ?? null,
        exif: result.exif ?? null,
        imageMetadata: result.metadata ?? null,
        aiWatermarkDetected: result.ai_watermark_detected ?? false,
        aiWatermarkIssuers: result.ai_watermark_issuers ?? null,
        creditsUsed: result.credits_used,
        creditsRemaining: result.credits_remaining
      },
      message: `AI image detection complete. **Human score: ${result.score}/100** (${result.score >= 70 ? 'likely human-created' : result.score >= 30 ? 'uncertain origin' : 'likely AI-generated'}). AI probability: ${result.ai_probability}%, Human probability: ${result.human_probability}%. AI watermark detected: ${result.ai_watermark_detected ? 'yes' : 'no'}. Credits used: ${result.credits_used}.`
    };
  });
