import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

export let detectAiText = SlateTool.create(spec, {
  name: 'Detect AI Text',
  key: 'detect_ai_text',
  description: `Analyzes text content to determine if it was written by a human or generated by AI. Returns a human score (0-100) where higher values indicate more likely human-written content. Can also provide per-sentence scores for granular analysis, a readability score, and detection of obfuscation attacks such as zero-width spaces or homoglyph substitutions.

Accepts plain text, a publicly accessible file URL (.pdf, .doc, .docx), or a website URL as input. Supports 12+ languages with auto-detection.`,
  instructions: [
    'Provide exactly one of: text, fileUrl, or websiteUrl. If multiple are provided, websiteUrl takes priority over fileUrl, which takes priority over text.',
    'For reliable results, text should be at least 600 characters. The minimum accepted length is 300 characters.'
  ],
  constraints: [
    'Text must be between 300 and 150,000 characters.',
    'Costs 1 credit per word processed.'
  ],
  tags: {
    destructive: false,
    readOnly: true
  }
})
  .input(
    z.object({
      text: z
        .string()
        .optional()
        .describe('Plain text content to analyze (300-150,000 characters)'),
      fileUrl: z
        .string()
        .optional()
        .describe('Publicly accessible URL to a .pdf, .doc, or .docx file'),
      websiteUrl: z.string().optional().describe('Public website URL to scan'),
      version: z
        .string()
        .optional()
        .describe('Detection model version (e.g. "4.14" or "latest")'),
      sentences: z
        .boolean()
        .optional()
        .describe('Whether to include per-sentence AI scores (defaults to true)'),
      language: z
        .string()
        .optional()
        .describe('Two-letter language code (e.g. "en", "fr"), or "auto" for auto-detection')
    })
  )
  .output(
    z.object({
      humanScore: z
        .number()
        .describe('Human likelihood score (0-100). Higher means more likely human-written'),
      readabilityScore: z.number().describe('Readability score of the content (0-100)'),
      sentences: z
        .array(
          z.object({
            text: z.string().describe('Sentence text'),
            score: z.number().describe('Human likelihood score for this sentence (0-100)')
          })
        )
        .optional()
        .describe('Per-sentence AI detection scores'),
      inputType: z.string().describe('Input type used: text, file, or website'),
      attackDetected: z
        .object({
          zeroWidthSpace: z
            .boolean()
            .describe('Whether zero-width space obfuscation was detected'),
          homoglyphAttack: z
            .boolean()
            .describe('Whether homoglyph attack obfuscation was detected')
        })
        .describe('Obfuscation attack detection results'),
      modelVersion: z.string().describe('Detection model version used'),
      language: z.string().describe('Detected or specified language code'),
      creditsUsed: z.number().describe('Number of credits consumed'),
      creditsRemaining: z.number().describe('Remaining account credits')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({ token: ctx.auth.token });

    let result = await client.detectText({
      text: ctx.input.text,
      file: ctx.input.fileUrl,
      website: ctx.input.websiteUrl,
      version: ctx.input.version,
      sentences: ctx.input.sentences,
      language: ctx.input.language
    });

    let sentenceScores = Array.isArray(result.sentences) ? result.sentences : undefined;

    return {
      output: {
        humanScore: result.score,
        readabilityScore: result.readability_score,
        sentences: sentenceScores,
        inputType: result.input,
        attackDetected: {
          zeroWidthSpace: result.attack_detected?.zero_width_space ?? false,
          homoglyphAttack: result.attack_detected?.homoglyph_attack ?? false
        },
        modelVersion: result.version,
        language: result.language,
        creditsUsed: result.credits_used,
        creditsRemaining: result.credits_remaining
      },
      message: `AI text detection complete. **Human score: ${result.score}/100** (${result.score >= 70 ? 'likely human' : result.score >= 30 ? 'mixed/uncertain' : 'likely AI'}). Readability: ${result.readability_score}/100. Language: ${result.language}. ${sentenceScores ? `Analyzed ${sentenceScores.length} sentences.` : ''} Credits used: ${result.credits_used}.`
    };
  });
