import { Slate } from 'slates';
import { spec } from './spec';
import {
  bulkDelete,
  createSegment,
  deleteSegment,
  getAccount,
  getBulkDeleteStatus,
  getFeature,
  getGuide,
  getMetadataSchema,
  getPage,
  getReport,
  getSegmentVisitorExport,
  getTrackType,
  getVisitor,
  listFeatures,
  listGuides,
  listPages,
  listReports,
  listSegments,
  listTrackTypes,
  patchSegmentVisitors,
  runAggregation,
  sendTrackEvent,
  startSegmentVisitorExport,
  updateAccountMetadata,
  updateSegment,
  updateVisitorMetadata,
  verifyIntegrationKey
} from './tools';
import { pendoEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    getVisitor,
    getAccount,
    verifyIntegrationKey,
    updateVisitorMetadata,
    updateAccountMetadata,
    listGuides,
    getGuide,
    listPages,
    getPage,
    listFeatures,
    getFeature,
    listTrackTypes,
    getTrackType,
    sendTrackEvent,
    listSegments,
    createSegment,
    updateSegment,
    patchSegmentVisitors,
    startSegmentVisitorExport,
    getSegmentVisitorExport,
    deleteSegment,
    getBulkDeleteStatus,
    runAggregation,
    bulkDelete,
    listReports,
    getReport,
    getMetadataSchema
  ],
  triggers: [pendoEvents]
});
