import { Slate } from 'slates';
import { spec } from './spec';
import {
  addAttachmentsToPdf,
  addBarcodeToPdf,
  addFormFieldToPdf,
  addHeaderFooter,
  addMarginToPdf,
  addPageNumbers,
  addWatermark,
  classifyDocument,
  compressPdf,
  convertFromPdf,
  convertToPdf,
  createBarcodeImage,
  createImagesFromPdf,
  createPdfA,
  deletePages,
  extractAttachmentsFromPdf,
  extractContent,
  extractPages,
  extractPdfFormData,
  fillPdfForm,
  findAndReplaceText,
  flattenPdf,
  generateDocument,
  getPdfMetadata,
  linearizePdf,
  mergePdfs,
  ocrPdf,
  parseDocument,
  protectPdf,
  readBarcodeFromPdf,
  repairPdf,
  rotatePdf,
  runWorkflow,
  signPdf,
  splitPdf,
  unlockPdf
} from './tools';

import { inboundWebhook } from './triggers/inbound-webhook';

export let provider = Slate.create({
  spec,
  tools: [
    convertToPdf,
    convertFromPdf,
    mergePdfs,
    splitPdf,
    compressPdf,
    extractContent,
    addWatermark,
    addMarginToPdf,
    addAttachmentsToPdf,
    extractAttachmentsFromPdf,
    addBarcodeToPdf,
    createBarcodeImage,
    readBarcodeFromPdf,
    protectPdf,
    unlockPdf,
    ocrPdf,
    getPdfMetadata,
    createPdfA,
    extractPages,
    deletePages,
    rotatePdf,
    addPageNumbers,
    findAndReplaceText,
    flattenPdf,
    repairPdf,
    linearizePdf,
    fillPdfForm,
    addFormFieldToPdf,
    extractPdfFormData,
    signPdf,
    parseDocument,
    generateDocument,
    addHeaderFooter,
    createImagesFromPdf,
    classifyDocument,
    runWorkflow
  ],
  triggers: [inboundWebhook]
});
