import { Slate } from 'slates';
import { spec } from './spec';
import {
  addPermissionTool,
  createDocTool,
  createFolderTool,
  createPageTool,
  deleteDocTool,
  deleteFolderTool,
  deletePageTool,
  deleteRowsTool,
  getDocAnalyticsTool,
  getDocTool,
  getFormulasControlsTool,
  getMutationStatusTool,
  getPageContentTool,
  getRowTool,
  listColumnsTool,
  listDocsTool,
  listFoldersTool,
  listPagesTool,
  listPermissionsTool,
  listRowsTool,
  listTablesTool,
  publishDocTool,
  pushButtonTool,
  removePermissionTool,
  resolveUrlTool,
  triggerAutomationTool,
  unpublishDocTool,
  updateDocTool,
  updateFolderTool,
  updatePageTool,
  updateRowTool,
  upsertRowsTool
} from './tools';
import { rowChangesTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listDocsTool,
    getDocTool,
    createDocTool,
    updateDocTool,
    deleteDocTool,
    listFoldersTool,
    createFolderTool,
    updateFolderTool,
    deleteFolderTool,
    listPagesTool,
    createPageTool,
    updatePageTool,
    deletePageTool,
    getPageContentTool,
    listTablesTool,
    listColumnsTool,
    listRowsTool,
    getRowTool,
    upsertRowsTool,
    updateRowTool,
    deleteRowsTool,
    pushButtonTool,
    getFormulasControlsTool,
    triggerAutomationTool,
    listPermissionsTool,
    addPermissionTool,
    removePermissionTool,
    publishDocTool,
    unpublishDocTool,
    resolveUrlTool,
    getMutationStatusTool,
    getDocAnalyticsTool
  ],
  triggers: [rowChangesTrigger]
});
