import { SlateTool } from 'slates';
import { z } from 'zod';
import { Client } from '../lib/client';
import { spec } from '../spec';

export let listImages = SlateTool.create(spec, {
  name: 'List Images',
  key: 'list_images',
  description: `Retrieve a list of all images previously generated by your account. Returns image metadata including URLs, creation dates, and rendering parameters.`,
  tags: {
    destructive: false,
    readOnly: true
  }
})
  .input(
    z.object({
      page: z.number().optional().describe('Page number for pagination'),
      perPage: z.number().optional().describe('Number of images per page')
    })
  )
  .output(
    z.object({
      images: z
        .array(
          z.object({
            imageId: z.string().describe('Unique identifier for the image'),
            url: z.string().describe('Permanent CDN-cached URL of the image'),
            createdAt: z.string().describe('Timestamp when the image was created'),
            html: z.string().optional().describe('HTML markup used to generate the image'),
            css: z.string().optional().describe('CSS styling applied to the image'),
            googleFonts: z.string().optional().describe('Google Fonts used'),
            msDelay: z.number().optional().describe('Render delay in milliseconds'),
            deviceScale: z.number().optional().describe('Device scale factor'),
            selector: z.string().optional().describe('CSS selector used for cropping'),
            viewportWidth: z.number().optional().describe('Viewport width used'),
            viewportHeight: z.number().optional().describe('Viewport height used'),
            templateId: z
              .string()
              .optional()
              .describe('Template ID if generated from a template'),
            templateVersion: z.number().optional().describe('Template version used')
          })
        )
        .describe('List of generated images')
    })
  )
  .handleInvocation(async ctx => {
    let client = new Client({
      userId: ctx.auth.userId,
      token: ctx.auth.token
    });

    let images = await client.listImages(ctx.input.page, ctx.input.perPage);

    return {
      output: { images },
      message: `Retrieved **${images.length}** image(s).`
    };
  })
  .build();
