import { Slate } from 'slates';
import { spec } from './spec';
import {
  completeTask,
  convertLead,
  deleteAccount,
  deleteAppointment,
  deleteContact,
  deleteDeal,
  deleteLead,
  deleteNote,
  deleteSalesActivity,
  deleteTask,
  filterContacts,
  getAccount,
  getAppointment,
  getContact,
  getDeal,
  getFields,
  getLead,
  getSalesActivity,
  getTask,
  listAccounts,
  listAppointments,
  listContacts,
  listDeals,
  listFilters,
  listLeads,
  listSalesActivities,
  listSelectors,
  listTasks,
  manageAccount,
  manageAppointment,
  manageContact,
  manageDeal,
  manageLead,
  manageNote,
  manageSalesActivity,
  manageTask,
  searchRecords
} from './tools';
import {
  accountChanges,
  contactChanges,
  dealChanges,
  inboundWebhook,
  leadChanges
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    manageLead,
    getLead,
    listLeads,
    deleteLead,
    convertLead,
    manageContact,
    getContact,
    listContacts,
    deleteContact,
    manageAccount,
    getAccount,
    listAccounts,
    deleteAccount,
    manageDeal,
    getDeal,
    listDeals,
    deleteDeal,
    manageTask,
    getTask,
    completeTask,
    listTasks,
    deleteTask,
    manageAppointment,
    getAppointment,
    listAppointments,
    deleteAppointment,
    manageNote,
    deleteNote,
    manageSalesActivity,
    getSalesActivity,
    listSalesActivities,
    deleteSalesActivity,
    searchRecords,
    filterContacts,
    listFilters,
    listSelectors,
    getFields
  ],
  triggers: [inboundWebhook, contactChanges, leadChanges, dealChanges, accountChanges]
});
