import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCommentTool,
  createChannelTool,
  createFolderTool,
  createShowcaseTool,
  deleteChannelTool,
  deleteFolderTool,
  deleteShowcaseTool,
  deleteVideoTool,
  downloadVideoTool,
  editShowcaseTool,
  editVideoTool,
  getChannelTool,
  getFolderTool,
  getShowcaseTool,
  getShowcaseVideosTool,
  getUserTool,
  getVideoTool,
  likeVideoTool,
  listCategoriesTool,
  listCategoryVideosTool,
  listChannelsTool,
  listChannelVideosTool,
  listCommentsTool,
  listFoldersTool,
  listFolderVideosTool,
  listLikedVideosTool,
  listShowcasesTool,
  listVideosTool,
  manageChannelVideoTool,
  manageFolderVideoTool,
  manageShowcaseVideoTool,
  renewVideoFile,
  searchVideosTool
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    getVideoTool,
    listVideosTool,
    searchVideosTool,
    editVideoTool,
    deleteVideoTool,
    listCommentsTool,
    addCommentTool,
    getUserTool,
    listLikedVideosTool,
    likeVideoTool,
    listShowcasesTool,
    createShowcaseTool,
    editShowcaseTool,
    deleteShowcaseTool,
    getShowcaseVideosTool,
    manageShowcaseVideoTool,
    listFoldersTool,
    createFolderTool,
    deleteFolderTool,
    listFolderVideosTool,
    manageFolderVideoTool,
    listChannelsTool,
    getChannelTool,
    createChannelTool,
    deleteChannelTool,
    listChannelVideosTool,
    manageChannelVideoTool,
    listCategoriesTool,
    listCategoryVideosTool,
    getFolderTool,
    getShowcaseTool,
    downloadVideoTool,
    renewVideoFile
  ],
  triggers: []
});
