import { Slate } from 'slates';
import { spec } from './spec';
import {
  aggregateMember,
  checkBalance,
  createMember,
  createUser,
  deleteMember,
  deleteUser,
  enhanceTransactions,
  extendHistory,
  fetchStatements,
  identifyMember,
  listAccountNumbers,
  listAccountOwners,
  listAccounts,
  listCategories,
  listHoldings,
  listInsights,
  listMembers,
  listStatements,
  listTransactions,
  listUsers,
  readAccount,
  readInstitution,
  readMemberStatus,
  readTransaction,
  readUser,
  requestWidgetUrl,
  resumeMfaChallenge,
  searchInstitutions,
  updateMember,
  updateUser,
  verifyMember
} from './tools';
import {
  accountEvents,
  aggregationEvents,
  connectionStatusEvents,
  holdingEvents,
  memberEvents,
  statementEvents,
  transactionEvents,
  userEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createUser,
    listUsers,
    readUser,
    updateUser,
    deleteUser,
    createMember,
    listMembers,
    readMemberStatus,
    updateMember,
    deleteMember,
    aggregateMember,
    resumeMfaChallenge,
    listAccounts,
    readAccount,
    listAccountNumbers,
    listTransactions,
    readTransaction,
    searchInstitutions,
    readInstitution,
    listHoldings,
    listStatements,
    fetchStatements,
    verifyMember,
    identifyMember,
    listAccountOwners,
    checkBalance,
    extendHistory,
    enhanceTransactions,
    requestWidgetUrl,
    listInsights,
    listCategories
  ],
  triggers: [
    aggregationEvents,
    connectionStatusEvents,
    memberEvents,
    accountEvents,
    transactionEvents,
    statementEvents,
    userEvents,
    holdingEvents
  ]
});
