import { Slate } from 'slates';
import { spec } from './spec';
import {
  addTicketComment,
  addTicketThread,
  createTicket,
  deleteAccount,
  deleteArticle,
  deleteContact,
  deleteTask,
  deleteTicket,
  getTicket,
  listAccounts,
  listAgents,
  listArticles,
  listContacts,
  listDepartments,
  listTasks,
  listTickets,
  manageAccount,
  manageArticle,
  manageContact,
  manageTask,
  manageTimeEntry,
  search,
  updateTicket
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    createTicket,
    getTicket,
    updateTicket,
    listTickets,
    deleteTicket,
    addTicketComment,
    addTicketThread,
    manageContact,
    listContacts,
    deleteContact,
    manageAccount,
    listAccounts,
    deleteAccount,
    search,
    manageArticle,
    listArticles,
    deleteArticle,
    listAgents,
    manageTask,
    listTasks,
    deleteTask,
    manageTimeEntry,
    listDepartments
  ],
  triggers: []
});
