import { Slate } from 'slates';
import { spec } from './spec';
import {
  createBooking,
  createContact,
  createCoupon,
  createInvoice,
  createPayment,
  createProduct,
  createRefund,
  createReview,
  createTask,
  deleteCalendarEvent,
  deleteContact,
  deleteCoupon,
  getBooking,
  getCalendarEvent,
  getContact,
  getProduct,
  listBookings,
  listCalendarEvents,
  listContacts,
  listCoupons,
  listInvoices,
  listMessages,
  listPayments,
  listProducts,
  listReviews,
  listTasks,
  updateBooking,
  updateCalendarEvent,
  updateContact,
  updateCoupon,
  updateProduct,
  updateTask
} from './tools';
import {
  bookingEvents,
  calendarEventEvents,
  calendarEventTaskEvents,
  contactEvents,
  invoiceEvents,
  memberEvents,
  paymentEvents,
  productEvents
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createBooking,
    getBooking,
    listBookings,
    updateBooking,
    listCalendarEvents,
    getCalendarEvent,
    updateCalendarEvent,
    deleteCalendarEvent,
    listContacts,
    getContact,
    createContact,
    updateContact,
    deleteContact,
    listProducts,
    getProduct,
    createProduct,
    updateProduct,
    listInvoices,
    createInvoice,
    listPayments,
    createPayment,
    createRefund,
    listCoupons,
    createCoupon,
    updateCoupon,
    deleteCoupon,
    listTasks,
    createTask,
    updateTask,
    listReviews,
    createReview,
    listMessages
  ],
  triggers: [
    bookingEvents,
    calendarEventEvents,
    calendarEventTaskEvents,
    contactEvents,
    invoiceEvents,
    paymentEvents,
    productEvents,
    memberEvents
  ]
});
