import { Slate } from 'slates';
import { spec } from './spec';
import {
  assignFeatureToReleaseTool,
  createCompanyTool,
  createFeatureTool,
  createInitiativeTool,
  createKeyResultTool,
  createNoteTool,
  createObjectiveTool,
  createReleaseTool,
  createUserTool,
  deleteFeatureTool,
  deleteInitiativeTool,
  deleteKeyResultTool,
  deleteNoteTool,
  deleteObjectiveTool,
  deleteReleaseTool,
  deleteUserTool,
  getCustomFieldValuesTool,
  getFeatureTool,
  getInitiativeTool,
  getNoteTool,
  getObjectiveTool,
  listCompaniesTool,
  listCustomFieldsTool,
  listFeatureStatusesTool,
  listFeaturesTool,
  listInitiativesTool,
  listKeyResultsTool,
  listNotesTool,
  listObjectivesTool,
  listProductHierarchyTool,
  listReleasesTool,
  listUsersTool,
  setCustomFieldValueTool,
  updateCompanyTool,
  updateFeatureTool,
  updateInitiativeTool,
  updateKeyResultTool,
  updateObjectiveTool,
  updateReleaseTool,
  updateUserTool
} from './tools';
import {
  componentEventsTrigger,
  featureEventsTrigger,
  noteEventsTrigger,
  productEventsTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listFeaturesTool,
    getFeatureTool,
    createFeatureTool,
    updateFeatureTool,
    deleteFeatureTool,
    listFeatureStatusesTool,
    listNotesTool,
    getNoteTool,
    createNoteTool,
    deleteNoteTool,
    listProductHierarchyTool,
    listCompaniesTool,
    createCompanyTool,
    updateCompanyTool,
    listUsersTool,
    createUserTool,
    updateUserTool,
    deleteUserTool,
    listReleasesTool,
    createReleaseTool,
    updateReleaseTool,
    deleteReleaseTool,
    assignFeatureToReleaseTool,
    listObjectivesTool,
    getObjectiveTool,
    createObjectiveTool,
    updateObjectiveTool,
    deleteObjectiveTool,
    listKeyResultsTool,
    createKeyResultTool,
    updateKeyResultTool,
    deleteKeyResultTool,
    listInitiativesTool,
    getInitiativeTool,
    createInitiativeTool,
    updateInitiativeTool,
    deleteInitiativeTool,
    listCustomFieldsTool,
    getCustomFieldValuesTool,
    setCustomFieldValueTool
  ],
  triggers: [
    featureEventsTrigger,
    noteEventsTrigger,
    componentEventsTrigger,
    productEventsTrigger
  ]
});
