import { Slate } from 'slates';
import { spec } from './spec';
import {
  archivePipeline,
  createAnnotation,
  createBuild,
  createPipeline,
  deleteAnnotation,
  deletePipeline,
  downloadArtifact,
  downloadJobLog,
  getAgent,
  getBuild,
  getJobLog,
  getPipeline,
  listAgents,
  listAnnotations,
  listArtifacts,
  listBuilds,
  listClusters,
  listOrganizations,
  listPipelines,
  listTeams,
  manageBuild,
  manageJob,
  stopAgent,
  updatePipeline,
  whoAmI
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    whoAmI.build(),
    listOrganizations.build(),
    listClusters.build(),
    listTeams.build(),
    getAgent.build(),
    listAnnotations.build(),
    deleteAnnotation.build(),
    downloadJobLog.build(),
    downloadArtifact.build(),
    listPipelines.build(),
    getPipeline.build(),
    createPipeline.build(),
    updatePipeline.build(),
    deletePipeline.build(),
    archivePipeline.build(),
    listBuilds.build(),
    getBuild.build(),
    createBuild.build(),
    manageBuild.build(),
    manageJob.build(),
    getJobLog.build(),
    listAgents.build(),
    stopAgent.build(),
    listArtifacts.build(),
    createAnnotation.build()
  ],
  triggers: []
});
