import { Slate } from 'slates';
import { spec } from './spec';
import {
  createAgent,
  createBatchCall,
  createKnowledgeBase,
  createRetellLlm,
  createWebCall,
  deleteAgent,
  deleteCall,
  deleteKnowledgeBase,
  deletePhoneNumber,
  deleteRetellLlm,
  downloadCallRecording,
  getAgent,
  getCall,
  getConcurrency,
  getFileUrl,
  getKnowledgeBase,
  getPhoneNumber,
  getRetellLlm,
  listAgents,
  listCalls,
  listKnowledgeBases,
  listPhoneNumbers,
  listRetellLlms,
  listVoices,
  makePhoneCall,
  publishAgent,
  purchasePhoneNumber,
  updateAgent,
  updatePhoneNumber,
  updateRetellLlm
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    createKnowledgeBase,
    createRetellLlm,
    getRetellLlm,
    listRetellLlms,
    updateRetellLlm,
    deleteRetellLlm,
    publishAgent,
    downloadCallRecording,
    getFileUrl,
    listAgents,
    getAgent,
    createAgent,
    updateAgent,
    deleteAgent,
    makePhoneCall,
    createWebCall,
    getCall,
    listCalls,
    deleteCall,
    createBatchCall,
    listPhoneNumbers,
    getPhoneNumber,
    purchasePhoneNumber,
    updatePhoneNumber,
    deletePhoneNumber,
    listKnowledgeBases,
    getKnowledgeBase,
    deleteKnowledgeBase,
    listVoices,
    getConcurrency
  ],
  triggers: []
});
