import { Slate } from 'slates';
import { spec } from './spec';

import {
  createBillTool,
  createContact,
  createCreditNoteTool,
  createEstimateTool,
  createExpenseTool,
  createInvoiceTool,
  createItemTool,
  createJournalEntryTool,
  createProjectTool,
  createPurchaseOrderTool,
  createSalesOrderTool,
  deleteContact,
  deleteInvoiceTool,
  getContact,
  getInvoiceTool,
  listBankAccountsTool,
  listBankTransactionsTool,
  listBillsTool,
  listChartOfAccountsTool,
  listContacts,
  listCreditNotesTool,
  listCustomerPaymentsTool,
  listEstimatesTool,
  listExpensesTool,
  listInvoicesTool,
  listItemsTool,
  listProjectsTool,
  listPurchaseOrdersTool,
  listSalesOrdersTool,
  logTimeEntryTool,
  recordCustomerPaymentTool,
  recordVendorPaymentTool,
  updateBillStatusTool,
  updateContact,
  updateEstimateStatusTool,
  updateInvoiceTool,
  updateItemTool
} from './tools';

import {
  billEventsTrigger,
  contactEventsTrigger,
  customerPaymentEventsTrigger,
  expenseEventsTrigger,
  inboundWebhook,
  invoiceEventsTrigger
} from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listContacts,
    getContact,
    createContact,
    updateContact,
    deleteContact,
    listInvoicesTool,
    getInvoiceTool,
    createInvoiceTool,
    updateInvoiceTool,
    deleteInvoiceTool,
    listEstimatesTool,
    createEstimateTool,
    updateEstimateStatusTool,
    listExpensesTool,
    createExpenseTool,
    recordCustomerPaymentTool,
    recordVendorPaymentTool,
    listCustomerPaymentsTool,
    listItemsTool,
    createItemTool,
    updateItemTool,
    listBillsTool,
    createBillTool,
    updateBillStatusTool,
    listPurchaseOrdersTool,
    createPurchaseOrderTool,
    listProjectsTool,
    createProjectTool,
    logTimeEntryTool,
    listBankAccountsTool,
    listBankTransactionsTool,
    listChartOfAccountsTool,
    createJournalEntryTool,
    listCreditNotesTool,
    createCreditNoteTool,
    listSalesOrdersTool,
    createSalesOrderTool
  ],
  triggers: [
    inboundWebhook,
    invoiceEventsTrigger,
    contactEventsTrigger,
    expenseEventsTrigger,
    billEventsTrigger,
    customerPaymentEventsTrigger
  ]
});
