import { Slate } from 'slates';
import { spec } from './spec';

import {
  createClient,
  createExpense,
  createInvoice,
  createProject,
  createTag,
  createTask,
  createTimeEntry,
  createTimeOffRequest,
  createUserGroup,
  deleteClient,
  deleteExpense,
  deleteInvoice,
  deleteProject,
  deleteTag,
  deleteTask,
  deleteTimeEntry,
  deleteUserGroup,
  generateDetailedReport,
  generateSummaryReport,
  getClients,
  getCurrentUser,
  getInvoices,
  getProjects,
  getTags,
  getTasks,
  getTimeEntries,
  getTimeOffPolicies,
  getTimeOffRequests,
  getUserGroups,
  getUsers,
  getWorkspace,
  stopTimer,
  updateClient,
  updateInvoice,
  updateProject,
  updateTag,
  updateTask,
  updateTimeEntry,
  updateTimeOffRequestStatus,
  updateUserGroup
} from './tools';

export let provider = Slate.create({
  spec,
  tools: [
    createTimeEntry,
    getTimeEntries,
    updateTimeEntry,
    deleteTimeEntry,
    stopTimer,
    createProject,
    updateProject,
    deleteProject,
    getProjects,
    createTask,
    updateTask,
    deleteTask,
    getTasks,
    createClient,
    updateClient,
    deleteClient,
    getClients,
    createTag,
    updateTag,
    deleteTag,
    getTags,
    getUsers,
    getCurrentUser,
    generateDetailedReport,
    generateSummaryReport,
    createExpense,
    deleteExpense,
    getInvoices,
    createInvoice,
    updateInvoice,
    deleteInvoice,
    createUserGroup,
    getUserGroups,
    updateUserGroup,
    deleteUserGroup,
    getTimeOffRequests,
    createTimeOffRequest,
    updateTimeOffRequestStatus,
    getTimeOffPolicies,
    getWorkspace
  ],
  triggers: []
});
