import { SlateTool } from 'slates';
import { z } from 'zod';
import { RadarClient } from '../lib/client';
import { spec } from '../spec';

export let trackUserTool = SlateTool.create(spec, {
  name: 'Track User Location',
  key: 'track_user_location',
  description: `Submit a location update for a user/device. This creates or updates the user record and generates location-based events (geofence entries/exits, place visits, trip updates, etc.). Returns the updated user and any generated events.`,
  constraints: ['Rate limited to 1 request per second per device.'],
  tags: {
    destructive: false,
    readOnly: false
  }
})
  .input(
    z.object({
      deviceId: z.string().describe('Unique device identifier'),
      latitude: z.number().describe('Current latitude'),
      longitude: z.number().describe('Current longitude'),
      accuracy: z.number().describe('Location accuracy in meters'),
      userId: z
        .string()
        .optional()
        .describe('Your internal user ID to associate with this device'),
      foreground: z.boolean().optional().describe('Whether the app is in the foreground'),
      stopped: z.boolean().optional().describe('Whether the user is stopped (not moving)'),
      description: z.string().optional().describe('User description'),
      metadata: z.record(z.string(), z.string()).optional().describe('Custom user metadata'),
      deviceType: z.string().optional().describe('Device type: iOS, Android, or Web'),
      updatedAt: z.string().optional().describe('ISO 8601 timestamp for the location update')
    })
  )
  .output(
    z.object({
      userId: z.string().optional().describe('User ID'),
      radarId: z.string().describe('Radar internal user ID'),
      eventsGenerated: z
        .number()
        .describe('Number of events generated from this location update'),
      events: z
        .array(
          z.object({
            eventId: z.string().describe('Event ID'),
            type: z.string().describe('Event type')
          })
        )
        .describe('Events generated by this location update')
    })
  )
  .handleInvocation(async ctx => {
    let client = new RadarClient({ token: ctx.auth.token });
    let result = await client.trackUser({
      deviceId: ctx.input.deviceId,
      latitude: ctx.input.latitude,
      longitude: ctx.input.longitude,
      accuracy: ctx.input.accuracy,
      userId: ctx.input.userId,
      foreground: ctx.input.foreground,
      stopped: ctx.input.stopped,
      description: ctx.input.description,
      metadata: ctx.input.metadata,
      deviceType: ctx.input.deviceType,
      updatedAt: ctx.input.updatedAt
    });

    let user = result.user || {};
    let events = (result.events || []).map((e: any) => ({
      eventId: e._id,
      type: e.type
    }));

    return {
      output: {
        userId: user.userId,
        radarId: user._id,
        eventsGenerated: events.length,
        events
      },
      message: `Location tracked for device **${ctx.input.deviceId}**. Generated **${events.length}** event(s).`
    };
  })
  .build();
