import { SlateAuth } from 'slates';
import { z } from 'zod';
import { Client } from './lib/client';

export let auth = SlateAuth.create()
  .output(z.object({ token: z.string(), alertSourceToken: z.string().optional() }))
  .addTokenAuth({
    type: 'auth.token',
    name: 'API Key',
    key: 'api_key',
    inputSchema: z.object({
      token: z.string().describe('Organization API key from incident.io Settings > API keys.'),
      alertSourceToken: z
        .string()
        .optional()
        .describe(
          'Optional secret generated by the HTTP alert source; required only when sending alert events. This differs from the organization API key.'
        )
    }),
    getOutput: async ctx => ({
      output: { token: ctx.input.token, alertSourceToken: ctx.input.alertSourceToken }
    }),
    getProfile: async (ctx: { output: { token: string; alertSourceToken?: string } }) => {
      const { identity } = await new Client(ctx.output).getIdentity();
      return {
        profile: {
          name: identity.name,
          dashboardUrl: identity.dashboard_url,
          roles: identity.roles
        }
      };
    }
  });
