import { Slate } from 'slates';
import { spec } from './spec';
import {
  createIncident,
  createScheduleOverride,
  deleteScheduleOverride,
  editIncident,
  getCatalogEntry,
  getIdentity,
  getIncident,
  getSchedule,
  getScheduleEntries,
  getStatusPageIncident,
  listAlertSources,
  listAlerts,
  listCatalogEntries,
  listCatalogTypes,
  listFollowUps,
  listIncidentRolesAndTypes,
  listIncidents,
  listSchedules,
  listSeveritiesAndStatuses,
  listStatusPages,
  listUsers,
  listWorkflows,
  manageCatalogEntry,
  manageStatusPageIncident,
  sendAlertEvent
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getIdentity,
    getSchedule,
    deleteScheduleOverride,
    getCatalogEntry,
    listStatusPages,
    getStatusPageIncident,
    listAlertSources,
    listIncidents,
    getIncident,
    createIncident,
    editIncident,
    listAlerts,
    sendAlertEvent,
    listSchedules,
    getScheduleEntries,
    createScheduleOverride,
    listCatalogTypes,
    listCatalogEntries,
    manageCatalogEntry,
    listSeveritiesAndStatuses,
    listIncidentRolesAndTypes,
    listFollowUps,
    manageStatusPageIncident,
    listUsers,
    listWorkflows
  ],
  triggers: []
});
