import { Slate } from 'slates';
import { spec } from './spec';
import {
  cancelJob,
  copyTable,
  createDataset,
  createRoutine,
  createTable,
  deleteDataset,
  deleteModel,
  deleteRoutine,
  deleteTable,
  executeQuery,
  executeSqlReadonly,
  exportData,
  getDataset,
  getJob,
  getModel,
  getRoutine,
  getTable,
  insertRows,
  listDatasets,
  listJobs,
  listModels,
  listRoutines,
  listTables,
  loadData,
  readTableData,
  updateDataset,
  updateModel,
  updateTable
} from './tools';
import { datasetUpdated, inboundWebhook, jobCompleted } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    executeQuery,
    executeSqlReadonly,
    listDatasets,
    getDataset,
    createDataset,
    updateDataset,
    deleteDataset,
    listTables,
    getTable,
    createTable,
    updateTable,
    deleteTable,
    loadData,
    exportData,
    listJobs,
    getJob,
    cancelJob,
    readTableData,
    insertRows,
    copyTable,
    listModels,
    getModel,
    updateModel,
    deleteModel,
    listRoutines,
    getRoutine,
    createRoutine,
    deleteRoutine
  ],
  triggers: [inboundWebhook, jobCompleted, datasetUpdated]
});
