import { Slate } from 'slates';
import { spec } from './spec';
import {
  createConnection,
  deleteConnection,
  downloadJobFile,
  getConnection,
  getFileUrl,
  getFlow,
  getFlowErrors,
  getJob,
  getTokenInfo,
  listConnections,
  listExports,
  listFlows,
  listImports,
  listIntegrations,
  listJobs,
  manageExport,
  manageFlow,
  manageImport,
  manageIntegration,
  manageState,
  manageUsers,
  resolveErrors,
  retryErrors,
  updateConnection
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getTokenInfo,
    downloadJobFile,
    getFileUrl,
    listConnections,
    getConnection,
    createConnection,
    updateConnection,
    deleteConnection,
    listFlows,
    getFlow,
    manageFlow,
    listExports,
    manageExport,
    listImports,
    manageImport,
    listIntegrations,
    manageIntegration,
    getFlowErrors,
    resolveErrors,
    retryErrors,
    listJobs,
    getJob,
    manageUsers,
    manageState
  ],
  triggers: []
});
