import { Slate } from 'slates';
import { spec } from './spec';
import {
  createInstance,
  deleteInstance,
  getCommitmentBasicInfo,
  getDiskBasicInfo,
  getDiskPerformanceConfig,
  getInstanceBasicInfo,
  getInstanceGroupManagerBasicInfo,
  getInstanceTemplateBasicInfo,
  getInstanceTemplateProperties,
  getReservationBasicInfo,
  getReservationDetails,
  getZoneOperation,
  listAcceleratorTypes,
  listCommitmentReservations,
  listCommitments,
  listDisks,
  listImages,
  listInstanceAttachedDisks,
  listInstanceGroupManagers,
  listInstances,
  listInstanceTemplates,
  listMachineTypes,
  listManagedInstances,
  listReservations,
  listSnapshots,
  resetInstance,
  setInstanceMachineType,
  startInstance,
  stopInstance
} from './tools';
import { triggers } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createInstance,
    deleteInstance,
    startInstance,
    stopInstance,
    resetInstance,
    setInstanceMachineType,
    getInstanceBasicInfo,
    listInstances,
    listInstanceAttachedDisks,
    getDiskBasicInfo,
    getDiskPerformanceConfig,
    listDisks,
    listSnapshots,
    listImages,
    listMachineTypes,
    listAcceleratorTypes,
    getInstanceGroupManagerBasicInfo,
    listInstanceGroupManagers,
    listManagedInstances,
    getInstanceTemplateBasicInfo,
    getInstanceTemplateProperties,
    listInstanceTemplates,
    getReservationBasicInfo,
    getReservationDetails,
    listReservations,
    getCommitmentBasicInfo,
    listCommitments,
    listCommitmentReservations,
    getZoneOperation
  ],
  triggers
});
