import { Slate } from '@slates/provider';
import { spec } from './spec';
import {
  addContactsToContactGroup,
  createAccount,
  createBankTransaction,
  createBankTransfer,
  createContact,
  createContactGroup,
  createCreditNote,
  createInvoice,
  createItem,
  createManualJournal,
  createPayment,
  createPurchaseOrder,
  createQuote,
  deletePayment,
  getBankTransfer,
  getContact,
  getContactGroup,
  getInvoice,
  getOrganisation,
  getReport,
  getSettings,
  listAccounts,
  listBankTransactions,
  listBankTransfers,
  listContactGroups,
  listContacts,
  listCreditNotes,
  listInvoices,
  listItems,
  listManualJournals,
  listPayments,
  listPurchaseOrders,
  listQuotes,
  removeContactFromContactGroup,
  updateAccount,
  updateContact,
  updateContactGroup,
  updateCreditNote,
  updateInvoice,
  updateItem,
  updatePurchaseOrder,
  updateQuote
} from './tools';
import { contactChanges, inboundWebhook, invoiceChanges, paymentChanges } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createInvoice,
    getInvoice,
    listInvoices,
    updateInvoice,
    createContact,
    getContact,
    listContacts,
    updateContact,
    listContactGroups,
    getContactGroup,
    createContactGroup,
    updateContactGroup,
    addContactsToContactGroup,
    removeContactFromContactGroup,
    createPayment,
    listPayments,
    deletePayment,
    createCreditNote,
    listCreditNotes,
    updateCreditNote,
    createBankTransaction,
    listBankTransactions,
    listBankTransfers,
    getBankTransfer,
    createBankTransfer,
    listAccounts,
    createAccount,
    updateAccount,
    createPurchaseOrder,
    listPurchaseOrders,
    updatePurchaseOrder,
    createQuote,
    listQuotes,
    updateQuote,
    listItems,
    createItem,
    updateItem,
    createManualJournal,
    listManualJournals,
    getReport,
    getOrganisation,
    getSettings
  ],
  triggers: [inboundWebhook, invoiceChanges, contactChanges, paymentChanges]
});
