import { SlateTool } from 'slates';
import { z } from 'zod';
import { StudioClient } from '../lib/client';
import { spec } from '../spec';

export let createUser = SlateTool.create(spec, {
  name: 'Create User',
  key: 'create_user',
  description: `Create a new user in a Softr application. Optionally generates a magic link for passwordless login. If no password is provided, one will be auto-generated by Softr.

Requires the **domain** to be configured in the integration settings.`,
  tags: {
    destructive: false,
    readOnly: false
  }
})
  .input(
    z.object({
      fullName: z.string().describe('Full name of the user'),
      email: z.string().describe('Email address of the user'),
      password: z
        .string()
        .optional()
        .describe('Password for the user. If omitted, Softr auto-generates one.'),
      generateMagicLink: z
        .boolean()
        .optional()
        .describe('Whether to generate a magic link for passwordless login')
    })
  )
  .output(
    z.object({
      email: z.string().describe('Email of the created user'),
      magicLink: z.string().optional().describe('Generated magic link URL, if requested')
    })
  )
  .handleInvocation(async ctx => {
    if (!ctx.config.domain) {
      throw new Error(
        'The "domain" config is required for user management. Set it to your Softr app domain (e.g., yourapp.softr.app).'
      );
    }

    let client = new StudioClient({
      token: ctx.auth.token,
      domain: ctx.config.domain
    });

    let result = await client.createUser({
      fullName: ctx.input.fullName,
      email: ctx.input.email,
      password: ctx.input.password,
      generateMagicLink: ctx.input.generateMagicLink
    });

    return {
      output: {
        email: ctx.input.email,
        magicLink: result?.magic_link ?? result?.magicLink
      },
      message: `User **${ctx.input.fullName}** (${ctx.input.email}) created successfully.${ctx.input.generateMagicLink ? ' A magic link was generated.' : ''}`
    };
  })
  .build();
