import { Slate } from 'slates';
import { spec } from './spec';
import {
  autofillBrandTemplate,
  createComment,
  createDesign,
  createFolder,
  deleteAsset,
  deleteFolder,
  exportDesign,
  getAsset,
  getAssetUploadJob,
  getAutofillJob,
  getBrandTemplate,
  getCommentThread,
  getDesign,
  getExportJob,
  getFolder,
  getImportJob,
  getUserProfile,
  importDesign,
  listBrandTemplates,
  listDesigns,
  listFolderItems,
  moveFolderItem,
  updateAsset,
  updateFolder,
  uploadAsset
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    getUserProfile,
    getAsset,
    updateAsset,
    deleteAsset,
    uploadAsset,
    getAssetUploadJob,
    getAutofillJob,
    listDesigns,
    getDesign,
    createDesign,
    exportDesign,
    getExportJob,
    importDesign,
    getImportJob,
    getFolder,
    createFolder,
    updateFolder,
    deleteFolder,
    listFolderItems,
    moveFolderItem,
    createComment,
    getCommentThread,
    listBrandTemplates,
    getBrandTemplate,
    autofillBrandTemplate
  ],
  triggers: []
});
