import { Slate } from 'slates';
import { spec } from './spec';
import {
  addJobComment,
  createCompany,
  createContact,
  createExpense,
  createJob,
  deleteTimeEntry,
  duplicateJob,
  getCompany,
  getContact,
  getExpense,
  getInvoice,
  getJob,
  getOrganisation,
  getQuote,
  getTimeEntry,
  listRoles,
  listUsers,
  logTime,
  manageJobPlan,
  manageLabels,
  recordInvoicePayment,
  searchInvoices,
  searchJobs,
  updateCompany,
  updateContact,
  updateExpense,
  updateInvoice,
  updateJob,
  updateTimeEntry
} from './tools';
import { inboundWebhook, newCompany, newInvoice, newJob } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    createJob,
    getJob,
    updateJob,
    searchJobs,
    duplicateJob,
    addJobComment,
    manageJobPlan,
    createCompany,
    getCompany,
    updateCompany,
    createContact,
    getContact,
    updateContact,
    logTime,
    getTimeEntry,
    updateTimeEntry,
    deleteTimeEntry,
    createExpense,
    getExpense,
    updateExpense,
    getInvoice,
    updateInvoice,
    recordInvoicePayment,
    searchInvoices,
    getQuote,
    manageLabels,
    listUsers,
    listRoles,
    getOrganisation
  ],
  triggers: [inboundWebhook, newJob, newInvoice, newCompany]
});
