import { Slate } from 'slates';
import { spec } from './spec';
import {
  addContactsToList,
  addSuppressedEmails,
  createContactList,
  createSuppressionGroup,
  createTemplate,
  createVerifiedSender,
  deleteContactList,
  deleteContacts,
  deleteSuppressionGroup,
  deleteTemplate,
  deleteVerifiedSender,
  getContact,
  getContactCount,
  getContactImportStatus,
  getContactList,
  getContactListCount,
  getEmailStats,
  getSuppressionGroup,
  getTemplate,
  listContactLists,
  listEventWebhooks,
  listSuppressionGroups,
  listSuppressions,
  listTemplates,
  listVerifiedSenders,
  removeContactFromList,
  removeSuppressedEmail,
  resendSenderVerification,
  searchContacts,
  sendEmail,
  updateContactList,
  updateSuppressionGroup,
  updateTemplate,
  upsertContacts
} from './tools';
import { emailEvents, inboundEmail } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    sendEmail.build(),
    listTemplates.build(),
    getTemplate.build(),
    createTemplate.build(),
    updateTemplate.build(),
    deleteTemplate.build(),
    upsertContacts.build(),
    getContactImportStatus.build(),
    getContactCount.build(),
    searchContacts.build(),
    getContact.build(),
    deleteContacts.build(),
    listContactLists.build(),
    getContactList.build(),
    getContactListCount.build(),
    createContactList.build(),
    addContactsToList.build(),
    updateContactList.build(),
    deleteContactList.build(),
    removeContactFromList.build(),
    listSuppressionGroups.build(),
    getSuppressionGroup.build(),
    createSuppressionGroup.build(),
    updateSuppressionGroup.build(),
    deleteSuppressionGroup.build(),
    addSuppressedEmails.build(),
    removeSuppressedEmail.build(),
    listSuppressions.build(),
    getEmailStats.build(),
    listVerifiedSenders.build(),
    createVerifiedSender.build(),
    deleteVerifiedSender.build(),
    resendSenderVerification.build(),
    listEventWebhooks.build()
  ],
  triggers: [emailEvents.build(), inboundEmail.build()]
});
