import { Slate } from 'slates';
import { spec } from './spec';
import {
  createContactGroup,
  createHeartbeatTest,
  createMaintenanceWindow,
  createPagespeedTest,
  createSslTest,
  createUptimeTest,
  deleteContactGroup,
  deleteHeartbeatTest,
  deleteMaintenanceWindow,
  deletePagespeedTest,
  deleteSslTest,
  deleteUptimeTest,
  getContactGroup,
  getHeartbeatTest,
  getMaintenanceWindow,
  getPagespeedHistory,
  getPagespeedTest,
  getSslTest,
  getUptimeHistory,
  getUptimeTest,
  listContactGroups,
  listHeartbeatTests,
  listMaintenanceWindows,
  listMonitoringLocations,
  listPagespeedTests,
  listSslTests,
  listUptimeTests,
  updateContactGroup,
  updateHeartbeatTest,
  updateMaintenanceWindow,
  updatePagespeedTest,
  updateSslTest,
  updateUptimeTest
} from './tools';
import { monitoringAlert } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listUptimeTests,
    getUptimeTest,
    createUptimeTest,
    updateUptimeTest,
    deleteUptimeTest,
    getUptimeHistory,
    listPagespeedTests,
    getPagespeedTest,
    createPagespeedTest,
    updatePagespeedTest,
    deletePagespeedTest,
    getPagespeedHistory,
    listSslTests,
    getSslTest,
    createSslTest,
    updateSslTest,
    deleteSslTest,
    listHeartbeatTests,
    getHeartbeatTest,
    createHeartbeatTest,
    updateHeartbeatTest,
    deleteHeartbeatTest,
    listContactGroups,
    getContactGroup,
    createContactGroup,
    updateContactGroup,
    deleteContactGroup,
    listMaintenanceWindows,
    getMaintenanceWindow,
    createMaintenanceWindow,
    updateMaintenanceWindow,
    deleteMaintenanceWindow,
    listMonitoringLocations
  ],
  triggers: [monitoringAlert]
});
