import { Slate } from 'slates';
import { spec } from './spec';
import {
  addCollectionItemTool,
  chatCompletionTool,
  commentOnDiscussionTool,
  controlSpaceTool,
  createCollectionTool,
  createDiscussionTool,
  createRepositoryTool,
  deleteCollectionTool,
  deleteFileTool,
  deleteRepositoryTool,
  getCollectionTool,
  getDiscussionTool,
  getFileContentTool,
  getRepositoryInfoTool,
  getSpaceRuntimeTool,
  getUserInfoTool,
  listDiscussionsTool,
  listRepoFilesTool,
  manageSpaceSecretsTool,
  manageSpaceVariablesTool,
  removeCollectionItemTool,
  runInferenceTool,
  searchDatasetsTool,
  searchModelsTool,
  searchSpacesTool,
  textGenerationTool,
  updateDiscussionStatusTool,
  updateRepositoryVisibilityTool,
  uploadFileTool
} from './tools';
import { repositoryEventsTrigger } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    searchModelsTool,
    searchDatasetsTool,
    searchSpacesTool,
    createRepositoryTool,
    deleteRepositoryTool,
    getRepositoryInfoTool,
    updateRepositoryVisibilityTool,
    listRepoFilesTool,
    getFileContentTool,
    uploadFileTool,
    deleteFileTool,
    listDiscussionsTool,
    getDiscussionTool,
    createDiscussionTool,
    commentOnDiscussionTool,
    updateDiscussionStatusTool,
    getCollectionTool,
    createCollectionTool,
    deleteCollectionTool,
    addCollectionItemTool,
    removeCollectionItemTool,
    getSpaceRuntimeTool,
    controlSpaceTool,
    manageSpaceSecretsTool,
    manageSpaceVariablesTool,
    chatCompletionTool,
    textGenerationTool,
    runInferenceTool,
    getUserInfoTool
  ],
  triggers: [repositoryEventsTrigger]
});
