import { Slate } from 'slates';
import { spec } from './spec';
import {
  addPersonToCadence,
  createAccount,
  createNote,
  createPerson,
  deleteAccount,
  deleteNote,
  deletePerson,
  getAccount,
  getCadence,
  getEmailTemplate,
  getMe,
  getNote,
  getPerson,
  getTask,
  listAccounts,
  listCadenceMemberships,
  listCadences,
  listCallActivities,
  listEmailActivities,
  listEmailTemplates,
  listNotes,
  listPeople,
  listTasks,
  listUsers,
  logCall,
  removePersonFromCadence,
  updateAccount,
  updateNote,
  updatePerson
} from './tools';
export let provider = Slate.create({
  spec,
  tools: [
    createPerson,
    updatePerson,
    getPerson,
    deletePerson,
    listPeople,
    createAccount,
    updateAccount,
    getAccount,
    deleteAccount,
    listAccounts,
    listCadences,
    getCadence,
    addPersonToCadence,
    removePersonFromCadence,
    listEmailActivities,
    listCallActivities,
    logCall,
    createNote,
    updateNote,
    listNotes,
    listEmailTemplates,
    getEmailTemplate,
    listTasks,
    getTask,
    listUsers,
    getMe,
    getNote,
    deleteNote,
    listCadenceMemberships
  ],
  triggers: []
});
