import { Slate } from 'slates';
import { spec } from './spec';
import {
  addProposalFee,
  addProposalSection,
  createClient,
  createFee,
  createProposal,
  createSection,
  deleteClient,
  deleteFee,
  deleteProposal,
  deleteSection,
  getClient,
  getProposal,
  getProposalStats,
  getTemplate,
  listClients,
  listFees,
  listProposalFees,
  listProposalSections,
  listProposals,
  listSections,
  listTemplates,
  removeProposalFee,
  removeProposalSection,
  updateClient,
  updateFee,
  updateProposal,
  updateProposalFee,
  updateProposalSection,
  updateSection
} from './tools';
import { clientCreated, proposalEvents } from './triggers';

export let provider = Slate.create({
  spec,
  tools: [
    listClients,
    getClient,
    createClient,
    updateClient,
    deleteClient,
    listProposals,
    getProposal,
    createProposal,
    updateProposal,
    deleteProposal,
    getProposalStats,
    listFees,
    createFee,
    updateFee,
    deleteFee,
    listSections,
    createSection,
    updateSection,
    deleteSection,
    listProposalSections,
    addProposalSection,
    updateProposalSection,
    removeProposalSection,
    listProposalFees,
    addProposalFee,
    updateProposalFee,
    removeProposalFee,
    listTemplates,
    getTemplate
  ],
  triggers: [clientCreated, proposalEvents]
});
